### ISSUE TITLE
Make lego more search friendly with godoc.org

### ISSUE THREAD

**Issue by xi2** [xenolf/lego#106]
Hi. Firstly, thank you for making lego. It's working great for me. This is not a bug report, but merely a suggestion.

When I go looking for Go stuff my first try is normally to type the thing I am looking for into godoc.org (e.g. "lets encrypt" or "acme"). I actually did this twice over the last couple of months and failed to notice lego. I eventually found it a day or two ago via a blog post.

This could be easily remedied by adding single line package comments as discussed at https://golang.org/doc/effective_go.html#commentary for github.com/xenolf/lego and github.com/xenolf/lego/acme. I can't believe I'm the only one looking on godoc.org before looking elsewhere!

Best wishes and thanks again for lego.

**Comment by mholt** [comment]
I can work on this.

**Comment by xenolf** [comment]
So we just need to add `Let's encrypt and ACME CLI package` to the main package and `ACME library implementation` to the acme package? (for example)

**Comment by xi2** [comment]
Yes, I believe so. Then if I type "let's encrypt" into Godoc search, because that string is in the package description, it should come up. And more importantly it shows what lego is used for. :)

**Comment by xenolf** [comment]
Well, that shouldn't be too hard to add then :wink: 

Thanks for bringing it to our attention!
