### ISSUE TITLE
Reverse proxying to lego requires modifying reverse proxy transport

### ISSUE THREAD

**Issue by xi2** [xenolf/lego#107]
Hi. I'm not sure if this is a bug or not, but if not it might be worth documenting somewhere if it isn't.

My setup is that I wanted to run lego on a non-standard port (using the --http flag) and have http-01 acme challenges forwarded to lego from my two web servers.

My first attempt at doing so was to add 302 http redirects but for some reason the Let's Encrypt validation servers just wouldn't play ball (even though everyone on the net says http redirects works fine). This was nothing to do with lego, but I just thought I'd mention it.

Having failed at that I decided to use httputil.ReverseProxy from the Go standard library to send on the challenges. This worked great with my first web server which has a single domain name on the certificate. However my second web server, which has a SAN Multi-Domain certificate, failed. The first domain on the certificate validated fine with Let's Encrypt's servers, but the second did not whith lego returning an acme "404" error.

After a bit of head scratching I turned off re-use of TCP connections between different HTTP requests in the transport of the reverse proxy by setting DisableKeepAlives in the transport to true. Then everything worked perfectly! :)

Anyway, I just thought I'd let you guys know in case it was of interest.

**Comment by xi2** [comment]
To reply to myself, I've just made a patch to lego that (I believe) solves the problem. I will submit a PR in in minute or two (never done one before!)

**Comment by xenolf** [comment]
I think 302 redirects only work for redirecting from a domain to another (www.example.com to example.com) and not to a different port for that matter.

About the KeepAlive problem, you are completely right :)

**Comment by xi2** [comment]
Great. It's my first PR so glad not to have made a fool of myself :)
