### ISSUE TITLE
Add a Go web server+Lego tutorial to wiki?

### ISSUE THREAD

**Issue by xi2** [xenolf/lego#109]
Hi Legoers. I've been so impressed with Lego after discovering it a couple of days ago that I made a short tutorial describing my setup to try to help others. You can find it here:

<https://github.com/xi2/lego/wiki/A-100%25-automated-Lego-setup-for-Go-web-servers>

Sorry for creating a Github issue, but there doesn't seem to be pull requests for the wiki?

Is the tutorial worth adding the wiki? I didn't want to just dump it on there as that seemed a bit rude. If it's not the right sort of thing then I will probably stick it on my blog so that's OK too and there'd be no offence caused. :)

Best wishes

**Comment by xenolf** [comment]
So I'm curious. Why did you decide to use exec/command to run the lego binary and not to embed the library directly into your projects?

**Comment by xi2** [comment]
Hi xenolf. That is a good question. The reasons are that (1) I was exec-ing the scp binary anyway, so it's not like I'd have avoided using exec, and (2) I wanted to capture the nice terminal output of the lego command since it gets sent in the email for inspection. I could of course have replicated that output that with my own Fprintf's and acme package API calls, but for the tutorial I was trying to keep the code as short as I possible. If you think it's stylistically or pedagogically bad I can change it, naturally, but I think it would be more lines of code. Anyway, thanks for looking it over.

**Comment by xenolf** [comment]
No, I was just curious :smile: 

I feel like this would make a great blog post, but for the wiki it's a bit too specific I'm afraid.

**Comment by xi2** [comment]
With hindsight, I think you are completely right in that it's far too specific to my setup. It will go on my blog :-)
