### ISSUE TITLE
Provide builds with go 1.5

### ISSUE THREAD

**Issue by gmbuell** [xenolf/lego#114]
Hello,

I'm guessing the current releases are built with go 1.6 which attempts to use http/2 which doesn't currently work with the lets encrypt production servers. Given that go 1.6 has not yet been released, it seems like the released binaries should be built with 1.5 to fix this issue.

**Comment by xi2** [comment]
I don't know about the binaries you are using, but I'm using a self-compiled lego binary built with Go 1.6rc2 and it's working fine. I had 2 certs issued today.

**Comment by xi2** [comment]
I should add I'm using latest master.

**Comment by xenolf** [comment]
The current binaries which are up for download are compiled using go 1.5.3.
