### ISSUE TITLE
Error creating new registration

### ISSUE THREAD

**Issue by gmbuell** [xenolf/lego#115]
When creating a new certificate, I get the following error with the current released binaries:
acme: Error 500 - urn:acme:error:serverInternal - Error creating new registration

My command is lego --email=gmbuell@gmail.com --domains=gmbuell.com run
This command works successfully if run against the staging servers.

**Comment by xenolf** [comment]
Did you run the command against staging or against live first?

**Comment by gmbuell** [comment]
Ah, I had some cached data in my docker volume. Sorry about that. Closing.
