### ISSUE TITLE
Add support for boulder dns-test-srv

### ISSUE THREAD

**Issue by strothj** [xenolf/lego#117]
Boulder contains a test DNS server:
https://github.com/letsencrypt/boulder/tree/master/test/dns-test-srv

You can see it in use here:
https://github.com/letsencrypt/boulder/blob/master/test/js/test.js

Adding a DNSProvider for this would allow plugging in for end to end testing.

Adding support for this would involve writing a DNSProvider and allowing for an override of the DNS server used in dnsprovider.go.

Is this something that is likely to be merged in if a pull request is provided?

**Comment by strothj** [comment]
I have a working version in my branch. I'm able to use lego against the test DNS server running from the boulder docker-compose setup like so:
`BOLDER_DNS_URL="http://127.0.0.1:8055" $GOPATH/bin/lego --domains example.com --server "http://127.0.0.1:4000/directory" --email "admin@example.com" --exclude "http-01" --exclude "tls-sni-01" --dns bouldertest run`

You'll see a response from the test DNS server in the docker session:
`boulder_1          | dns-srv: added TXT record for _acme-challenge.example.com. containing "7jRNrp68Qo7SbkURQkZjbBrhTl0Ljjkd1o3r4PxthXs"`

`2016/02/10 05:13:52 [INFO][example.com] acme: Obtaining bundled SAN certificate
2016/02/10 05:13:52 [INFO][example.com] acme: Could not find solver for: tls-sni-01
2016/02/10 05:13:52 [INFO][example.com] acme: Could not find solver for: http-01
2016/02/10 05:13:52 [INFO][example.com] acme: Trying to solve DNS-01
2016/02/10 05:14:03 [INFO][example.com] The server validated our request
2016/02/10 05:14:03 [INFO][example.com] acme: Validations succeeded; requesting certificates
2016/02/10 05:14:04 [INFO] acme: Requesting issuer cert from http://127.0.0.1:4000/acme/issuer-cert
2016/02/10 05:14:04 [INFO][example.com] Server responded with a certificate.`

**Comment by xenolf** [comment]
I am actually working on integration testing against boulder in a local branch to allow for proper integration tests of all the challenges.

Didn't add DNS-01 support yet though :)
