### ISSUE TITLE
question regarding usage

### ISSUE THREAD

**Issue by gedw99** [xenolf/lego#12]
I am a go developer and am running servers on google compute and AWS.

I saw the python client and how it kind of integrates with Apache. Nice for Apache users but useless for me.

Is there some docs yet regarding using this go based client ?
Can i participate in testing domains and wildcard domains ? I would like to try this out for our development environments now.

**Comment by mholt** [comment]
You can try it out :) Let's Encrypt has a staging API you can hit or you can run your own Boulder instance.

As for docs, have you seen the readme?

**Comment by gedw99** [comment]
Hey @mholt 

Your the Caddy guy :)

Readme looks ok. Let me give this a shot.
i am using go and appengine and Caddy. I have a simple code switch so i can run on both.
Do you think it should work on app engine and gcloud ?

**Comment by xenolf** [comment]
It should (should as in I didn't try it out) work in both environments. :)

**Comment by gedw99** [comment]
Ok i am just learning hwo to use it:

I am BTW:
OSX
golang 1.5.1

SO when i do this:
./lego --email="123@gmail.com" --domains="www.xyz.de" run:

````

2015/10/21 15:48:47 Obtaining certificates...
2015/10/21 15:48:49 SimpleHTTP: Domain www.xyz.de does not resolve to the public ip of this server. Determined IP: 89.46.195.77 Resolved IP: 47.31.143.1
2015/10/21 15:48:49 Could not find solver for: simpleHttp
2015/10/21 15:48:49 Could not find solver for: dvsni
2015/10/21 15:48:49 Could not find solver for: http-01
2015/10/21 15:48:49 Could not find solver for: tls-sni-01
2015/10/21 15:48:49 Could not obtain certificates
	Could not determine solvers for www.berlininfusions.de

```


So dumb question:
1. I have to run this on the actual server that will be serving, just like normal SSL ?
- If yes, then i guess i can try the google cloud shell to do it.
https://cloud.google.com/cloud-shell/docs/

**Comment by xenolf** [comment]
Well, you do not have to use the client. The client comes with a library as well so you could actually build LE directly into your go programs.

Other then that, you won't get a certificate from the staging CA for a domain which does not resolve to the ip address of the host you are running lego on.

**Comment by mholt** [comment]
If you want to test the entire process in your dev environment you'll need to set up a local Boulder instance that can work locally; the staging API uses real DNS to resolve your hostname to the real machine (it just issues a non-trusted certificate).

**Comment by gedw99** [comment]
it works in the google cloud console BTW. Go same distance.

Regarding IP resolution. Yes thats makes sense.
Regarding embedding the lego softwar, it will not work on google cloud app engine i presume because its a read only file system. Instead the normal way is to  uploaded the SSL cert
https://cloud.google.com/appengine/docs/using-custom-domains-and-ssl?hl=en#adding_ssl_to_your_custom_domain

SO its a chicken and egg problem.

**Comment by xenolf** [comment]
The library itself does not save anything. It it left to your application as to where you store that stuff.

**Comment by gedw99** [comment]
@mholt 
Ok using Boulder makes sense. Tats great for have the whole thing in the one environment.
For now, i dont want to go that far. Thats more for later.
Right now i just want to test getting an existing junk web site using SSL.
This web site is on appengine.

When i run the exe, it saved stuff to the account dir.

**Comment by mholt** [comment]
@gedw99 What xenolf meant is that the acme client library (the Go package you can import into your own programs) doesn't save anything. The command (the CLI tool in the main package) *does* save the cert and user information to disk for you.

**Comment by gedw99** [comment]
@mholt 
OK - penny drops.
I see the JWS code now. 
So the architecture is designed to be way way easier than the normal process.
Steps: 
Fire up a web site
Go to some URL (like admin area)
Request the cert (via soem UI)
And it will under the hood do all the bits and pieces ?

**Comment by gedw99** [comment]
Ok i now see the code in the readme and its intent / usage paradigm. +1

So when i get to below, where to put this if on AppEngine.  

````
// Each certificate comes back with the cert bytes, the bytes of the client's
// private key, and a certificate URL. This is where you should save them to files!
fmt.Printf("%#v\n", certificates)

```

**Comment by kuba** [comment]
@gedw99, official client doesn't need Apache/nginx or any other web server. Just use the standalone authenticator - either select from the menu or run `letsencrypt -a standalone`. +it should work on Google App Engine. We are also working on exposing programmatic API, so you don't have to shell out to call the binary.

**Comment by gedw99** [comment]
@kuba 
thanks. but the exe is called lego, not lets-encrypt.

Can i ask that a basic newbie, how to get running on App Engine or other be written ?
Sorry

**Comment by mholt** [comment]
@gedw99, kuba is referring to the official letsencrypt client, not this one.

Before continuing: Are you trying to use the *LIBRARY* in your own Go program (this means your Go program imports `github.com/xenolf/acme`) **or** are you trying to use the *CLI TOOL* as a client? The CLI tool will have to be executed from the command line ("lego") and requires writing to the disk.

This CLI tool is somewhat analogous to the official `letsencrypt` client, but this one is less mature. Simply depends what you're trying to do.

**Comment by gedw99** [comment]
@mholt 
thanks.

The objective is to get an appengine web site using SSL. How i get there up for debate.
Its golang based.

I tried the letsencrypt python CLI. I kind of hate python, and so i really want to use this golang based one.
Hence, why i am here bugging you guys :)

In my own library ?
Well i could link it into my golang web site code. But i need a bit of help I presume i setup a handler or something. This is what i was referring to before.

Fro the CLI ?
Tried that and we worked out that because i cant SSH into the server running the web server its not goin to work.

What do you advise ?

**Comment by xenolf** [comment]
The readme does outline a full sample of the library usage. You can also have a look at how we integrated it into caddy [here](https://github.com/mholt/caddy/tree/letsencrypt/config/letsencrypt).
