### ISSUE TITLE
Provide filter script for certificate generation

### ISSUE THREAD

**Issue by fenderle** [xenolf/lego#120]
Currently the CA chain and the certificate is bundled into the crt file, while the key resides in the key file. This is all great and good but there are many cases where we would need other formats, because there is not only apache but many other daemons which come with all sorts of ssl configuration requirements. Some want everything in one file (eg. haproxy), some want everything split up, etc. 

So I would propose the following:

1. keep the current output files as they are to ensure compatibility with existing scripts and to give lego a known baseline
2. provide a simple, scriptable filter api:

- add a new command line option to run and renew (or only to renew): `--filter`
- the `--filter` option will accept the name of an executable (which might be a shell script)
- make sure the `--filter` script is only called if the certificate changes
- lego uses env variables to pass the cert, the cachain and the key including metadata (domain, etc) to the filter executable
- the script could then easiliy output the files in their required format and location
- and could then signal the daemons to reload or restart them

Currently I have to use an extra script to split the certs up and rearrange them as required by the daemons using them (ca, crt and key in separate files or everything in one file, etc). Of course this also involves checking if the certs have been renewed at all, plus restarting the daemon, etc. All this is _a lot_ of boilerplate considering how easy it could be if lego was a bit more cooperative in handling the output.

Thoughts? Better ways to do this?

**Comment by xenolf** [comment]
I'm afraid I'm not understanding how adding a `--format` option would make your example any better?
You are using a script now to split the certificates up, I get that. But you would still need a script or program to do that when it gets called by lego using the `--format` switch.
Is your issue only in the passing around of data?

I actually didn't decide on the cert file format with apache or any web server in mind for that matter. I simply used this format because it's what go uses and understands.

**Comment by xenolf** [comment]
I will close this for inactivity. If you have anything to add feel free to re-open the issue.

**Comment by hanoii** [comment]
I actually come across this need, I need the intermediate certificate on a separate file, of course I could split it myself with a script, I just think it's simpler to concatenate two files and split them if needed together. But just sharing a thought.

**Comment by hanoii** [comment]
And for what it's worth:

```
csplit -f file.crt- file.crt '/-----BEGIN CERTIFICATE-----/' '{1}' -z
```

splits it nicely :)
