### ISSUE TITLE
lego/acme contains OCSP support

### ISSUE THREAD

**Issue by willglynn** [xenolf/lego#129]
`lego/acme` contains `GetOCSPForCert()`. [The implementation](https://github.com/xenolf/lego/blob/00f13f2da0cc14530d9d113854cbda054e00d569/acme/crypto.go#L47-L124) does not appear ACME-specific, and this method isn't used by anything else inside `lego/acme` or the `lego` tool.

Why is this method in `lego/acme`? Should this method be relocated to a different package (e.g. `lego/ocsp`) to reduce `lego/acme`'s dependencies (#100)?

**Comment by mholt** [comment]
Let's Encrypt, which is so far the only ACME CA, strongly encourages OCSP stapling, so the library includes an RFC-compliant function to make it easier to do it right.

I guess it could be moved to a different package but it would only contain a few functions, some of which are currently unexported and used by other functions in the acme package.

**Comment by mholt** [comment]
Although perhaps we could move much of the crypto file to a new package called `certificates ` that deals with parsing, encoding, decoding, OCSP, etc, all other things related to certificates that is useful for the acme package and its importers.

**Comment by willglynn** [comment]
Sure, but… everyone in the ecosystem encourages OCSP stapling. This responsibility falls on whatever program is actually using the certificate, not on the library that obtained it.

I understand that tools like caddy have every reason to incorporate OCSP stapling, but `GetOCSPForCert()` works fine for non-ACME certificates, and it's not actually related to ACME, so it seems out of place in `lego/acme`.

**Comment by xenolf** [comment]
There are multiple things inside the `acme` package which strictly aren't any concern for ACME. Most of the functions in `crypto.go` deal with encoding and/or transforming certificates which is not part of ACME either but strife to make the experience for the consumer of the library better. 

I'm not against moving it into it's own package, but the question is if a single function warrant it's own package plus the re-implementation of the functions it uses?

**Comment by willglynn** [comment]
The broader `lego/acme` package and the `lego` CLI can't help but deal with certificates, keys, and signatures, so keeping things like PEM encoding/decoding local to the package seems appropriate even if it's not strictly ACME-related.

`GetOCSPForCert()` is the only reason `lego/acme` pulls in `golang.org/x/crypto/ocsp`, and isn't needed at all unless you're a TLS server that's trying to follow best practices. If you *are* a TLS server that's trying to follow best practices, you should implement OCSP stapling regardless of who issued your certificates.

As for supporting functions: `GetOCSPForCert()` doesn't need much, see 4ce187dfd28bd25a2bad2e12a15467c2b885521b. `httpGet()` and `httpPost()` are both called exactly once, so those could be reduced straight into `net/http`.

`parsePEMBundle()` needed to be brought over to preserve the method signature, but considering the use case, I think it's better to drop it. Anything interested in OCSP stapling is guaranteed to have parsed the certificate chain already; see e.g. [`mholt/caddy`'s `makeCertificate()` function](https://github.com/mholt/caddy/blob/7bd2adf0dc3a6f4c0eefe3072043de42d1cd8273/caddy/https/certificates.go#L165-L191) or [`dispatch/letsencrypt`'s `state` struct](https://github.com/khlieng/dispatch/blob/master/letsencrypt/letsencrypt.go#L73-L79). I think `GetOCSPForCert()` should take a `*tls.Certificate` or a slice of `x509.Certificate`s instead.

**Comment by mholt** [comment]
> GetOCSPForCert() is the only reason lego/acme pulls in golang.org/x/crypto/ocsp, and isn't needed at all unless you're a TLS server that's trying to follow best practices. If you are a TLS server that's trying to follow best practices, you should implement OCSP stapling regardless of who issued your certificates.

I would argue that nearly every user of ACME certificates are using TLS in some form or another, whether it be for mail or web, etc., and every TLS server should follow basic best practices especially OCSP since every client that relies on a certificate for security should check its revocation status.

The whole point of ACME is to be integrated directly into the TLS servers. And every TLS server should staple OCSP. There is basically one good way to get OCSP according to spec, so we might as well offer it for other programs to use, so they can do it correctly. 

> As for supporting functions: GetOCSPForCert() doesn't need much, see 46c6100. httpGet() and httpPost() are both called exactly once, so those could be reduced straight into net/http.

Unfortunately, these set a User-Agent header, which is customizable by the application that imports the acme package. So it's not as simple as just using net/http. There's state from the acme package that is needed.

> parsePEMBundle() needed to be brought over to preserve the method signature, but considering the use case, I think it's better to drop it. Anything interested in OCSP stapling is guaranteed to have parsed the certificate chain already; see e.g. mholt/caddy's makeCertificate() function ... I think GetOCSPForCert() should take a *tls.Certificate or a slice of x509.Certificates instead.

Yeah, I've actually come very close to refactoring GetOCSPForCert a little bit so that it can accept PEM bytes like it does now or another function that accepts DER bytes or tls.Certificate. Sometimes all we have is the PEM bytes, and other times all we have is the DER bytes (stored in a tls.Certificate -- although I'm not sure that a pointer, *tls.Certificate, is necessary).

**Comment by willglynn** [comment]
> I would argue that nearly every user of ACME certificates are using TLS in some form or another, whether it be for mail or web, etc., and every TLS server should follow basic best practices especially OCSP since every client that relies on a certificate for security should check its revocation status.

I agree that ACME users are almost certainly TLS users. I disagree with assuming that ACME *library* users are also TLS servers, hence my objection to bundling OCSP in `lego/acme`.

> The whole point of ACME is to be integrated directly into the TLS servers.

That is one way to use ACME. If this were the only way ACME was intended to be used, then ACME would have no need for challenges besides `tls-sni-01`.

ACME is designed to support a broad range of use cases. At the present time, the most common pattern involves using a tool to talk ACME and to record certificates to disk, and pairing it with ACME-oblivious server software that loads certificates from disk. In this use case, the ACME-related software never makes an OCSP request.

> There is basically one good way to get OCSP according to spec, so we might as well offer it for other programs to use, so they can do it correctly.

Agreed. I'm not saying it needs to go away, I'm just saying it doesn't belong in `lego/acme`.

> Unfortunately, these set a User-Agent header, which is customizable by the application that imports the acme package. So it's not as simple as just using net/http. There's state from the acme package that is needed.

Or, if `lego/ocsp` is a separate package, then `lego/ocsp` should have its own way to customize the user-agent in order to avoid needless inter-dependencies. ACME clients import `lego/acme`, TLS servers import `lego/ocsp`, TLS servers with built-in ACME clients import both.

Why does `lego/acme` let the user customize the User-Agent but not other aspects of its requests? (It would be more flexible if the user could provide an `http.Client` instead.) Does the same rationale for `lego/acme` in general apply to `GetOCSPForCert()` in particular?

> Sometimes all we have is the PEM bytes, and other times all we have is the DER bytes (stored in a tls.Certificate -- although I'm not sure that a pointer, *tls.Certificate, is necessary).

Does it ever happen that all you have are PEM bytes in a context when you want an OCSP response?

I'm struggling to identify a use case where the caller of `GetOCSPForCert()` ever wants to do anything besides put the OCSP response in a `tls.Certificate`'s `OCSPStaple` field. (Google couldn't find one, either; that's what both users above do right now.) Passing in a `*tls.Certificate` would let `GetOCSPForCert()` take a single parameter containing everything it needs, and it could record the `[]byte` output directly on that `*tls.Certificate`, which saves the caller a step too.

**Comment by mholt** [comment]
> Why does lego/acme let the user customize the User-Agent but not other aspects of its requests? (It would be more flexible if the user could provide an http.Client instead.)

Nothing else needs to be customized... and requests are orthogonal to the http.Client that is used, I'm not sure why providing their own client would help.

> Does the same rationale for lego/acme in general apply to GetOCSPForCert() in particular?

Yeah, we want the servers to know who is request OCSP.

> Does it ever happen that all you have are PEM bytes in a context when you want an OCSP response?

Yes. We can decode the PEM but that step is not necessary all the time, since the DER bytes are needed anyway.

> I'm struggling to identify a use case where the caller of GetOCSPForCert() ever wants to do anything besides put the OCSP response in a tls.Certificate's OCSPStaple field.

I want to store the parsed OCSP response alongside the tls.Certificate so I don't have to keep parsing it every time I want to see if it's expiring. But I do agree that one variation of the function signature could accept a tls.Certificate.

The problem with passing in a pointer to tls.Certificate, though, is that you're changing it *at the same time* TLS handshakes are being served - it's a race condition. At least, for most TLS servers.

**Comment by willglynn** [comment]
> I want to store the parsed OCSP response alongside the tls.Certificate so I don't have to keep parsing it every time I want to see if it's expiring. … The problem with passing in a pointer to tls.Certificate, though, is that you're changing it at the same time TLS handshakes are being served - it's a race condition. At least, for most TLS servers.

Hmm… maybe the more fundamental issue is that `GetOCSPForCert()` is only a partial solution.

Stepping back: the purpose is to make OCSP stapling correct and convenient for Go TLS servers, right? So… why force the TLS server to juggle OCSP responses at all?

I'm picturing a function that takes a `tls.Certificate`, launches a goroutine, and returns something that you can call to get more `tls.Certificate`s later. (You'd want to use it in a `tls.Server` `GetCertificate()` callback.) `lego/ocsp` would be responsible for gathering the state it needs, obtaining an initial response, and refreshing the OCSP response before it expires. It would also be responsible for handling situations where the OCSP server is unreachable/unresponsive or returning nonsense instead of punting these situations downstream.

The caller would always get a `tls.Certificate` immediately containing the best OCSP response available at the time. Issues that pop up related to the OCSP lifecycle could be solved centrally in `lego/ocsp` instead of in every consuming application.

Something like this seems much better than exporting `GetOCSPForCert()` and making the TLS server figure it out. Are there use cases that need to be addressed besides being able to get a `tls.Certificate` with a current OCSP response at all times?

**Comment by mholt** [comment]
> I'm picturing a function that takes a tls.Certificate, launches a goroutine, and returns something that you can call to get more tls.Certificates later. (You'd want to use it in a tls.Server GetCertificate() callback.) lego/ocsp would be responsible for gathering the state it needs, obtaining an initial response, and refreshing the OCSP response before it expires. It would also be responsible for handling situations where the OCSP server is unreachable/unresponsive or returning nonsense instead of punting these situations downstream.

IMO that's scope creep.

But having GetOCSPForCert() is pretty much a necessity since Let's Encrypt supports must-staple. So I can see why a Let's Encrypt client lib might provide it as a convenience.

**Comment by xenolf** [comment]
Will remain as is for now.
