### ISSUE TITLE
--tls flag not working

### ISSUE THREAD

**Issue by loop0** [xenolf/lego#134]
Hi,

I tried to generate a certificate using the --tls flag to change the https challenge server port but it appear to have no effect and try to bind at port 443.

```
go get -u github.com/xenolf/lego
cd go/bin
./lego --path /etc/lego --domains domain.com -m my@email.com  --http 8080 --tls 8081 run
```

Gives me the error:
```
error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use
```

Am I doing something wrong or is it a bug?

Thanks!

**Comment by xenolf** [comment]
Hello!

You have to pass `interface:port` or `:port` to `--tls`.

**Comment by xi2** [comment]
I have accidentally made this same error myself. Should we make it so that if an argument `<arg>` to `--http` or `--tls` consists of digits only it is mapped to `:<arg>`. If you agree I can make a PR.

**Comment by xenolf** [comment]
I'd rather add an error output to the CLI if an argument without a colon is passed to `--tls` or `--http`. :)

**Comment by xi2** [comment]
Yes, adding a more helpful error message is a better idea than mine.
