### ISSUE TITLE
Like accounts, should certificates live under the server-directoy?

### ISSUE THREAD

**Issue by middelink** [xenolf/lego#145]
Rationale: when I use anything but the official https://acme-v01.api.letsencrypt.org/directory" they are different, self-signed certificates, not to be confused with the real ones. It will be good to not deploy them by mistake to production environments and now we have to examine the certificate itself to make the distinction.
  It will break the existing structure though, although only revoke/renew will be effected.

And in a similar, but less important question, can we link the account into the cert's metadata (acme/CertificateResource) somehow? It is not really important in the sense of the acme interface, since every account can request any certificate of the domains it has control over, but it would be nice to retain the data.

**Comment by xenolf** [comment]
The rationale behind the current structure was to always have the latest cert / key combination in the same place without having to worry about what service you got the certificate from. I can see where you are coming from though.

> And in a similar, but less important question, can we link the account into the cert's metadata (acme/CertificateResource) somehow?

What kind of link do you have in mind? Linking the local identifiable account to the cert (the email address maybe) or the URL to the ACME identifier?

**Comment by middelink** [comment]
To be honest, I have no preference. Just any way to link up an account to the user would be great. Both the email address and the uri (like "https://acme-staging.api.letsencrypt.org/acme/reg/131077", right?) would work fine for this purpose.

**Comment by xenolf** [comment]
> (like "https://acme-staging.api.letsencrypt.org/acme/reg/131077", right?) 

Yes, that's what I meant. I will add this in as I just encountered that problem myself with not knowing which account a certain certificate was from :sweat_smile:

**Comment by xenolf** [comment]
The link through meta data is now in.
