### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by pjebs** [xenolf/lego#146]
I ran `lego --email="foo@bar.com" --domains="example.com" run` (with my details instead).

It doesn't work. It simply pauses and shows some kind of command line screen where I can type arbitrary text. I can type stuff but that doesn't do anything plus your instructions doesn;t even mention this text entry screen.

**Comment by mholt** [comment]
Could you please post the text you see exactly? Or a screenshot.

**Comment by pjebs** [comment]
i think their server was down because I specified the server actual  explicitly and then it worked.
It produced a *.crt  and *.key file.
Do I need to convert it to pem format to use in Golang's built in webserver:

`err := http.ListenAndServeTLS(":443", "cert.pem", "key.pem", nil)`

**Comment by xenolf** [comment]
No, the output is already in PEM format and includes the intermediate certificate.
