### ISSUE TITLE
Release date next release with cloudflare dns challenge

### ISSUE THREAD

**Issue by JorritSalverda** [xenolf/lego#147]
I can build and compile the current master branch and it works perfect for using cloudflare for the dns-01 challenge. However this code isn't part of version 0.2.0 yet. When is the next release due? Is it awaiting certain fixes? A milestone might be useful to see what's still lined up for going in the new release. 

Btw, thanks for the awesome cli that doesn't require any dependencies like python as most other letsencrypt clients do.

**Comment by xenolf** [comment]
The next release will get pushed after #144 is in. If the open PRs which introduce new providers for DNS get rebased on the new format introduced in #144 then I'd like to get them in as well.

**Comment by JorritSalverda** [comment]
Cool, thanks.

**Comment by xenolf** [comment]
I added a milestone for the next release :)
