### ISSUE TITLE
DNS Challenge in the face of slow DNS update propagation

### ISSUE THREAD

**Issue by beevik** [xenolf/lego#149]
I'm in the process of adding a DNS challenge provider for namecheap, but I've been hitting the 30-second propagation timeout.  I don't know if it's just because namecheap happens to be particularly slow at propagating DNS changes, but the 30 second window does seem optimistic.  Has anyone given any thought to making the timeout configurable?

**Comment by mholt** [comment]
Uh, yes, in fact, see #148 :wink:

**Comment by beevik** [comment]
Oh sorry I missed that. Closing this.
