### ISSUE TITLE
Vendoring third-party packages?

### ISSUE THREAD

**Issue by beevik** [xenolf/lego#165]
I've noticed that lego depends on quite a large number of third-party packages now.  Here's the full list:

```
github.com/codegangsta/cli
github.com/davecgh/go-spew/spew
github.com/golang/protobuf/proto
github.com/miekg/dns
github.com/mitchellh/goamz/aws
github.com/mitchellh/goamz/route53
github.com/mitchellh/goamz/testutil
github.com/motain/gocheck
github.com/pmezard/go-difflib/difflib
github.com/square/go-jose
github.com/square/go-jose/cipher
github.com/square/go-jose/json
github.com/stretchr/testify/assert
github.com/vaughan0/go-ini
github.com/weppos/dnsimple-go/dnsimple
golang.org/x/crypto/ocsp
golang.org/x/net/context
golang.org/x/net/context/ctxhttp
golang.org/x/net/publicsuffix
golang.org/x/oauth2
golang.org/x/oauth2/google
golang.org/x/oauth2/internal
golang.org/x/oauth2/jws
golang.org/x/oauth2/jwt
google.golang.org/api/dns/v1
google.golang.org/api/gensupport
google.golang.org/api/googleapi
google.golang.org/api/googleapi/internal/uritemplates
google.golang.org/appengine
google.golang.org/appengine/internal
google.golang.org/appengine/internal/app_identity
google.golang.org/appengine/internal/base
google.golang.org/appengine/internal/datastore
google.golang.org/appengine/internal/log
google.golang.org/appengine/internal/modules
google.golang.org/appengine/internal/remote_api
google.golang.org/cloud/compute/metadata
google.golang.org/cloud/internal
```

Has there been any thought given to using godep? Keeping lego in sync with the latest versions of all its dependencies is going to become increasingly fraught.

**Comment by xenolf** [comment]
Yes, I do plan on using vendoring if its viable.

The ACME package itself only has the following external dependencies:

```
github.com/miekg/dns
github.com/square/go-jose
github.com/square/go-jose/cipher
golang.org/x/crypto/ocsp
golang.org/x/net/publicsuffix
```

My view on the ACME package being downloadable via `go get` and thus being standalone is quite strong and this goal needs to be met with whatever vendoring we might use.

I did not spend a large amount of time on looking into vendoring but it would need to accomplish the independent vendoring of the different parts of this project (CLI, ACME and the providers).

**Comment by beevik** [comment]
I think if you wanted separate vendoring for acme and providers, you might want to consider using git submodules.  Then you could run godep on each submodule.

**Comment by mholt** [comment]
The go tool supports the "vendor" folder -- would that help/work?

**Comment by beevik** [comment]
I'm not positive, but I think the use of the "vendor" folder is only supported by go version 1.6 (and 1.5 if you use a special environment flag).

**Comment by xenolf** [comment]
> I'm not positive, but I think the use of the "vendor" folder is only supported by go version 1.6 (and 1.5 if you use a special environment flag).

That's the case. I will take some time the coming week to have a look at the current vendoring options and then decide upon a direction to take. I'll of course post that in here and let other people chime in with their opinions :)

**Comment by doherty** [comment]
FWIW, I found it very easy to use [`gb`](https://getgb.io/) to vendor dependencies for this repo by creating an empty repo, adding this repo as a submodule in `src/github.com/xenolf/lego` and running `gb vendor ...` See https://github.com/doherty/lego-vendored

**Comment by mrueg** [comment]
Would be great to see the vendoring reintegrated into this repository! :+1:

**Comment by JamesClonk** [comment]
Agree, some form of vendoring would be nice. 👍 

I accidentally broke the build yesterday by renaming the DNS functions in the Vultr library.
Had to send a PR to fix it: https://github.com/xenolf/lego/pull/335  😅

**Comment by carlwgeorge** [comment]
I'm exploring packaging lego for Fedora and CentOS.  Getting the dependencies vendored into the project would make that significantly easier.

**Comment by carlwgeorge** [comment]
I have built lego RPMs in a [COPR](https://copr.fedorainfracloud.org/coprs/carlwgeorge/lego/).  Instead of using [the tarball from this repo](https://github.com/xenolf/lego/archive/v0.4.1.tar.gz) directly, I [forked it](https://github.com/carlwgeorge/lego) to [vendor the dependencies](https://github.com/carlwgeorge/lego/commit/d6d4cdcb1fb11a1cefcc004aa2dc7aed14473d7d) with [dep](https://github.com/golang/dep).  This causes the tarball to increase from 92 KiB to 3568 KiB (3.5 MiB).  I rolled back to the v0.4.1 tag for my commit, but if this approach looks sane I would be happy to repeat it against master and do a proper pull request.
