### ISSUE TITLE
Improvement: setting dns-01 challenge record for multiple domains in parallel

### ISSUE THREAD

**Issue by JorritSalverda** [xenolf/lego#173]
When running lego for multiple domains it will set the dns TXT record and check propagation in sequence. This can take a long time if the number of domains is large. Would it be possible to parallelize this?

**Comment by xenolf** [comment]
Well it sure is possible. @mholt and me already had a talk about this and we came to agree that it would be a great feature. The ACME challenges are good to run concurrent as the context for each of them should be seperate. What we need to do though is look all over to be sure that no state is shared.

So yes, this is something I'd like to add in the future :)

**Comment by lenovouser** [comment]
Yeah, this would be very helpful if you have a lot of domains.

**Comment by mthoretton** [comment]
Just another comment to add you some additional pressure about developing this great functionality ;) Btw lego works fine with route53! Thanks

**Comment by xenolf** [comment]
I've started to work on this (for all challenges) locally and will push once I have something to show ;)

**Comment by xi2** [comment]
Thank you for working on this. I will be happy to test and/or update the gandi provider as required. :)

**Comment by aaronb-cg** [comment]
I would like to see this also.
Lego is working great for us, just takes a long time with the large number of domains we're processing.

**Comment by lenovouser** [comment]
Any progress?

**Comment by jasonwbarnett** [comment]
Would love to collaborate to get this done. I looked over the code tonight and identified where the modification should go, but haven't had time to brainstorm the best design, e.g. worker pool, go routines, etc...

**Comment by jasonwbarnett** [comment]
I leveraged #237 as a starting point and was able to make things more efficient. I was able to obtain a SSL certificate with 86 SANs in 6 minutes and 24 seconds.

I was using the following:

Challenge Type: DNS-01
DNS Provider: Google DNS
TXT Record TTL: 10 seconds
zone negative cache TTL: 10 seconds

Thi

**Comment by xenolf** [comment]
Hey @jasonwbarnett and thanks for your time!
I had a quick look at your implementation. Please keep in mind that many of the DNS providers currently shipped with lego do have state per instance of the provider (for caching the domain name for example). Your implementation only calls the `solve()` function in parallel which will overwrite this state.

**Comment by jasonwbarnett** [comment]
@xenolf Where did you get with your implementation? Do you have it published anywhere?

Wondering if it makes sense to implement the concurrency in the provider itself or what... Or if it's just a matter of refactoring the providers which currently have a shared state.

**Comment by xenolf** [comment]
@jasonwbarnett My approach was to create one instance of the provider for each call to `solve()`. The code isn't published anywhere but I can push it into a branch once I get home.

**Comment by jasonwbarnett** [comment]
@xenolf Please post what you have to a branch so I can see.

**Comment by lenovouser** [comment]
Any progress?

**Comment by jasonwbarnett** [comment]
I did it for google on my fork here and it works perfectly, https://github.com/jasonwbarnett/lego/tree/feature/concurrent-solvers

**Comment by lenovouser** [comment]
@jasonwbarnett can you create a pull request? Or did you already?

**Comment by aslafy-z** [comment]
up?

**Comment by jasonwbarnett** [comment]
I'm up :)

@aslafy-z what are you asking?

**Comment by aslafy-z** [comment]
Will you PR this awesome feature ?

**Comment by jasonwbarnett** [comment]
Since I last worked on this I am 105 commits behind master and last I looked (6 months ago) the changes were fairly drastic and this would take a bit of work to integrate into the latest.

I will have some time later this week at which point I'll spend some time looking into rebasing off of master and getting this thing working. I doubt it will get merged in by @xenolf though...

**Comment by xenolf** [comment]
@jasonwbarnett What makes you think that?

**Comment by jasonwbarnett** [comment]
:innocent: I stand corrected

**Comment by ldez** [comment]
Fixed by #607
