### ISSUE TITLE
Show server error messages

### ISSUE THREAD

**Issue by rgl** [xenolf/lego#18]
It seems the server can return typed error responses alike:

```
HTTP/1.1 403 Forbidden
Server: nginx
Content-Type: application/problem+json
Content-Length: 90
Replay-Nonce: BImpOtZwyWj0msQvumDms8FPPheeyA-dpljvm86upH4
Expires: Wed, 28 Oct 2015 14:21:10 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 28 Oct 2015 14:21:10 GMT
Connection: close

{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Syntax error"}
```

It would be great if the client could return those error messages to stdout instead of just outputting `The server did not provide enough information to proceed.`. That particular error was returned because I tried to use `--domains localhost`.

**Comment by mholt** [comment]
Yeah, this is something I noticed yesterday too. Will be working on that this week for sure.
