### ISSUE TITLE
Support for azure dns

### ISSUE THREAD

**Issue by Flowman** [xenolf/lego#180]
Can we add support for azure dns?

https://azure.microsoft.com/en-us/services/dns/

**Comment by LukeHandle** [comment]
I'm currently working on Rackspace DNS but could take a look at this after. If I do start, I'll update here.

**Comment by Flowman** [comment]
How is it going with this implementation, anything I can do to help?

**Comment by Flowman** [comment]
Can we use the [Azure SDK for GO](https://github.com/Azure/azure-sdk-for-go/tree/master/arm/dns) to get this thing rolling?

**Comment by buckett** [comment]
@Flowman I've an initial implementation of this using the Azure SDK for GO.
