### ISSUE TITLE
Windows/IIS support

### ISSUE THREAD

**Issue by oliverjanik** [xenolf/lego#184]
I absolutely love this client. Thanks for the work.

What would it take to be able to run this on Windows and produce certs for IIS?

1) Go is cross platform, there shouldn't be many issues with that
2) IIS uses .pfx format for certs
3) The certs need to be imported into IIS, can't be just file based (I think)
4) During renewal the cert needs to be replaced in IIS registry

Some of these things may be handles by [certutil](https://technet.microsoft.com/en-us/library/cc732443.aspx).

**Comment by xenolf** [comment]
Greetings! And thanks for using our tool :)

Unfortunately this won't be possible without using a tool like openssl to convert the PEM file(s) into the PKCS12 format. Go has afaik no built in way of converting and certutil can't work with the PEM format.

You can of course write a powershell script which does all of this for you. Certutil does allow you to import PKCS12 certs directly from the command line with `certutil -p <PFXPassword> -importPFX <FileLocation.pfx>` so a complete automation is possible.

**Comment by xenolf** [comment]
I'm going to close this. If you have any additional questions, please feel free to reopen the issue or create a new one.
