### ISSUE TITLE
Could not obtain certificates 	acme: Error 400 -  - 

### ISSUE THREAD

**Issue by gaillard** [xenolf/lego#188]
Is there a way to get more information than this?

I can use the http challenge fine on my own network, but I am now trying to get it to work with amazon and am only getting the above :(

**Comment by gaillard** [comment]
So i dumped out the error in the handleHTTPError() function, and it looks like this is the blacklisted ephemeral aws instance domains it doesn't like with a: policy forbids issuing for name.

but the real issue here was that error function, no need to decode into json, just dump the body to any error variable so at least callers get it back!

**Comment by xenolf** [comment]
Actually all errors coming from the ACME server should have the content type `application/json` and thus should get parsed into an error struct and later printed using [this](https://github.com/xenolf/lego/blob/master/acme/error.go#L22) to print all info we get.

I'll double check that though to be sure.

**Comment by rekby** [comment]
I have same errors in my usage. It happen from time to time in long series of requests.
I solve the problem by repeat requests. Usually repeat request help.

**Comment by gaillard** [comment]
At least the staging LetsEncrypt is not returning with the content type. But still, all that is being done with the body contents is putting it into an error variable, it is nice if the message is formatted well but in the case where it can't be decoded it should not be lost, that is much worse. So in that case lets just shove it into the error.

**Comment by xenolf** [comment]
Errors are now added verbatim to the details string when they are not parsed as JSON.

**Comment by gaillard** [comment]
awesome, thanks!
