### ISSUE TITLE
Pending authorizations

### ISSUE THREAD

**Issue by rekby** [xenolf/lego#189]
I have send request for few thouthand domains. After 2000 certificates i start received response
Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.

I use acme.HTTP01 authentication for domains with webroot provider.
Before each request of certificate I check webroot someself:
generate random token and key, put it to webfolder by the provider and try to get it by general http.Get request, then remove my token.
I send certificate request only if my request is ok.

before 429 I have many errors:
Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce pm_ZKGxzW...

I used patched jws.go - from pr #185 
I think it may be depends from jws nonce bug.

**Comment by xenolf** [comment]
I'm not sure I'm understanding what you are trying to say :worried:

**Comment by rekby** [comment]
Sometime authorization failed for good domains. It is problem for large sets of domains: I reached limit 

> Pending Authorizations/Account limits how many times an ACME client can request a domain name be authorized without actually fulfilling on the request itself. This is most commonly encountered when developing ACME clients, and this limit is set to 300 per account per week.

https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769

**Comment by xenolf** [comment]
Is this still happening after #185 was merged?

**Comment by rekby** [comment]
Yes.

**Comment by rekby** [comment]
I think the problem can be in time of remove authorized token (call webroot provider CleanUp).

I try to switch to other libraries and get same problem until wait for remove token _after_ receive certificate (not right after authorization).

In log I saw about letsencrypt can check token few times.

In your library token removed right after succefully authorization:
http_challenge.go, func (s *httpChallenge) Solve(chlng challenge, domain string).

For example logs from one of website:
```
66.133.109.36 - - [14/Apr/2016:09:09:17 +0300] "GET /.well-known/acme-challenge/l5qidJBvNNW10BvHbJfM9aFYknzTHWf3sw1pACMuRSU HTTP/1.1" 301 - "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
66.133.109.36 - - [14/Apr/2016:09:09:19 +0300] "GET /.well-known/acme-challenge/l5qidJBvNNW10BvHbJfM9aFYknzTHWf3sw1pACMuRSU HTTP/1.1" 404 7607 "http://.../.well-known/acme-challenge/l5qidJBvNNW10BvHbJfM9aFYknzTHWf3sw1pACMuRSU" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

The first time token was present and authorize was succesfully.  Second time token was removed (may be when request certificate) and letsencrypt receive 404 error.

I think it happen for domains with redirection from www.domain.com -> domain.com or vise versa:
first domain.com checked ok,  but when try to check second variant - www.domain.com request redirected to domain domain.com and letsencrypt check old token - for domain.com, which already removed.

**Comment by xenolf** [comment]
> I think it happen for domains with redirection from www.domain.com -> domain.com or vise versa:
first domain.com checked ok, but when try to check second variant - www.domain.com request redirected to domain domain.com and letsencrypt check old token - for domain.com, which already removed.

This case is handled by two different authorizations. You get one authorization + token for `domain.com` and another one for `www.domain.com` as both are different entities. Per the ACME spec the token should be removed after successful authorization as any other domain will have their own auth token.

In your example logs, why is the let's encrypt server receiving a 301 on the first request - it should receive a 200 OK.

**Comment by rekby** [comment]
Yes, I understand about two different tokens for different domains.

Server get 301 becouse customers website have redirect from unconditional www.domain.com to domain.com in his .htaccess. I can't change customers website or rewrite rules.

I solve problem for me by switch to other library, which give more control (but it's more difficult in use) and change live of tokens for all certificate request process.

In your library you can create tokens for all domains, then obtain certificate then remove all tokens for all domains. It will handle the case.

Your library is perfect and simple for usage. Thanks for work :)

**Comment by xenolf** [comment]
Thanks :) but I'm still not sure about the issue at hand.
Given we want to validate the domains `www.example.com` and `example.com` where the `www` subdomain redirects to the main domain.

Boulder will try to access `http://www.example.com/.well-known/acme-challenge/123456789www` and is greeted with a 301 redirect to `http://example.com`. Now boulder follows this redirect and tries to access the SAME token again at `http://example.com/.well-known/acme-challenge/123456789www`. At this point we have not removed the token as the challenge did not complete yet. After boulder got the token and validated it, we get a new status from boulder that the authorization is complete and we remove the token.

Next boulder tries to access `http://example.com/.well-known/acme-challenge/123456789example` - notice the different token. Here boulder gets a 200 response again and we delete the token as the challenge is complete.

This is how it's supposed to work. Could you provide the steps which differ from the above?

**Comment by rekby** [comment]
Hmm... yes, you are right...
Ok, I have no any more idea.

May you remove token before letsencrypt check it - similar to race condition? For example:
lego put token
lego request letsencrypt
lego remove token
lensencrypt request token
?

If not - i have no any more ideas about 404 errors of token (while self check work fine).

About subject problem: it can be from 400 bad requests errors too. After 2-3 hours continuesly cert requests server response 400 bad request for every second request (about 50%). Without retry (if skip bad domain) it fast reach pending authorization limit.

**Comment by xenolf** [comment]
> May you remove token before letsencrypt check it

We specifically check with the ACME server through polling to make sure the challenge status is no longer "pending" (executing) but either "invalid" or "valid". Only when the status is one of these two we remove the token.

> After 2-3 hours continuesly cert requests server response 400 bad request for every second request

It is taking you 2-3 hours to request certificates for all domains?

**Comment by xenolf** [comment]
I will close this for now.
Feel free to re-open the issue if you feel like there is anything else to add.
