### ISSUE TITLE
Route 53 provider gets confused by private zones

### ISSUE THREAD

**Issue by danni** [xenolf/lego#192]
I have two hosted zones in Route 53 for the same domain, one is public and one is private. lego is trying to set the Route53 verification on the wrong zone so it fails to verify.

**Comment by LukeHandle** [comment]
Hmm, so when we do the explicit lookup, we are getting 2 returned, but the private appears first? I wonder if we can pass a filter to Amazon to only return public, or if we just need to check how many are returned and if they are public.

**Comment by danni** [comment]
From what I can determine from the API, there's no filter. You have to post
filter on `.Config.PrivateZone`

On Apr 16 2016, at 9:10 pm, LukeH &lt;notifications@github.com&gt; wrote:  

> Hmm, so when we do the explicit lookup, we are getting 2 returned, but the
private appears first? I wonder if we can pass a filter to Amazon to only
return public, or if we just need to check how many are returned and if they
are public.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/xenolf/
lego/issues/192#issuecomment-210792319)![](https://github.com/notifications/be
acon/AAH5wNciy87jL84djpZRYJd4R_o5Rs2Iks5p4MOygaJpZM4II4pH.gif)

**Comment by janeczku** [comment]
Route 53 is tricky in that regard as it also allows multiple public zones with the same name. In that case we currently may end up provisioning the authorization record to a zone that is not "active" (as in the domain registrar's name server doesn't point to it).

How about letting users pass the Hosted Zone ID when requesting a certificate using Route 53?

**Comment by LukeHandle** [comment]
Ahh, allowing ID is a sure fire way for success. Interesting point that there could be multiple identically named zones. How much extra work if we wanted to establish the correct zone though. (also, heads up, not currently working on this)
