### ISSUE TITLE
Add to dockerhub registry

### ISSUE THREAD

**Issue by JoyceBabu** [xenolf/lego#194]
Please create an automated build repository at Dockerhub as it will be much easier to install and use.

Thanks

**Comment by JoyceBabu** [comment]
The following `Dockerfile` will create a container which is ~ 20MB in size

```
FROM alpine:3.3

ENV GOPATH /go

RUN apk update && apk add ca-certificates go git && \
    rm -rf /var/cache/apk/* && \
    go get -u github.com/xenolf/lego && \
    cd /go/src/github.com/xenolf/lego && \
	go build -o /usr/bin/lego . && \
	apk del ca-certificates go git && \
	rm -rf /var/cache/apk/* && \
	rm -rf /go

ENTRYPOINT [ "/usr/bin/lego" ]

```

**Comment by strothj** [comment]
There is an official Go docker container based on Alpine which can be used as a base instead of installing the go package using apk.

**Comment by JoyceBabu** [comment]
The above `Dockerfile` is a modification of the official one.

It took me over 10 minutes to build the binary, and it required downloading packages several megabytes in size. If the package is available in DockerHub, it will be only 20MB in size and it would be much more easier for a user to get started.

IMHO since adding the automated build is a one time job its benefits far outweighs the effort spend doing it.

**Comment by xenolf** [comment]
We do have a dockerfile in the repo already. From what I can tell it's nearly exactly the same one you posted?
Is the automation possible through our travis builds?

**Comment by JoyceBabu** [comment]
I have modified the official Dockerfile and made two changes

- Each `RUN` instruction creates an additional layer in the docker image. Adding files in one `RUN` instruction and deleting it in another `RUN` instruction will not reduce the size of the image. I used a single `RUN` command so that all the package/file removal happens in the same command in which the package installation happens, so that no additional layers are created.
- Similar to `RUN` statement, `ADD` instruction also creates an additional layer. Using git clone in the `RUN` statement and deleting it within the same statement ensures that an additional layer with source files is not added.

A quick google search tells me that it should be possible to automate using travis builds, but I am not sure because I have never used travis.

DockerHub allows you to create an automated build repository. When you try to create an automated build, it will ask you to link your GitHub account (if not already done so). After that it will show a list of your repositories, and you just have to select the GitHub repo (xenolf/lego) and a branch (master). Whenever you push a commit to that branch, DockerHub will automatically trigger a build.

**Comment by xenolf** [comment]
I created an automatic build at https://hub.docker.com/r/xenolf/lego/
So this should get updated when we next push to master.

**Comment by JoyceBabu** [comment]
Thank you.

I can see that there is no current build. Can you please manually trigger a build or accept my pull request to auto trigger a build?

**Comment by xenolf** [comment]
Should have built now :)
Please close this issue if you feel like it is solved.

**Comment by JoyceBabu** [comment]
Thank you 😀
```
REPOSITORY       TAG         IMAGE ID            CREATED             SIZE
xenolf/lego      latest      9d4b8d2c67e3        4 minutes ago       19.92 MB
```
