### ISSUE TITLE
What's the relationship to github.com/google/goacme?

### ISSUE THREAD

**Issue by shurcooL** [xenolf/lego#195]
Hi, I just wanted to ask this question to learn.

What's the relationship of the ACME library in this repository to the one in https://github.com/google/goacme? I've learned about recently from https://github.com/golang/crypto/commit/1777f3ba8c1fed80fcaec3317e3aaa4f627764d2.

Thanks!

**Comment by xenolf** [comment]
Not related at all.

**Comment by shurcooL** [comment]
Do the two libraries do different things?

**Comment by xenolf** [comment]
Not that I'm aware of. Google chose to reimplement the ACME spec themselves.
The only difference that I am aware of is that goacme does only implement HTTP01.

**Comment by shurcooL** [comment]
I see, thanks.

I'll close this since my question was answered.

But I do wonder, for someone looking for an ACME library, how they should choose between these two seemingly similar libraries...

**Comment by xenolf** [comment]
We did [offer][1] [to][2] join efforts, but were never approached from anyone. It is very unfortunate that things turned out this way.

[1]: https://twitter.com/mholt6/status/667507533905420288
[2]: https://twitter.com/mholt6/status/656343614109278208
