### ISSUE TITLE
Account creation with EC384 key fails

### ISSUE THREAD

**Issue by jfindley** [xenolf/lego#197]
If I try to use an EC384 (P384) account key, registration fails, with the following error:
```
Failed to post JWS message. -> square/go-jose: unknown/unsupported algorithm
```

I'm generating the account key like so:
```go
priv, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
if err != nil {
	return
}
a.PrivateKey, err = x509.MarshalECPrivateKey(priv)
```

**Comment by xenolf** [comment]
The key returned from `GetPrivateKey()` should be a `crypto.PrivateKey`. In your case you should directly return the key in `priv` and not marshal it.

**Comment by jfindley** [comment]
Ah! that fixed it thanks.  Sorry for the noise.
