### ISSUE TITLE
Dyn Provider returns 404 for * subdomains

### ISSUE THREAD

**Issue by CalebTodd** [xenolf/lego#199]
I use a two A records for my domain. One is the standard TLD and another is a ' * ' to catch any subdomain. I then handle the subdomain inside of nginx. 

When trying to generate a certificate for www -- or any other subdomain -- which does not have an explicit record, I receive a 404 HTTP status code. 

I'm hoping the code can be written so that it validates either the named subdomain OR a ' * ' record to accommodate my situation.

**Comment by aebruno** [comment]
@CalebTodd I'm not sure I understand your use case. Can you provide some more details? I don't believe the ACME protocol supports wildcard certs (at least last time I checked).

**Comment by CalebTodd** [comment]
My application handles the content displayed for different subdomains. These correlate with users of the application. A power user can generate new users at-will within the application -- e.g. new subdomains. So, rather than create DNS entries for every possible subdomain, I create a standard A record and a secondary record (A-record but a CNAME would probably work too) which redirects all subdomains to the same host. When you lookup a random subdomain, that wilcard character ensures that it routes to the correct place.

That said, when I pass www.foo.com in as a domain -- and an explicit record for WWW doesn't exist -- it fails to validate using DNS validation. 

So, the wildcard part really just applies to the DNS validation component; perhaps just from the token request from Dyn. From the certificate side of things, I'm still explicitly defining the domains to include in the SAN certificate. 

This is how I see the logic: Attempt subdomain check. If subdomain record does not exist, check for * record (assuming this is possible). If that exists, proceed with validation.

**Comment by LukeHandle** [comment]
Hey there @CalebTodd, can you confirm what your "zone" would be?

[Here](https://github.com/xenolf/lego/blob/master/providers/dns/dyn/dyn.go#L189) we are assuming that the "zone" is actually the domain passed to the `Present()` function (probably a bit optimistic?). We may benefit from getting the "auth zone" with `FindZoneByFqdn()` if that matches what you would expect here?

We do this elsewhere for getting the correct zone to lookup, see [CloudFlare](https://github.com/xenolf/lego/blob/master/providers/dns/cloudflare/cloudflare.go#L107) and [Route53](https://github.com/xenolf/lego/blob/master/providers/dns/route53/route53.go#L127).

Dyn API docs for those interested (they were surprisingly unintuitive to find):
https://help.dyn.com/create-txt-record-api/

**Comment by CalebTodd** [comment]
The Zone for my case would be the second-level domain (SLD) -- foo.com -- and the node would be the third-level domain -- www. I think in call cases with Dyn, the zone is the SLD. So, if we can parse out the SLD for "zone", we should be good to pass in the full domain name as FQDN.

**Comment by LukeHandle** [comment]
What I don't quite understand is how this is working at the moment? Have you tested after adding a record for www.foo.com and attempting to get a cert for it? From my understanding of their API, it still shouldn't work as we are using a sub-domain as the zone name?

We should be establishing the correct zone to request for and then passing it the FQDN of the record to add. In almost every other provider we do that first.

I'm doubting myself though as anyone using this provider would have come across this issue assuming they attempted to request a cert for a sub-domain of their main zone. I'll have a look with fresh eyes tomorrow.

**Comment by CalebTodd** [comment]
You may be correct that it doesn't add correctly. I just added a WWW node (cname and A) and still get the 404.

**Comment by aebruno** [comment]
Looks like this is a bug. I can confirm this is broken for me as well. I had incorrectly assumed, as @LukeHandle  mentioned the domain passed to the `Present()` function is the "zone". I had previously only tested using a tld. It appears the Dyn API doesn't like this REST call:

    PUT /TXTRecord/example.com/_acme-challenge.www.example.com./

However, works perfectly fine with:

    PUT /TXTRecord/example.com/_acme-challenge.example.com./

I'll try and investigate this further and dig through their api docs.

**Comment by aebruno** [comment]
@LukeHandle thanks for the pointer to `FindZoneByFqdn()`. I submitted a pull request which fixes the Present and Cleanup functions to use the correct zone. Tested this using both a tld (example.com) as well as (www.example.com) and it seems to be working for me. @CalebTodd I'm not sure this completely fixes your original issue but the Dyn provider should work correctly now for subdomains.

**Comment by xenolf** [comment]
@CalebTodd feel free to reopen this if the PR does not fix your problem :)
