### ISSUE TITLE
How do I renew SAN certificates?

### ISSUE THREAD

**Issue by codefx9** [xenolf/lego#202]
Hi,
I see that during renew operation I can only provide a single domain name. How do I renew a SAN certificate?

Thanks.

**Comment by xenolf** [comment]
I guess you are talking about the CLI task `Renew`? The domain needed here is the domain in the `CommonName` property of the certificate. Lego will use this to find the right certificate on disk and load it. Then it uses the `DNSNames` property to enumerate all domains and renews each of them.

This happens through the `CertificateResource` that get's passed to the `RenewCertificate` function. The certificate inside of the Resource has all information needed to renew a SAN certificate.

**Comment by codefx9** [comment]
I am guessing it is using the CertURL to get all the information it needs. Am I right? Thanks.

**Comment by xenolf** [comment]
No it does not need to call an API for that. All information needed for renewal is readily available in the cert itself and it's metadata file.

**Comment by codefx9** [comment]
Thanks.
