### ISSUE TITLE
Lego still tries to use disabled solvers

### ISSUE THREAD

**Issue by lenovouser** [xenolf/lego#203]
I am not sure whether `lego` really tries to use them but I want to note that it still displays this in the output:

```
2016/04/26 12:46:08 [INFO][sub0.domain.tld] acme: Could not find solver for: tls-sni-01
2016/04/26 12:46:08 [INFO][sub0.domain.tld] acme: Could not find solver for: http-01
2016/04/26 12:46:08 [INFO][sub0.domain.tld] acme: Trying to solve DNS-01
2016/04/26 12:46:09 [INFO][sub0.domain.tld] Checking DNS record propagation...
2016/04/26 12:46:21 [INFO][sub0.domain.tld] The server validated our request
```

even when I have them disabled with the `exclude` flag like this:

```
lego \
     --d="sub0.domain.tld" \
     --d="sub1.domain.tld" \
     --d="sub2.domain.tld" \
     --d="sub3.domain.tld" \
     --email="administrator@domain.tld" \
     --accept-tos \
     --key-type="rsa4096" \
     --server="https://acme-staging.api.letsencrypt.org/directory" \
     --path="/domain/data/lego/" \
     --exclude="http-01" \
     --exclude="tls-sni-01" \
     --dns="cloudflare" \
     run;
```

So to me it seems like it does try to use `http-01` and `tls-sni-01`. I think that this and the fact that `lego` sets the [dns challenge record](https://github.com/xenolf/lego/issues/173) every time new for every subdomain is the reason for `lego` taking a really long time for receiving the SAN certificate if you have a lot of subdomains.

**Comment by xenolf** [comment]
No, lego is not actively trying to solve a challenge you excluded via the `--exclude` flag.
The output you are seeing is simply stating the fact that lego received a challenge from the server it is not able to solve as you excluded the solver from the list. 
We are receiving a list of challenges from the server and are iterating it. Whenever lego encounters a challenge type and has no matching solver configured, it outputs this message. Performance wise the message is only a map lookup and a `printf` statement.

**Comment by lenovouser** [comment]
@xenolf alright, yeah - as I said I wasn't sure. Thanks for the clarification!
