### ISSUE TITLE
Install fails with go 1.4.1

### ISSUE THREAD

**Issue by buckett** [xenolf/lego#205]
I attempted to install on an old version of go and got:
```
$ go version
go version go1.4.1 darwin/amd64
$ go get -u github.com/xenolf/lego
# golang.org/x/net/context/ctxhttp
Documents/go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)
```
Upgrading to 1.6.2 resulted in a good install. Reporting so that if nothing else someone searching for this error sees that a simple upgrade should fix it.

**Comment by xenolf** [comment]
Thank you for reporting :)
I've decided to only support the last two releases of go because it is kinda dictated from google libraries like you just experienced. For anyone hitting this issue, please look at the versions in our CI, these are the ones we currently support.
