### ISSUE TITLE
With `lego ... run` DEPRECATED Action signature.

### ISSUE THREAD

**Issue by buckett** [xenolf/lego#206]
I was attempting to use the `lego ... --dns run` command and after what looked like success:

    2016/05/12 17:56:04 [INFO][my.domain] Server responded with a certificate.
    DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

Which I'm guessing is because I got a newer version of the cli library?

**Comment by xenolf** [comment]
Thanks for reporting this.
This is indeed caused by the CLI library version. I will fix this in master.

**Comment by buckett** [comment]
Thanks for the quick fix and I can confirm that with an update of lego this morning (`go get -u github.com/xenolf/lego`) it all works fine.
