### ISSUE TITLE
http timeout

### ISSUE THREAD

**Issue by mizutechvoip** [xenolf/lego#207]
Running this command:

> lego.exe --accept-tos="true" --http="201.33.209.185:80" --tls="201.33.209.185:443" --email="info@mizu-voip.com" --domains="rtc.tellfree.com.br" run

I get this response:

> 2016/05/12 16:12:41 Could not create client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

This is happening only on our Brazil server (Windows Server 2008 R2, lego.exe enabled on firewall, both 80 and 443 ports available for it).
The same is working fine on our UK server.
If I open the "https://acme-v01.api.letsencrypt.org/directory" URL from Firefox on the same Brazil server, i get the answer in around 10 seconds. So from Brazil the 10 second timeout usually is not enough.

Proposed solution:
Increase the http timeout in the http.go file by replacing:
this line: var defaultClient = http.Client{Timeout: 10 * time.Second} 
with this: var defaultClient = http.Client{Timeout: 20 * time.Second} 

If you wish you might also add a command line option to specify the http timeout.

**Comment by xenolf** [comment]
I guess making the timeout configurable via a CLI option would be the most sensible option here. I'm sure that if we raise the default timeout, somebody else will still hit it 😄

**Comment by mholt** [comment]
Hmmm yeah I feel like the permanent solution to this is to fix your network connection (you or them, depending where the problem is)

**Comment by mizutechvoip** [comment]
This is a server with 100 mbits internet connection used for VoIP with hundred of simultaneous calls. I don't think that the problem is with the internet connection. If you don't wish to increase the timeout so much, then my proposal:
-increase only a little bit the default (make it 14 seconds and it will be fine for the whole South America by default)
-and make it configurable via a CLI option

**Comment by xenolf** [comment]
You are now able to supply a `--http-timeout` flag to set the timeout in seconds.

**Comment by alfeg** [comment]
I've try to make `lego` works on my Asus-AC68U router. I've got exactly same message as in issue when run `lego`

> Could not create client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)


When I run `lego` from the same network from windows PC - it's works correctly. 

I've try to use latest release `v0.3.1` `lego_linux_arm` build and build my own build from master branch with exactly the same result. It's fails almost instantly - in 3-4 seconds. `--http-timeout` doesn't do anything.
