### ISSUE TITLE
support for rackspace dns

### ISSUE THREAD

**Issue by matejc** [xenolf/lego#208]
(when) will there be support for rackspace dns?

**Comment by LukeHandle** [comment]
If you're feeling daring, I wrote an initial start here: https://github.com/LukeHandle/lego/tree/patch-dns-rackspace?files=1

It should work, but I got distracted before writing proper testing. I'm halfway on a local branch with httptest on the auth and dns endpoints. A few niggles I needed to work out though.

**Comment by xenolf** [comment]
This landed.
