### ISSUE TITLE
Could not obtain certificates

### ISSUE THREAD

**Issue by lenovouser** [xenolf/lego#210]
I am getting this error

```
Could not obtain certificates
        Error presenting token: API error -> 6003: Invalid request headers
```

using this command:

```
lego \
     --d="domain.tld" \
     --d="1.domain.tld" \
     --d="...domain.tld" \
     --d="...domain.tld" \
     --d="...domain.tld" \
     --d="94.domain.tld" \
     --email="administrator@domain.tld" \
     --accept-tos \
     --key-type="rsa4096" \
     --path="/data/lego/" \
     --exclude="http-01" \
     --exclude="tls-sni-01" \
     --dns="cloudflare" \
     run;
```

**Comment by xenolf** [comment]
Thanks for reporting this issue. Did this only happen once or multiple times?

**Comment by lenovouser** [comment]
It happens every time I try to request new certificates. The `1...94` mean that there are 94 domains in total, didn't know if that was clear from the example. I could reproduce it twice, now I am getting this again:

```
2016/05/17 23:31:07 [domain.tld] Could not obtain certificates
        acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.
```

which I had a few weeks ago but [from a different cause](https://github.com/xenolf/lego/issues/167#issuecomment-202986192), but I didn't force-quit it this time. It just exited by itself. I might have to wait a few days / weeks until the currently pending authorizations get deleted before I can test anything for you.

System details:

```
web@web01.dev.domain.tld:[/data/lego]: go version
go version go1.5.1 linux/amd64
web@web01.dev.domain.tld:[/data/lego]: uname -a
Linux web01.dev.domain.tld 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```

I am installing lego like this: `go get -u github.com/xenolf/lego`

Anything more I could provide?

**Comment by xenolf** [comment]
I'll try to reproduce again with 1.5.1, was using 1.6.2 on the testing box I'm using.

**Comment by lenovouser** [comment]
@xenolf alright. I just remembered that I can use the staging server in case you want me to test something. So no need for waiting until the pending certificates get deleted.

**Comment by xenolf** [comment]
Turns out the error is coming from the cloudflare API. Could you try again with the change to the cloudflare provider I just pushed? It improves the error reporting in the provider as I'm guessing the error you are getting isn't the only one reported.

**Comment by lenovouser** [comment]
@xenolf I did with the staging environment:

```
2016/05/19 18:51:53 [sub.domain.tld] Could not obtain certificates
        Error presenting token: Cloudflare API Error
         Error: 6003: Invalid request headers<- 6102: Invalid format for X-Auth-Email header
```

Does that help?

**Comment by xenolf** [comment]
Any chance you have a space or other unfitting character in your `CLOUDFLARE_EMAIL` env variable?

**Comment by lenovouser** [comment]
@xenolf not any that I am aware of. Let me try to run `dos2unix` on the script.

**Comment by lenovouser** [comment]
@xenolf Yep, that did it. I don't know what exactly was wrong in the script now. I am sorry for creating this issue, I didn't look to me like that the

```
Could not obtain certificates
        Error presenting token: API error -> 6003: Invalid request headers
```

was an error on my side. Anyway, it seems like that there was a bad character in the bash script which I fixed by using `dos2unix <file>`, just for people who run into the same issue in the future.

**Comment by xenolf** [comment]
No problem, glad we got it resolved. :)
I hope the error output is a bit more telling now.

**Comment by lenovouser** [comment]
@xenolf Yep, `Invalid format for X-Auth-Email header` is definitely more telling - thanks!
