### ISSUE TITLE
Time limit exceeded

### ISSUE THREAD

**Issue by codefx9** [xenolf/lego#212]
I am trying to use DNS challenge with Google Cloud DNS servers from cli `run` command. I keep getting the following error (tried 3-4 times):

> Could not obtain certificates
> 	Time limit exceeded. Last error: NS ns-1318.awsdns-36.org. did not return the expected TXT record

I am using `.computer` TLD. I was able to successfully obtain SAN cert with same command for `.io` TLD.

**Comment by codefx9** [comment]
I increased the time out to 6 mins from 60 secs. Now, I am getting the following DNS errors even for `.io` TLD.

> Could not obtain certificates
> 	Time limit exceeded. Last error: NS ns-1318.awsdns-36.org. returned REFUSED for _acme-challenge.abc.xyz.org.

**Comment by xenolf** [comment]
Which timeout did you increase in particular?

**Comment by codefx9** [comment]
I increased the timeout inside DNS challenge file. https://github.com/xenolf/lego/blob/master/acme/dns_challenge.go#L79

**Comment by xenolf** [comment]
You said you are using google cloud DNS but we are asking the AWS DNS servers for your zone. Could you give me a bit more information about your DNS setup? It seems like we are resolving to the wrong authoritative DNS server for your domains.

**Comment by codefx9** [comment]
I purchased by domains on Namecheap and changed DNS servers to Google Cloud DNS. Everything in pretty much standard setup as far as DNS goes.

**Comment by xenolf** [comment]
Would you be able to share the domain name with me? You can send me a private message on gitter or something.

**Comment by xenolf** [comment]
I have not heard back from you in quite some time. Is this issue still relevant?

**Comment by xenolf** [comment]
Closing this as there haven't been any updates.
