### ISSUE TITLE
googlecloud dns provider errors because it already made the _acme-challenge domain

### ISSUE THREAD

**Issue by jmhodges** [xenolf/lego#218]
A previous run of lego that I Ctrl-C'ed is causing a later run to fail.

When run with the googlecloud dns provider, `googlecloud.DNSProvider.Present` fails because the `Changes.Create` call returns a googleapi.Error with status code 409:

```
googleapi: Error 409: The resource 'entity.change.additions[0]' named '_acme-challenge.animaltexts.com. (TXT)' already exists, alreadyExists
```

Not sure what the model of behavior for dns providers here is, but it seems like lego could clean this up for us.

**Comment by xenolf** [comment]
Hello and thanks for reporting this!

I agree that we could try to remove the entry if there is an existing one for the domain we are trying to validate. An issue to consider is that there could be another process (on the same or a different host) trying to validate the same domain at the same time.

**Comment by jmhodges** [comment]
Hm, well, now that I'm thinking about it, I'd be surprised if Google didn't allow multiple TXT records for that domain, so maybe there's a way to make that happen?

Maybe this error is because something else other than the domain and record type is non-unique. Maybe there's a TXT record for that domain with the same value? If that's the case, we could just allow 409 to mean "we got it up there".

**Comment by jmhodges** [comment]
(Let's Encrypt should check multiple TXT records with the same domain. I helped write that code but it's been a few months since I worked on the codebase.)

**Comment by xenolf** [comment]
You are right, it would seem odd to only allow one TXT record for a certain domain. I looked over the Cloud DNS docs but could not find a mention of any limits of this kind and I can't test it myself as I don't have a domain there.
Would it be possible for you to try it with the CLI tool google offers?

**Comment by jasonwbarnett** [comment]
I'm going to pick this up in the next couple of days and own it to completion. This seems like it's either easily doable or not. Either way, I'll figure it out.

**Comment by PSG-Luna** [comment]
Is this still being worked on ?

**Comment by buckett** [comment]
The Cloud DNS allows multiple TXT records for a domain.

The simple fix it to just check if there is an existing record when attempting to add our new record and if there is remove it.
