### ISSUE TITLE
Make resolver configurable

### ISSUE THREAD

**Issue by totallyunknown** [xenolf/lego#219]
In networks with limited network connectivity or restricted connectivity it's sometimes not possible to reach the Google DNS server. 

```
var RecursiveNameservers = []string{
	"google-public-dns-a.google.com:53",
	"google-public-dns-b.google.com:53",
}
```

I would be nice, to have a command line option to change the default resolver to other nameservers:

```
   --resolver value, -r value         Set the DNS resolver (default: google-public-dns-a.google.com, google-public-dns-b.google.com )
```

**Comment by xenolf** [comment]
Hello and thanks for the suggestion. I will look into implementing this when I get some time on my hands. The switch would probably end up being `--dns-resolver`.

**Comment by porjo** [comment]
I'm currently finding it frustrating to test new code when Lego insists on doing 'real' lookups. I'd like to send these queries to my local recursor so I can fake the response. Have this customizable would be great. I'm also not a fan of giving Google free data :wink:
