### ISSUE TITLE
Doesn't work if server can't bind to DNS IP

### ISSUE THREAD

**Issue by jimmidyson** [xenolf/lego#22]
I'm very possibly missing something, but I'm trying this running on a cloud server with a floating IP. I have set up DNS to resolve to this floating IP & then trying to do domain validation. This tries to bind to the   IP that the domain resolves to which ends up with

    Could not start HTTPS server for challenge -> listen tcp <IP>:5001: bind: cannot assign requested address

which is understandable because that IP is a floating IP, not bound to the host interfaces.

How about just listening on requested port rather than trying to use the requested domain IP?

**Comment by mholt** [comment]
Because binding to `host:port` is less invasive than binding to `:port`.

This change was deliberate because we had users reporting errors when another service was already bound to `:port`, so binding to `host:port` was the logical way to fix it.

**Comment by xenolf** [comment]
Hello and thanks for bringing this up! 

I think the right answer to this problem is to add a fallback option which binds to :443 / optPort if the bind to domain:port fails.

I will fix this ASAP.

**Comment by jimmidyson** [comment]
SGTM. Alternatively add another option for the bind IP/port?

**Comment by xenolf** [comment]
I just commited a fix to a new branch [add-shttp-bind-fallback](https://github.com/xenolf/lego/tree/add-shttp-bind-fallback).
@jimmidyson could you test this branch if it works for you?

**Comment by jimmidyson** [comment]
Tested - works for me... Thanks!

**Comment by xenolf** [comment]
Great!
In that case fixed by 959cf00 :)

**Comment by jimmidyson** [comment]
Now that is good service... thanks!
