### ISSUE TITLE
DNS provider for Google Cloud should accept credentials

### ISSUE THREAD

**Issue by kop** [xenolf/lego#226]
The current implementation of the Google Cloud DNS provider only works if a node, where lego is deployed, has node metadata available. However, that's not always possible. So it should also accept `CLIENT_ID` and `CLIENT_SECRET` pair for such cases.

**Comment by peterwald** [comment]
You don't necessarily need node metadata. It also works if gcloud is installed and authenticated.

**Comment by PSG-Luna** [comment]
You can also provide the GOOGLE_APPLICATION_CREDENTIALS env var and have it point to a json credentials file. That's probably what you want ?

**Comment by kop** [comment]
@PSG-Luna, yes this solves the problem.

**Comment by xenolf** [comment]
I'll go ahead and close this then. :)

**Comment by remy-actual** [comment]
Is this documented anywhere? 
I exported GOOGLE_APPLICATION_CREDENTIALS previously for my Cloud SQL Service Account limited to `roles/cloudsql.client` -- took me a day to figure out why my API calls where coming back 403 Forbidden
