### ISSUE TITLE
Could not create client:decode directory: json: cannot unmarshal number into Go value of type acme.directory 

### ISSUE THREAD

**Issue by tgulacsi** [xenolf/lego#23]
Could not create client:decode directory: json: cannot unmarshal number into Go value of type acme.directory 

Caddy errored out with this, but lego does the same:

gthomas@tequila:/home/gthomas$ sudo chpst -u www-data:ssl-cert /home/gthomas/bin/lego --path /var/www/.caddy/letsencrypt --server https://acme-v01.api.letsencrypt.org/directory --email tgulacsi78@gmail.com run
2015/11/10 18:04:13 No key found for account tgulacsi78@gmail.com. Generating a 2048 bit key.
2015/11/10 18:04:14 Saved key to /var/www/.caddy/letsencrypt/accounts/acme-v01.api.letsencrypt.org/tgulacsi78@gmail.com/keys/tgulacsi78@gmail.com.key
2015/11/10 18:04:15 Could not create client:decode directory: json: cannot unmarshal number into Go value of type acme.directory

Idea?

**Comment by xenolf** [comment]
You should not at /directory to the end of the CA url. Please use https://acme-v01.api.letsencrypt.org/

**Comment by tgulacsi** [comment]
Thanks!

The "/directory" came from copy-pasting the given URL from the email came from Let's Encrypt:

"""
To use Let's Encrypt's official client to obtain your real certificates, you will need to provide the production API URL on the command line:

  https://acme-v01.api.letsencrypt.org/directory
When running the Python client (installation directions [1]), be sure to specify the --server argument as shown below:

  git clone https://github.com/letsencrypt/letsencrypt
  cd letsencrypt
  ./letsencrypt-auto --server \
      https://acme-v01.api.letsencrypt.org/directory --help
How to use the client
"""

**Comment by mholt** [comment]
Okay, @xenolf, I figured out why they tell people to use the URL with /directory. The spec says:

>  In order to help clients configure themselves with the right URIs for
>   each ACME operation, ACME servers provide a directory object.  This
>   should be the root URL with which clients are configured.

I do find it odd that the directory isn't just at `/`, but perhaps lego should comply anyway.

**Comment by jimmidyson** [comment]
Perhaps only append `/directory` if it's not already present?

**Comment by xenolf** [comment]
The library now accepts urls with and without /directory as of b958bd2

**Comment by jimmidyson** [comment]
Nice!

**Comment by mholt** [comment]
That'll work. Just note that some CAs may not use /directory as per their choosing. But I don't suppose there will be any CAs other than Le'ts Encrypt for a while.
