### ISSUE TITLE
any plans for etcd as storage?

### ISSUE THREAD

**Issue by kalbasit** [xenolf/lego#236]
I have a use case where etcd storage would make more sense (one service deployed on a Kubernetes cluster), is there any plans for an etcd storage?

**Comment by mholt** [comment]
I can't speak for @xenolf but IMO that's a bit out of the scope of this project; the CLI is meant to be a simple tool to use the acme package. But I do know there are at least one or two importers of the acme package that will support etcd.

**Comment by kalbasit** [comment]
@mholt that's good enough, care to share links to those packages? Thanks.

**Comment by mholt** [comment]
This isn't terribly helpful, I know, but one is a future plugin for Caddy, another is proprietary.

**Comment by kalbasit** [comment]
@mholt oh I see, thanks anyway. I will write a new library with a binary as well using the acme library here.

**Comment by kalbasit** [comment]
I'm working on https://github.com/kalbasit/lego-etcd (it already works via CLI) and I am almost done creating the self-managed service (which does an etcd-backed locking to ensure only one process is creating or renewing the certificate). See kalbasit/lego-etcd#2. Still, a lot to do but I should have the first version of my proprietary server deployed tomorrow.

**Comment by xenolf** [comment]
Thats looking good :)
As @mholt said, etcd support inside of lego is a bit outside of it's intended scope. Would you want to store certificates inside of etcd or the configuration?

**Comment by kalbasit** [comment]
@xenolf it's for storing the certificates inside of etcd. On a kubernetes cluster, this makes more sense than a filesystem, as it's shared between the entire cluster with strong consistency. I'll close this for now, but it would be interesting to make it possible to plugin different storage adapters, perhaps through an interface?
