### ISSUE TITLE
Implement HTTP-01 challenge type

### ISSUE THREAD

**Issue by jhalderm** [xenolf/lego#24]
The existing "simpleHttp" and "dvsni" challenges are insecure, and Let's Encrypt will be disabling them in the near future.  In order to keep working, lego will need to implement the "http-01" or "tls-sni-01" challenges.

See this issue from the official Let's Encrypt client:
https://github.com/letsencrypt/letsencrypt/issues/914

**Comment by xenolf** [comment]
Hello and thanks for reporting this.

Work has begun in the [add-http-01](https://github.com/xenolf/lego/tree/add-http-01) branch.

I will track progress using this issue.
