### ISSUE TITLE
http-timeout is not set correctly

### ISSUE THREAD

**Issue by jmhodges** [xenolf/lego#246]
The `--http-timeout` flag is not actually used in acme.DefaultClient. When that object is made at package initialization time, the `acme.HTTPTimeout` is set to 10 seconds. The update to `acme.HTTPTimeout` is done some time after package initialization during the flag parsing steps but no new client is used.

I ran into this while trying to help the Let's Encrypt folks debug some timeouts I was seeing while hitting their API.

One option is to just ditch the public global variable for the timeout and for the cli code to make a new HTTP client as it needs one.

**Comment by xenolf** [comment]
I chose to remove the `acme.HTTPTimeout` variable completely and replace it with the exported HTTPClient. Should work as advertised now :)
