### ISSUE TITLE
The http default client should be configurable

### ISSUE THREAD

**Issue by kelseyhightower** [xenolf/lego#249]
I'm currently using lego as a library in a service that is running in an execution environment that does not ship with a default ca-certificate bundle. This causes the following errors and prevents me from using the default http client used in the acme package:

```
2016/07/19 16:20:22 Request LetsEncrypt certificate failed: get directory at 'https://acme-staging.api.letsencrypt.org/directory': failed to get "https://acme-staging.api.letsencrypt.org/directory": Get https://acme-staging.api.letsencrypt.org/directory: x509: failed to load system roots and no roots provided
```

I'm using https://github.com/certifi/gocertifi to supply a ca-certificate bundle, but I need the ability to use my own http.Client in place of the default client defined here.

https://github.com/xenolf/lego/blob/master/acme/http.go#L21

One possible fix would be to add a SetHTTPClient function or export the defaultClient variable so I can override this.

**Comment by xenolf** [comment]
I renamed the `acme.defaultClient` to `acme.HTTPClient` and thus exported it to fix #246. Should be fine now for your use case. :)
