### ISSUE TITLE
Fresh "go get" broken

### ISSUE THREAD

**Issue by bshi** [xenolf/lego#250]
Possibly due to breaking changes in `github.com/miekg/dns`

    $ go get github.com/xenolf/lego
    # github.com/xenolf/lego/acme
    go/src/github.com/xenolf/lego/acme/dns_challenge.go:167: unknown dns.Client field 'Timeout' in struct literal
    go/src/github.com/xenolf/lego/acme/dns_challenge.go:171: unknown dns.Client field 'Timeout' in struct literal

Is there a listing of the recommended versions for `lego` dependencies?

**Comment by xenolf** [comment]
Hello and thanks for reporting!
I just tried a `go get -u` and it worked fine.
I can also see the mentioned `Timeout` property in the current `github.com/miekg/dns` master: https://github.com/miekg/dns/blob/master/client.go#L32

Are you sure your local version of `github.com/miekg/dns` is up-to-date?

**Comment by bshi** [comment]
On second inspection, I think this is pilot error.  My `GOPATH` seems to have been put in a bad state by the prior use of godep (https://github.com/tools/godep/issues/60)  Sorry for the noise.  Please feel free to close this out.

    go get -u github.com/xenolf/lego
    # cd /home/bs/go/src/golang.org/x/crypto; git pull --ff-only
    You are not currently on a branch. Please specify which
    branch you want to merge with. See git-pull(1) for details.
    
        git pull <remote> <branch>

**Comment by gaillard** [comment]
I got the same thing?

**Comment by xenolf** [comment]
@gaillard have you checked if it is the same problem as bshi experienced?

**Comment by gaillard** [comment]
I don't use godep

**Comment by bshi** [comment]
@gaillard your call to `go get -u github.com/xenolf/lego` succeeds?
