### ISSUE TITLE
Too many currently pending authorizations after lots of failed dns challenges

### ISSUE THREAD

**Issue by JorritSalverda** [xenolf/lego#253]
Early this week the cloudflare propagation times were sky-high, and even with --dns-timeout 600 the requests were failing - although already after 2 minutes??.

However now that cloudflare is fine again we run into the following error from letsencrypts side:

`acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations`

This happened before 4 months ago when cloudflare had similar issues, so they seem to be related. Could it be the case that the authorizations don't get closed in some failure cases?

**Comment by janeczku** [comment]
@xenolf i think the `--dns-timeout` should override the timeout for the propagation check. Currently this governs the DNS client's timeout for a single UDP query to a name server. This is not obvious to the user (see OP) and i don't quite see the need for this timeout to be configurable in the first place. Thoughts?

**Comment by xenolf** [comment]
@janeczku You are right. Users do expect the `--dns-timeout` switch to govern the propagation check timeout. The issue here is that we allow DNS providers to set their own timeouts via the `ChallengeProviderTimeout` interface so it's not as straight forward to override it in one spot.

**Comment by ldez** [comment]
Fixed by 634
