### ISSUE TITLE
Issue trying to get gcloud / google dns working with Lego

### ISSUE THREAD

**Issue by marl-scot** [xenolf/lego#255]
Hi,
I am trying to test Lego with Google DNS via the gcloud DNS provider.  My issue is, i can not work out what vars need set to get Lego to authnticate to my Google account :(

I have the gcloud CLI utility installed, and have authenticated to my google account.  but i dont know what i need to set for Lego to authticate, anyone able to give me some pointers and examples?

thanks

matt
P.S. this is my first time using gcloud as well as lego :(

**Comment by xenolf** [comment]
Hey there!
The DNS provider for google cloud DNS uses the credentials provided by the CLI utility so you are fine on that part. What lego needs is only an ENV variable `GCE_PROJECT` set to your project.

**Comment by xenolf** [comment]
I assume you solved your problem?
Feel free to re-open if that's not the case.
