### ISSUE TITLE
Proposal: Add --zone flag for DNS challenge

### ISSUE THREAD

**Issue by doublerr** [xenolf/lego#257]
I ran into an issue trying to a cert with multiple SANs on Google using lego. The issue is when trying to get a cert for a subdomain(i.e. `foo.example.com`) when my hosted zone is `example.com`. This doesn't work (as least for Google DNS provider) due to the assumption that the `domain` being passed is also the `zone` being hosted: https://github.com/xenolf/lego/blob/master/providers/dns/googlecloud/googlecloud.go#L127

This is simple enough to fix when the hosted zone is just the `domain.tld` and I have a working fix here: https://github.com/doublerr/lego/commit/99b62912aee47ae917417b1caa0d54893948525b

**BUT** this would break for anyone that want a cert for a fqdn that is multiple sub domains deep (which is me), `a.foo.example.com`.

Since we can't reasonably assume what the hosted zone is, I'd like to propose adding a `--zone` flag for the DNS challenge. This would allow an user to do something like:

```bash
GCE_PROJECT=example-123 lego --dns gcloud --zone=example.com \
--domains=foo.exmaple.com \
--domains=a.foo.example.com \
--domains=bar.example.com \
--email=me@example.com --accept-tos run
```

Since this would change the interface I think we can use a reasonable default that doesn't really change current behavior. Some possible defaults:

1. Assume the zone is `domain.tld`of the supplied fqdn.
1. If 1 fqdn is supplied, assume the zone is that domain. ( This is how things are today)
1. If 2 fqdns are supplied, assume the zone the common portion.

I'm happy to work on this, if this seems like a feature you want.

**Comment by xenolf** [comment]
Hello there!
This seems to be a limitation of the Google DNS provider. The Route53 provider for example, does a lookup on the list of hosted zones to find it. Maybe this is also possible for Google DNS?

**Comment by doublerr** [comment]
@xenolf the route53 provider does something similar when looking up zones. The difference is that it uses acme.FindZoneByFqdn, https://github.com/xenolf/lego/blob/master/providers/dns/route53/route53.go#L128, to solve this problem. That should be an easy fix if it works like I expect.
