### ISSUE TITLE
Agreement URL needs to be updated

### ISSUE THREAD

**Issue by mischapeters** [xenolf/lego#258]
The Let's Encrypt Agreement URL needs to be updated as there is a new one.

```
https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
```

See: https://github.com/lukas2511/letsencrypt.sh/commit/afabfff06e2dece1772ed788ac41ca0d297ab49b

**Comment by mholt** [comment]
Better yet, use `https://acme-v01.api.letsencrypt.org/terms` which always points to the latest version of the SA (at least, for version 1 of the API).

**Comment by mischapeters** [comment]
Works for me. :)

**Comment by xenolf** [comment]
I'm not entirely sure what we should update? The ToS URL isn't hardcoded anywhere but is received from the server during registration.

**Comment by mholt** [comment]
Oh yeah. Weird... where are you seeing this @mischapeters ?

**Comment by mischapeters** [comment]
I just ran a search on the agreement string I found some issues so just wanted to make sure.
If it's not hardcoded that is even better! :)
