### ISSUE TITLE
"Progress" messages for DNS record propagation checks

### ISSUE THREAD

**Issue by voltagex** [xenolf/lego#263]
I'm assuming this check can take 10-20 minutes, especially with multiple domains, but the last message I got was 12 minutes ago.

I understand it'd be pretty difficult to implement any kind of progress bar due to the way the propagation and test works, but maybe a log message when the record is checked again/retried? As it currently stands, I have no idea what the application is doing.

`2016/08/14 16:08:19 [INFO][subdomain.voltagex.org] Checking DNS record propagation...`

**Comment by xenolf** [comment]
Hey there! You mean like to print a message on every iteration of the validation loop?

**Comment by zelenin** [comment]
it seems like dns check is very unstable (maybe just cloudflare) and dns propagation freezes. Sometimes works, sometimes freezes.
