### ISSUE TITLE
dnssimple-go: needless fork?

### ISSUE THREAD

**Issue by onlyjob** [xenolf/lego#264]
Apparently _lego_ uses [github.com/weppos/dnsimple-go](https://github.com/weppos/dnsimple-go) which is an outdated fork of [github.com/dnsimple/dnsimple-go](https://github.com/dnsimple/dnsimple-go). The latter is better maintained and have issues tracker enabled.

Please consider switching to `github.com/dnsimple/dnsimple-go`.

Thanks.

**Comment by lenovouser** [comment]
Pinging @weppos since he seems to be the maintainer.

**Comment by weppos** [comment]
@onlyjob @lenovouser I am the maintainer of the dnsimple-go library and I work for DNSimple. I originally started the client under my account, and moved it under the DNSimple umbrella when it was ready.

However, the one under the DNSimple account only supports API v2. I had on my todo list to upgrade lego with the new client, but it will require switching to API v2.

I will provide a patch ASAP.

**Comment by xenolf** [comment]
closed via #363
