### ISSUE TITLE
PowerDNS provider

### ISSUE THREAD

**Issue by porjo** [xenolf/lego#265]
It'd be great to see support for PowerDNS authoritative nameserver. There are various 3rd party API frontends available for it, however I had thought to make the provider talk to PowerDNS's own RESTful API directly.

I've had a play around with it and it looks feasible. Would anyone have any objections/concerns with me working on a pull request?

**Comment by xenolf** [comment]
Hey!
No objections as long as we can ping you when issues arise :)

**Comment by porjo** [comment]
I've made an initial commit [here](https://github.com/porjo/lego/commit/e9ca62c56809d3d6fbac27f3db6edcc518bb625c). That's tested with v3.x of the PowerDNS server but not v4.x. I'll try and do that soon.
