### ISSUE TITLE
Webroot authenticator

### ISSUE THREAD

**Issue by zakjan** [xenolf/lego#27]
Do you plan to implement webroot authenticator? ACME challenge file can be written to a directory, while another webserver (eg. nginx) is configured to read from it.

Not only it allows to run the client LE application as non-root user, it is also possible to run multiple cert requests at once, because it doesn't block any incoming port.

**Comment by xenolf** [comment]
Well yeah. 
We had a pull request to add this (#16) but unfortunately it was closed by the author.

For now my focus is at implementing the remaining challenges to get full ACME coverage and SAN certificates.

**Comment by zakjan** [comment]
OK. Maybe I'll try to implement it in my spare time.

I noticed you merged http-01, which is great timing because simple-http will be shut down this week. https://community.letsencrypt.org/t/turning-off-old-insecure-challenge-types/3825

**Comment by xenolf** [comment]
That would be great :)

> I noticed you merged http-01, which is great timing because simple-http will be shut down this week.

Yes this was intentional as [caddy](https://github.com/mholt/caddy) depends on this library.

**Comment by zakjan** [comment]
Closing in favor of #32
