### ISSUE TITLE
Add flag/support for OCSP Must Staple x.509 extension

### ISSUE THREAD

**Issue by marumari** [xenolf/lego#270]
Let's Encrypt supports the x.509 must staple extension, which tells user agents that they must receive an OCSP stapling to connect.  Let's Encrypt's "certbot" supports it with the -must-staple option; it would be great to have it in lego as well.

Thanks!

**Comment by xenolf** [comment]
I agree that an OCSP must staple option would be great to have. I might get some free time on my hands this week and will look into it.

**Comment by Night1** [comment]
Hey, I just grabed this from go

but i get this error 

root@apps:~/go/bin# ./lego -d d.pw -d s2.d.pw -d s1.d.pw -m email@gmail.com -a --must-staple run
Incorrect Usage. flag provided but not defined: -must-staple

same when I use --must-staple

any ideas?

**Comment by alemairebe** [comment]
Hi @Night1,
when looking at command help : 
```
./lego_linux_amd64 run --help
NAME:
   lego_linux_amd64 run - Register an account, then create and install a certificate

USAGE:
   lego_linux_amd64 run [command options]  [arguments...]
```
so you need to write your command like : 
`root@apps:~/go/bin# ./lego -d d.pw -d s2.d.pw -d s1.d.pw -m email@gmail.com -a run --must-staple`
