### ISSUE TITLE
unknown http.Transport field 'TLSNextProto'

### ISSUE THREAD

**Issue by mischapeters** [xenolf/lego#279]
When I want to upgrade of lego from 0.3.0 to 0.3.1 or do a clean install with:
go get -u github.com/xenolf/lego

I get the following error message:
```
# github.com/JamesClonk/vultr/lib
lego/src/github.com/JamesClonk/vultr/lib/client.go:80: unknown http.Transport field 'TLSNextProto' in struct literal 
```

This is on OpenBSD 5.9.
Is there anything that I need to add?

**Comment by mholt** [comment]
You need Go 1.6 or higher now. Time to upgrade! :+1:

**Comment by mischapeters** [comment]
Thanx!
