### ISSUE TITLE
Is there a way to append domains to a cert during renewal?

### ISSUE THREAD

**Issue by oliverjanik** [xenolf/lego#283]
Here's my simple use case:

- A subdomain DNS records  are created on the fly
- I need to get a cert for the new subdomain
- because there are rate limits on cert requests / domain I'm using certs where I batch several subdomains together

The problem is I still end up with a lot of separate certs for different batches of sudomains.

Is there a way to renew a cert and append new domains to it?

I tried creating a new cert (run command) everytime with added subdomain, however, this abandons the old cert and I get expiry warnings from let's encrypt for the old abandoned certs.

Is there a better way to manage this use-case?

**Comment by xenolf** [comment]
From what I know, no there is not.
If you want to add a new domain to a cert, the only way is through a new certificate.
Keep in mind that we actually end up creating a new cert on a renew as well, so there is really not much of a difference.

**Comment by oliverjanik** [comment]
If only it didn't send expired certificates warnings :-)
