### ISSUE TITLE
Improvement: Split certificate and ca certificate

### ISSUE THREAD

**Issue by alexs77** [xenolf/lego#286]
At the moment, lego creates a "combined" server certificate + ca certificate file in .lego/certificates/$domain.crt. Certain servers (like Apache < 2.4.8 in Ubuntu 14.04) need a seperate file.

Would be nice, if lego could (optionally) create split files. Having to manually split the certificate file after each run is not so nice.

**Comment by alexs77** [comment]
Nevermind — I now found the --no-bundle switch for run and renew.

**Comment by wichert** [comment]
I don't think `--no-bundle` solves this really: it creates a file with just to certificate, but you will still need a separate file with the intermediate certificates. As far as I can see lego has no way to create that.

**Comment by mholt** [comment]
The intermediate certs are provided by your CA, you can simply download them from your CA, no?
