### ISSUE TITLE
Key type will be ignored

### ISSUE THREAD

**Issue by jonathan-jaekel** [xenolf/lego#287]
Running lego first time (without a private key) I would expect a 4096 bits RSA key to be created. But I got a P384 EC key.

```
rm -rf ./accounts
lego \
--accept-tos \
--dns=ovh \
--email=hostmaster@example.com \
--server=https://acme-staging.api.letsencrypt.org/directory \
--domains=example.com \
--key-type=rsa4096 \
--path . \
run
2016/09/14 18:20:53 No key found for account hostmaster@example.com. Generating a curve P384 EC key.
```

**Comment by mholt** [comment]
The key type you choose is for the certificate, not the account. No need to customize the account key AFAIK.

**Comment by jonathan-jaekel** [comment]
OK, thank you! I had assumed `--key-type` is for both. May be it should be clarified in documentation?

**Comment by xenolf** [comment]
Right. The `--key-type` switch is only for the resulting certificate. There is no way to change the type for your account key.
