### ISSUE TITLE
"failed to load system roots and no roots provided" with Docker image

### ISSUE THREAD

**Issue by Wonderfall** [xenolf/lego#288]
The complete error message is : `2016/09/25 13:38:32 Could not create client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: x509: failed to load system roots and no roots provided`

I've just built the Docker image. Maybe there's a problem with `ca-certificates`?

**Comment by omallo** [comment]
I'm having the same problem with the current [Docker image](https://hub.docker.com/r/xenolf/lego/) (which is updated again after fixing #303 ).

**Comment by xenolf** [comment]
Should be fixed now :)

**Comment by omallo** [comment]
I just tested it with the updated Docker image on Docker Hub and it seems to work fine now, thanks!
