### ISSUE TITLE
fullchain.pem

### ISSUE THREAD

**Issue by JoyceBabu** [xenolf/lego#298]
How can I generate `fullchain.pem`? Why isn't it generated with the other files?

**Comment by xenolf** [comment]
Hello there!
The file we generate only has the intermediate and the client certificate in it which should generally be enough. What is your usecase where you need the CA cert as well?

**Comment by JoyceBabu** [comment]
I did not realize that the `.crt` file contained the Lets Encrypt CA certificate too. Sorry.

**Comment by im7mortal** [comment]
To generate **fullchain.pem**
```go
certificates, failures := client.ObtainCertificate([]string{"example.com"}, bundle, nil, false)
// ...
fullchain := []byte{}
fullchain = append(fullchain, certificates.Certificate...)
fullchain = append(fullchain, certificates.IssuerCertificate...)
```
Then
```go
ioutil.WriteFile("cert.pem", certificates.Certificate, 0644)
ioutil.WriteFile("chain.pem", certificates.IssuerCertificate, 0644)
ioutil.WriteFile("fullchain.pem", fullchain, 0644)
ioutil.WriteFile("privkey.pem", certificates.PrivateKey, 0640)
```

**Comment by Poikilos** [comment]
Uh, where does that code go?
