### ISSUE TITLE
Renew only if certificate is close to expiry

### ISSUE THREAD

**Issue by omallo** [xenolf/lego#302]
I have just started using lego to request and renew certificates using the DNS challenge. While everything works fine, it looks like the `renew` command always renews the certificates, even if the certificate is far away from expiring.

Would it be possible to add an option which prevents the renewal if a certificate is not yet close to expiring? This would facilitate executing the renew command regularly without the certificates being actually renewed on each run. E.g. the official Let's Encrypt client only does a renewal if less than 30 days remain for the expiry date.

**Comment by xenolf** [comment]
Hello there!

That would be the `--days` switch for the `renew` command.
You pass it the number of days you want the cert to have left in order to renew it.

**Comment by omallo** [comment]
hi @xenolf :)

sorry for missing this.. I had just checked the global options in the docs and hadn't seen that there is a command specific option which does exactly what I want! thanks!
