### ISSUE TITLE
Revive the build on Docker Hub

### ISSUE THREAD

**Issue by omallo** [xenolf/lego#303]
It looks like the automated build on [Docker Hub](https://hub.docker.com/r/xenolf/lego/) is not working anymore.

It would be nice if the Docker build could be reactivated and if there were also some tagged images based on the Git tags on Github.

**Comment by xenolf** [comment]
I guess something changed with the integration. Had to manually add a service to the repo. I think it's working again now.

**Comment by omallo** [comment]
@xenolf : Thanks for fixing this so quickly!

Would it also be possible to provide some tagged image on Docker Hub?
