### ISSUE TITLE
urface/cli deprecation warning

### ISSUE THREAD

**Issue by bfallik** [xenolf/lego#305]
Saw this scary warning at the end of the lego run:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

Doesn't seem to prevent lego from doing its job.

**Comment by xenolf** [comment]
Hello there!

Which version of lego are you using?
Sounds a lot like #206 and #232.

**Comment by bfallik** [comment]
```
$ lego --version
lego version 0.3.0
```

Yeah it probably is a dupe. Sorry for the noise.

**Comment by bfallik** [comment]
I installed this using `brew` so I suppose their config is just out-of-date.

**Comment by xenolf** [comment]
I didn't even know that homebrew had lego in it's repository :smile:

**Comment by bfallik** [comment]
achievement unlocked!

**Comment by xenolf** [comment]
Closing this as a dupe of #232
