### ISSUE TITLE
Custom Http Port does not work with multiple domains

### ISSUE THREAD

**Issue by shyim** [xenolf/lego#306]
I found a the awesome method to use a other port than 80 to get the certificates (apache server can be active during yay).

But when i use multiple domains with -d, he tries the normal port 80.
Log:

2016/10/27 18:56:15 [INFO][web.gameserver-sponsor.de, imap.gameserver-sponsor.de, smtp.gameserver-sponsor.de, pop3.gameserver-sponsor.de] acme: Obtaining bundled SAN certificate
2016/10/27 18:56:16 [INFO][web.gameserver-sponsor.de] acme: Could not find solver for: dns-01
2016/10/27 18:56:16 [INFO][web.gameserver-sponsor.de] acme: Trying to solve HTTP-01
2016/10/27 18:56:16 [INFO][web.gameserver-sponsor.de] The server validated our request
2016/10/27 18:56:16 [INFO][imap.gameserver-sponsor.de] acme: Trying to solve TLS-SNI-01
2016/10/27 18:56:17 [INFO][smtp.gameserver-sponsor.de] acme: Could not find solver for: dns-01
2016/10/27 18:56:17 [INFO][smtp.gameserver-sponsor.de] acme: Trying to solve TLS-SNI-01
2016/10/27 18:56:18 [INFO][pop3.gameserver-sponsor.de] acme: Trying to solve HTTP-01
2016/10/27 18:56:19 [pop3.gameserver-sponsor.de] Could not obtain certificates
        acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://pop3.gameserver-sponsor.de/.well-known/acme-challenge/1a0AUcfLOUos2uVdM4sRJHkFsU8jpoYgPJ2Uri-Rm4E [37.114.61.139]: 404
Error Detail:
        Validation for pop3.gameserver-sponsor.de:80
        Resolved to:
                37.114.61.139
        Used: 37.114.61.139

2016/10/27 18:56:19 [imap.gameserver-sponsor.de] Could not obtain certificates
        [imap.gameserver-sponsor.de] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use
2016/10/27 18:56:19 [smtp.gameserver-sponsor.de] Could not obtain certificates
        [smtp.gameserver-sponsor.de] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use

**Comment by xenolf** [comment]
Hello there!
What's the full command line you use to request the certificates?

**Comment by shyim** [comment]
Hey,
here my config

./lego \
     --d="web.gameserver-sponsor.de" \
     --d="imap.gameserver-sponsor.de" \
     --d="smtp.gameserver-sponsor.de" \
     --d="pop3.gameserver-sponsor.de" \
     --email="mymail@outlook.de" \
     --accept-tos \
     --key-type="rsa4096" \
     --http :82 \
     run;

**Comment by mholt** [comment]
If I understand correctly, that command doesn't disable the TLS-SNI challenge, so it still tries to open port 443. I think there's a way with the CLI to limit it to the HTTP challenge and force use of port 82...

**Comment by xenolf** [comment]
Right. There is the `--exclude` switch to exclude certain challenges from the solver.
In your case @shyim the first challenge is solved using HTTP-01 and works, but the second challenge is using TLS-SNI-01 and fails. To get this working you should exclude TLS-SNI-01 using the mentioned switch and it should work just fine.

**Comment by shyim** [comment]
I added the exclude now it hangs on the second solve with HTTP-01
Full log:

```
2016/10/29 13:13:32 [INFO][web.gameserver-sponsor.de, imap.gameserver-sponsor.de, smtp.gameserver-sponsor.de, pop3.gameserver-sponsor.de, mail.gameserver-sponsor.de] acme: Obtaining bundled SAN certificate
2016/10/29 13:13:33 [INFO][web.gameserver-sponsor.de] acme: Could not find solver for: dns-01
2016/10/29 13:13:33 [INFO][web.gameserver-sponsor.de] acme: Trying to solve HTTP-01
2016/10/29 13:13:33 [INFO][web.gameserver-sponsor.de] The server validated our request
2016/10/29 13:13:33 [INFO][imap.gameserver-sponsor.de] acme: Could not find solver for: tls-sni-01
2016/10/29 13:13:33 [INFO][imap.gameserver-sponsor.de] acme: Trying to solve HTTP-01
```

Command:
```bash
./lego \
     --d="web.gameserver-sponsor.de" \
     --d="imap.gameserver-sponsor.de" \
     --d="smtp.gameserver-sponsor.de" \
     --d="pop3.gameserver-sponsor.de" \
     --d="mail.gameserver-sponsor.de" \
     --email="shyim@outlook.de" \
     --exclude="tls-sni-01" \
     --accept-tos \
     --key-type="rsa4096" \
     --http :82 \
     run;
```

**Comment by dessant** [comment]
I have the same issue using 0.31 and master, with one domain it works.

```sh
lego \
--email="test@example.com" \
--d="le.example.com" \
--d="le2.example.com" \
--http="0.0.0.0:37192" \
--exclude="tls-sni-01" \
--exclude="dns-01" \
--accept-tos \
run
```
```
2016/10/30 03:12:20 [INFO][le.example.com, le2.example.com] acme: Obtaining bundled SAN certificate
2016/10/30 03:12:20 [INFO][le.example.com] acme: Could not find solver for: tls-sni-01
2016/10/30 03:12:20 [INFO][le.example.com] acme: Could not find solver for: dns-01
2016/10/30 03:12:20 [INFO][le.example.com] acme: Trying to solve HTTP-01
2016/10/30 03:12:22 [INFO][le2.example.com] acme: Could not find solver for: tls-sni-01
2016/10/30 03:12:22 [INFO][le2.example.com] acme: Could not find solver for: dns-01
2016/10/30 03:12:22 [INFO][le2.example.com] acme: Trying to solve HTTP-01
2016/10/30 03:12:23 [le.example.com] Could not obtain certificates
	acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://le.example.com/.well-known/acme-challenge/BGE76FsTdlPcxqqk-RsPeUsRQ27OE8RVpJ9fcN17e90: "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js "
Error Detail:
	Validation for le.example.com:80
	Resolved to:
		104.41.66.9
		104.41.37.9
		2400:cb00:2048:1::641f:5709
		2400:cb00:2048:1::641f:5609
	Used: 104.41.66.9

2016/10/30 03:12:23 [le2.example.com] Could not obtain certificates
	acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://le2.example.com/.well-known/acme-challenge/GuTpdWmkENxJb-p2Jw48oJfhsM6EOuLIDCnZK5zkaVo: "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js "
Error Detail:
	Validation for le2.example.com:80
	Resolved to:
		104.41.66.9
		104.41.37.9
		2400:cb00:2048:1::641f:5709
		2400:cb00:2048:1::641f:5609
	Used: 104.41.37.9
```

**Comment by xenolf** [comment]
Hello!

@dessant your error looks like your webserver is returning HTML when being accessed by let's encrypts servers. 

@shyim and @dessant please make sure that *every* domain you are trying to validate has some kind of reverse proxy or equivalent set up to your custom port.

For instance I want to validate `ex1.example.com` and `ex2.example.com` and I'm using apache. In this case I have to match the path `ex1.example.com/.well-known/acme-challenge/*` and `ex2.example.com/.well-known/acme-challenge/*` and forward them internally to the port where lego is running.

**Comment by shyim** [comment]
@xenolf i dont using reverse proxy

**Comment by xenolf** [comment]
@shyim See that may be the problem.
Let's Encrypt servers *always* access your server on port 80. When using the `--http` switch you make lego listen on that port but LE will still access port 80. In this configuration you have to somehow pass the requests from port 80 to whatever port you set with the `--http` option.

**Comment by shyim** [comment]
@xenolf ahh now i understand it :)
