### ISSUE TITLE
token != [TEST]

### ISSUE THREAD

**Issue by oneumyvakin** [xenolf/lego#314]
`./lego.amd64 --version`
lego version 0.3.1

*STEPS*

`./lego.amd64 --http 10.8.58.131:4000 --tls 10.8.58.131:4001 --exclude=tls-sni-01 --email="oneumyvakin@mail.com" --domains domain.tld  run`

*ACTUAL RESULT*
```
2016/11/09 07:37:22 [INFO] Received request for domain 10.8.58.131:4000 with method GET
acme: Error 403 - urn:acme:error:unauthorized - The key authorization file from the server did not match this challenge [ywFf-LT1tMZGQeHdm8RypytHoFYe1B6hKQgsT8d6X8Q.lvYtkbjIuSLZ7SdcbKZ1KlrJjHIQF9eudU5frjlMsVM] != [TEST]
```

*EXPECTED RESULT*
Let's provide useful info in log messages or  maybe add in README.md example how to configure web servers.

*INFO*

I've see quite strange writing here:
https://github.com/xenolf/lego/blob/82ac43327b01319544c050d5d78a4edeff9565d2/acme/http_challenge_server.go#L67

```
		if strings.HasPrefix(r.Host, domain) && r.Method == "GET" {
			w.Header().Add("Content-Type", "text/plain")
			w.Write([]byte(keyAuth))
			logf("[INFO][%s] Served key authentication", domain)
		} else {
			logf("[INFO] Received request for domain %s with method %s", r.Host, r.Method)
			w.Write([]byte("TEST"))
}
```

**Comment by LukeHandle** [comment]
Hey there, 

I agree it looks like this "TEST"  data is not quite correct, though it looks to represent an error when LE tries to get the Key Auth. 

The actual cause looks like your reverse proxy is not passing the "Host" header to Lego (or it's not sending a GET). The "TEST"  output is a result of the `if` statement here:
https://github.com/xenolf/lego/blob/82ac43327b01319544c050d5d78a4edeff9565d2/acme/http_challenge_server.go#L61

What reverse proxy do you use/configuration?

**Comment by oneumyvakin** [comment]
Yes, it's happens because of front-end web server doesn't set `host` header. I've using nginx and already fix this. 
I just want to point that it's really difficult to figure out from log message what you should to do now.

**Comment by xenolf** [comment]
@oneumyvakin Thanks for reporting this. I agree that there should be a log when this happens.
