### ISSUE TITLE
How do I generate fullchain.pem?

### ISSUE THREAD

**Issue by voltagex** [xenolf/lego#316]
The official certbot client generates "fullchain.pem" which seems to be the complete chain of trust all the way down to the newly issued certificate.

Would it be possible to get lego to create this file? Most letsencrypt tutorials (especially for nginx) reference the fullchain.pem file.

**Comment by xenolf** [comment]
lego only has support for generating a bundle with the intermediate and leaf certificates, other certificates in the path are not included.

**Comment by stapelberg** [comment]
At least for me, the letsencrypt client’s fullchain.pem contains precisely 2 certificates:

```
Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
Subject: CN=mycn

Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
Subject: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
```

lego’s .crt file contains the same certificates.

I inspected the files using `openssl crl2pkcs7 -nocrl -certfile ~/.lego/certificates/mycn.crt | openssl pkcs7 -print_certs -text -noout`

**Comment by czerasz** [comment]
@stapelberg, @xenolf does this mean `lego-generated.crt` and `fullchain.pem` are equivalent?

**Comment by d0m84** [comment]
It would be cool if this option would work and would be a flag in "global" scope.

**Comment by tacerus** [comment]
I, too, would be interested as to whether Lego's `<domain>.crt` is equal to Certbot's `fullchain.pem`, and if so, if that is by design (and something that can be relied on if i.e. omitting the seperate certificate chain option that some software offers), or if it's just by good luck.

**Comment by tacerus** [comment]
Nevermind, shortly after I found https://github.com/go-acme/lego/issues/1264#issuecomment-702559799 which clears it up.
