### ISSUE TITLE
Cannot Compile freebsd 10.3 with go 1.7.2

### ISSUE THREAD

**Issue by symgryph** [xenolf/lego#324]
I get the following when trying to compile:

go get -u github.com/xenolf/lego
# github.com/xenolf/lego/providers/dns/azure
gocode/src/github.com/xenolf/lego/providers/dns/azure/azure.go:78: unknown dns.RecordSet field 'Properties' in struct literal
gocode/src/github.com/xenolf/lego/providers/dns/azure/azure.go:106: too many arguments in call to rsc.Delete

Any ideas on how to fix?

**Comment by pborzenkov** [comment]
@symgryph I've stumbled upon the same build issue and fixed it. Have a look at this pull request: https://github.com/xenolf/lego/pull/323

**Comment by xenolf** [comment]
Should be fixed now. #323 has been merged.
