### ISSUE TITLE
googlecloud.getHostedZone doesn't work correctly for CNAMEs that cross zones

### ISSUE THREAD

**Issue by ixdy** [xenolf/lego#330]
In my Google cloud project, I have two domains and two zones:
* example.com, with google cloud dns zone `example-com-zone`
* example.net, with google cloud dns zone `example-net-zone`

Subdomains on example.com and example.net are synonyms of each other, so for simplicity, the A records are in `example-com-zone`, and `example-net-zone` just has CNAMEs to the equivalent domain in `example-com-zone`. So for example:
* `foo.example.com. A 1.2.3.4`
* `foo.example.net. CNAME foo.example.com.`

Unfortunately, when `googlecloud.getHostedZone` does a lookup of the `SOA` record (using `acme.FindZoneByFqdn`) for `foo.example.net`, the reported authority is `example.com`. I've confirmed this with `dig -t soa`.

As a result, we try to add the `txt` record in `example-com-zone` instead of `example-net-zone`, and the call fails.

**Comment by ixdy** [comment]
This similarly affects `lookupNameservers` in `acme/dns_challenge.go`, which also uses `FindZoneByFqdn`:

```
2016/12/06 18:17:22 [foo.example.net] Could not obtain certificates
        Time limit exceeded. Last error: NS ns-cloud-b2.googledomains.com. returned REFUSED for _acme-challenge.foo.example.net.
```

In this case, `ns-cloud-b2.googledomains.com.` is the authoritative server for `example.com`, whereas `ns-cloud-c2.googledomains.com` is authoritative for `example.net`.

**Comment by TamalSaha** [comment]
@ixdy Did you try the latest version of lego? This issue seems to be addressed some time ago?https://github.com/xenolf/lego/commit/d6197084fcdbe3fe987a83db7050c971e30d0fb9

I am just trying to find out like you.

**Comment by TamalSaha** [comment]
@ixdy I have tried to address this issue here https://github.com/xenolf/lego/pull/336

**Comment by ixdy** [comment]
@TamalSaha I tried your fix while working on https://github.com/kubernetes-incubator/spartakus/issues/16 and it seemed to work. Thanks!

**Comment by fd** [comment]
#449 Should resolve this issue. The idea is to ignore SOA records that are not a suffix of the domain.

**Comment by xenolf** [comment]
Close via #449
