### ISSUE TITLE
unable to expand domains

### ISSUE THREAD

**Issue by komuW** [xenolf/lego#332]
I already have ssl certs from letsencrypt that I had obtained a few months ago using lego. The cert was a SAN for mysite.com and www.mysite.com

I wanted to to expand(or obtain a new) SAN cert by adding dev.mysite.com and staging.mysite.com 

I did that by running this command: 

`CLOUDFLARE_EMAIL=something@gmail.com CLOUDFLARE_API_KEY=something /usr/local/bin/lego/lego --dns="cloudflare" --email="something@gmail.com" --domains="mysite.com" --domains="www.mysite.com" --domains="staging.mysite.com" --domains="dev.mysite.com" --path=/etc/nginx/.lego -k "rsa2048" run`     

and output was:         

2016/12/12 23:00:23 [INFO][mysite.com, www.mysite.com, staging.mysite.com, dev.mysite.com] acme: Obtaining bundled SAN certificate
2016/12/12 23:00:28 [INFO][mysite.com] acme: Could not find solver for: http-01
2016/12/12 23:00:28 [INFO][mysite.com] acme: Trying to solve DNS-01
2016/12/12 23:00:30 [INFO][mysite.com] Checking DNS record propagation...
2016/12/12 23:00:34 [INFO][mysite.com] The server validated our request
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Could not find solver for: tls-sni-01
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Could not find solver for: http-01
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Trying to solve DNS-01
2016/12/12 23:00:36 [INFO][staging.mysite.com] acme: Could not find solver for: tls-sni-01
2016/12/12 23:00:36 [INFO][staging.mysite.com] acme: Trying to solve DNS-01
2016/12/12 23:00:37 [INFO][staging.mysite.com] Checking DNS record propagation...
2016/12/12 23:00:40 [INFO][staging.mysite.com] The server validated our request
2016/12/12 23:00:41 [INFO][dev.mysite.com] acme: Could not find solver for: http-01
2016/12/12 23:00:41 [INFO][dev.mysite.com] acme: Could not find solver for: tls-sni-01
2016/12/12 23:00:41 [INFO][dev.mysite.com] acme: Trying to solve DNS-01
2016/12/12 23:00:44 [INFO][dev.mysite.com] Checking DNS record propagation...
2016/12/12 23:00:47 [INFO][dev.mysite.com] The server validated our request
2016/12/12 23:00:48 [www.mysite.com] Could not obtain certificates
	Error presenting token: API error -> 81057: The record already exists.

I'm using lego version v0.3.1 on ubuntu 16.04  with go version go1.6.2 linux/amd64         

I noticed that certbot have an `--expand` flag that should be used in a case like this: https://certbot.eff.org/docs/using.html?highlight=expand 

I'm I doing something wrong or doesn't lego support SAN certificate expansion?

**Comment by LukeHandle** [comment]
Hey, I'm assuming you have solved this by now? 

Anyway, notice for this domain it never gets to the DNS validation? As the error suggests, THE Cloudflare API is complaining/failing:
```
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Could not find solver for: tls-sni-01
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Could not find solver for: http-01
2016/12/12 23:00:35 [INFO][www.mysite.com] acme: Trying to solve DNS-01
[...]
2016/12/12 23:00:48 [www.mysite.com] Could not obtain certificates
Error presenting token: API error -> 81057: The record already exists.
```
The `TXT` record it would be trying to create is the following:
`_acme-challenge.www.mysite.com`

Verify in Cloudflare that there is no record already matching that. Cloudflare is failing at this stage as it is unable to add a record that already is listed (duplicate).

**Comment by komuW** [comment]
thanks @LukeHandle for the insight. 
I had solved it by purging all my previous certificates and obtaining new ones with all the subdomains I want. 

I close this issue.
