### ISSUE TITLE
Route53 DNS chooses wrong zone

### ISSUE THREAD

**Issue by xer0x** [xenolf/lego#337]
I have two zones on Route53. Lego is choosing to update the internal zone, but checking the external for updates.

- foo.com (internal)
- foo.com (external)

Public lookups from the internet go to foo.com(external), meanwhile lookups on my VPC go to internal.

I've tried this with the lego v0.3.1 and v0.3.0 releases. I haven't used the latest release yet. I do see that https://github.com/xenolf/lego/pull/254 may have updated this.

**Comment by LukeHandle** [comment]
I believe this was meant to be resolved in #201, see [here](https://github.com/xenolf/lego/blob/ce8fb060cb8361a9ff8b5fb7c2347fa907b6fcac/providers/dns/route53/route53.go#L145-L148).

This should then return the external ID for updating.

**Comment by xer0x** [comment]
Thanks @LukeHandle yes, that fixes it. 

I just built the latest version and it works great. Are there any plans afoot to release a new binary?
