### ISSUE TITLE
Please support AWS_PROFILE

### ISSUE THREAD

**Issue by brianredbeard** [xenolf/lego#351]
As a part of the AWS SDK, an alternative to using `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_REGION` is to use `AWS_PROFILE` which packages all of these options together.  It would be ideal to specify these options as profiles together to simplify deployment.

**Comment by xenolf** [comment]
The command line parameters are not handled by lego directly but through the AWS go package. What is supported there should also be supported by lego.
