### ISSUE TITLE
429 Error when requesting multiple SAN certificate

### ISSUE THREAD

**Issue by Rishka** [xenolf/lego#356]
When requesting a SAN certificate with more that 7 SANs I get a 429 error before validation starts. 

I have tried the packaged binary of v0.3.1, building the Dockerfile, and building from source on OS X.  

It does not seem to matter which auth I use, I can exclude any of the validators and it still fails. 

logs:
```2017/02/24 20:51:21 [INFO] acme: Registering account for certs@example.com
2017/02/24 20:51:23 [INFO][example.com, ex1.com, d.example.com, ex2.com, b.example.com, ex3.com, ex6.com, ex7.com, e.example.com, c.example.com, ex5.com, ex4.com, pg.example.com, a.example.com, staging.example.com, ex8.com, ex9.com] acme: Obtaining bundled SAN certificate
2017/02/24 20:51:24 [INFO][example.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/sF4QY2GrjkL3peLPhNKz00F73k9YwQcmF-XF1nkti38
2017/02/24 20:51:24 [INFO][ex1.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/oJEfmNglpp_x6zeKcx6uxC4XdKJ1EEntIJYXKCWWHd0
2017/02/24 20:51:24 [INFO][b.example.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/PCHQIcfHqi_bqinPqcfPU28A2PzsGz-eCDnX8MSSfYY
2017/02/24 20:51:24 [INFO][ex3.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/7nKV5BG8fMLTHgBX7ECpcWbxPqmUpyPQ4fzoPdnYzFY
2017/02/24 20:51:24 [INFO][ex6.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/zXdounzpnaSXHZOqEvLh-KLA8vED3frmVwBi9cFbwyk
2017/02/24 20:51:24 [INFO][ex7.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/C5lhuEIDopjdhobXTtbxm332A1al5WE66Bk9Wx78jTE
2017/02/24 20:51:24 [INFO][e.example.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/t3F1y_7qsnR0O9y6jP4kPzzn7KwgiekFWv1zsamWC98
2017/02/24 20:51:24 [INFO][ex5.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/LeJ8mjHJiwmfJfE_D5kDPOA7vrzkHuw3jik8AecRlrM
2017/02/24 20:51:24 [INFO][ex4.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/1lKZcZJ3UMb3avNVUaONGH0f3Sg5vuJeRBvg4yNDkdA
2017/02/24 20:51:24 [INFO][a.example.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/N23Nf1UtJcJO8YWLqdEExbrnTMubB8kZum2Uy4-8hpY
2017/02/24 20:51:24 [INFO][ex8.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/3DVIKc4579rtYqu2Fp9AZ6EwT6q-Pk24RnaJZX8AYls
2017/02/24 20:51:24 Error while processing certificate event: Error while obtaining certificate for new domain d.example.com: acme: Error 429 -  -```

**Comment by xenolf** [comment]
> #357 almost fixes this. If you remove the conditional around the delay it does work
Are you positive on this? I did some testing with the PR and I did not run into the 429 anymore.

**Comment by Rishka** [comment]
Yes, and I am not sure why. I am wondering if there are some calls that trigger that authz rate that are not being limited

**Comment by murzick** [comment]
I've just built from source on Centos 6. 

# AWS_REGION=us-east-1 AWS_ACCESS_KEY_ID=ID AWS_SECRET_ACCESS_KEY=KEY /usr/local/lego/lego --path=/etc/letsencrypt-lego --email="a@b.com" \
> --domains="ec.test.xyz" \
> --domains="br.ec.test.xyz" \
> --domains="de.ec.test.xyz" \
> --domains="en.ec.test.xyz" \
> --domains="es.ec.test.xyz" \
> --domains="fr.ec.test.xyz" \
> --domains="it.ec.test.xyz" \
> --domains="ki.test.xyz" \
> --domains="br.ki.test.xyz" \
> --domains="de.ki.test.xyz" \
> --domains="en.ki.test.xyz" \
> --domains="es.ki.test.xyz" \
> --domains="fr.ki.test.xyz" \
> --domains="it.ki.test.xyz" \
> --domains="ol.test.xyz" \
> --domains="br.ol.test.xyz" \
> --domains="de.ol.test.xyz" \
> --domains="en.ol.test.xyz" \
> --domains="es.ol.test.xyz" \
> --domains="fr.ol.test.xyz" \
> --domains="it.ol.test.xyz" \
> --dns="route53" run
2017/03/16 10:21:23 [INFO][ec.test.xyz, br.ec.test.xyz, de.ec.test.xyz, en.ec.test.xyz, es.ec.test.xyz, fr.ec.test.xyz, it.ec.test.xyz, ki.test.xyz, br.ki.test.xyz, de.ki.test.xyz, en.ki.test.xyz, es.ki.test.xyz, fr.ki.test.xyz, it.ki.test.xyz, ol.test.xyz, br.ol.test.xyz, de.ol.test.xyz, en.ol.test.xyz, es.ol.test.xyz, fr.ol.test.xyz, it.ol.test.xyz] acme: Obtaining bundled SAN certificate
2017/03/16 10:21:26 [INFO][ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/ABS0k-MY6dfSr1fu2HF6kbmlu-SZgRFsTcQgEZE_6OM
2017/03/16 10:21:26 [INFO][br.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/90_j0cHXprrgcyt1dtl_9H9iw6zshBwoMy7IEVcTcm8
2017/03/16 10:21:26 [INFO][de.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/crXNTv9YNrn21Q915RHOra3W11t5BW-eDCwzGk_8IZw
2017/03/16 10:21:26 [INFO][en.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/U4KdeIssFSui-HQr0qR8WMF-mLNfV2L8RFNJasuV5Cc
2017/03/16 10:21:26 [INFO][es.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/t0PnA2b832EhQrqtk57Ua3hMzf3tf_Gcb0HqzdMPO3Q
2017/03/16 10:21:26 [INFO][fr.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/RJpaiFEmf2Db1-CY4Kd6pxoRU-0BkFilsk-aV-3N4fs
2017/03/16 10:21:26 [INFO][it.ec.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/E9eoCdH4Iy2RA-deagmFLxW3-adbo_KiHHvgEEJa5Gg
2017/03/16 10:21:26 [INFO][ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/diCTAVBsvquEJKEZbaRjJ8Oazr_AnbisjQuTY-d_Ja0
2017/03/16 10:21:26 [INFO][br.ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/F733AuV_15NVGTp1J-VrGcqhRYjzwGmgD-ctN47VjAc
2017/03/16 10:21:26 [INFO][de.ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/OIGwjkaQwkuHQNnV9grYRGUqOreTbw0gaPnj4t7cs9M
2017/03/16 10:21:26 [INFO][en.ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/5NKdA_APE9OQ6MKmpA-PZL4Y1vgVh3Myc02ZMDbdk1k
2017/03/16 10:21:26 [INFO][es.ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/4BtrbsEwcTDxTy3phdV53Kuqg58GeHQLObUE_AHfvt8
2017/03/16 10:21:26 [INFO][it.ki.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/KkdECwyroPymiBdnciFfJnOXepV6i6N8MGJNOvh4q1c
2017/03/16 10:21:26 [INFO][ol.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/eisvK4lCi9LS8AbZgGFK4d37hFPYxWPb7XkUCGdbYYE
2017/03/16 10:21:26 [INFO][en.ol.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/0KO5GxbselpH76ZXBum0fZqloWW7-lPFR2Ph8TTO0VY
2017/03/16 10:21:26 [INFO][es.ol.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/i99QzcxZLYxlWO4ZYBYRHTdc3LfuC0epRGC8F1UQXlA
2017/03/16 10:21:26 [INFO][fr.ol.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/A6Uat2xCA482ieCbqqd52yQ3ixsGdLuI0tVQN2NLEc0
2017/03/16 10:21:26 [INFO][it.ol.test.xyz] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/OOkj7X5kVoKOmZ1Jrt1Nc3Q1eNcgiafSiQpFmexN5XQ
2017/03/16 10:21:26 [fr.ki.test.xyz] Could not obtain certificates
        acme: Error 429 -  -
2017/03/16 10:21:26 [br.ol.test.xyz] Could not obtain certificates
        acme: Error 429 -  -
2017/03/16 10:21:26 [de.ol.test.xyz] Could not obtain certificates
        acme: Error 429 -  -

**Comment by owais** [comment]
I've been facing the same issue for a week or so. Found this report after submitting the bug report: https://github.com/xenolf/lego/issues/362

Looks like a duplicate.

I just tested with latest master and was able to reproduce the problem

**Comment by trecloux** [comment]
I am also reproducing the issue, but not on staging.
I tested the same fix than @owais and it fixed the issue.

**Comment by tdewolff** [comment]
I can confirm this issue is still present on master and that @Rishka his suggestion (remove the conditional) fixed it for me.

**Comment by xenolf** [comment]
I removed the conditional in master, please report if it works for you ( @owais, @trecloux )

**Comment by trecloux** [comment]
Unfortunately I was able to reproduce the issue 
I built lego with commit `a111d61d85454f5d58a0f843ced3413b5678f244`
I tried to generate 80 certificates, could not reproduce it with 20 or 40
```
bin/lego   \
--accept-tos   \
--email="me@domain.com"   \
--domains="test-01.domain.com"   \
--domains="test-02.domain.com"   \
--domains="test-03.domain.com"   \
--domains="test-04.domain.com"   \
....
--domains="test-79.domain.com"   \
--domains="test-80.domain.com"   \
--dns="exoscale"  \
--dns-timeout 60 \
--server "https://acme-staging.api.letsencrypt.org/directory" \
run
```
Is there a way to tune lego in order to log all HTTP requests ?

**Comment by tdewolff** [comment]
On a side note, can we see a more elaborate error for 429? Something along the lines of "Error 429 - rate limited". Is there a way to see which rate limit was hit?

**Comment by xenolf** [comment]
429 errors should be a thing of the past now. See #390
