### ISSUE TITLE
jws.go post does not error-check responses

### ISSUE THREAD

**Issue by mahmoudm** [xenolf/lego#359]
Ran into this when doing DNS based validation while re-using the private key on the account + obtainCerts. In that case, the Let's Encrypt server returns an error saying you can't re-use the key, but it does not contain a nonce which causes a crash (nil dereference). 

```	
        resp, err := httpPost(url, "application/jose+json", bytes.NewBuffer([]byte(signedContent.FullSerialize())))

	// Even in case of an error, the response should still contain a nonce.
	nonce, nonceErr := getNonceFromResponse(resp)
	if nonceErr == nil {
		j.nonces.Push(nonce)
	}
```

The fix should be to simply do an error check on the httpPost.

**Comment by xenolf** [comment]
Closed via #360
