### ISSUE TITLE
Error `acme: Error 429 -  -`

### ISSUE THREAD

**Issue by owais** [xenolf/lego#362]
We've been using lego at works for almost a year now and it has been working flawlessly until recently it stopped working at all. Both `lego renew` and `lego run` are almost consistently raising Error 429 without any additional details. 

`acme: Error 429 -  -`

```bash
lego --path="lego" --email="admin@mycompany.com" -s=https://acme-staging.api.letsencrypt.org/directory --dns="route53" --dns-timeout=6000 --accept-tos -d="example.io" -d="www.example.io" -d="sub1.example.io" -d="sub2.example.io" -d="dev.example.io" -d="my.example.io" -d="mydev.example.io" -d="qa.mydev.example.io" -d="id.example.io" -d="iddev.example.io" -d="customer.example.io" -d="customerdev.example.io" -d="test.example.io" -d="testdev.example.io" run
2017/03/16 16:45:42 [INFO][example.io, www.example.io, sub1.example.io, sub2.example.io, dev.example.io, my.example.io, mydev.example.io, qa.mydev.example.io, id.example.io, iddev.example.io, customer.example.io, customerdev.example.io, test.example.io, testdev.example.io] acme: Obtaining bundled SAN certificate
2017/03/16 16:45:44 [INFO][www.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/********
2017/03/16 16:45:44 [INFO][sub1.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/********
2017/03/16 16:45:44 [INFO][sub2.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/********
2017/03/16 16:45:44 [INFO][dev.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/*********
2017/03/16 16:45:44 [INFO][my.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/********
2017/03/16 16:45:44 [INFO][mydev.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/*******
2017/03/16 16:45:44 [INFO][qa.mydev.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/***********
2017/03/16 16:45:44 [INFO][iddev.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/*********
2017/03/16 16:45:44 [INFO][customer.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/*********
2017/03/16 16:45:44 [INFO][testdev.example.io] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/**********
2017/03/16 16:45:44 [id.example.io] Could not obtain certificates
	acme: Error 429 -  -
2017/03/16 16:45:44 [example.io] Could not obtain certificates
	acme: Error 429 -  -
2017/03/16 16:45:44 [customerdev.example.io] Could not obtain certificates
	acme: Error 429 -  -
2017/03/16 16:45:44 [test.example.io] Could not obtain certificates
	acme: Error 429 -  -
make: *** [issue-certificates] Error 1
```

This happened against production LE for a few times. I initially thought we hit some rate limits even thought the command was being invoked for the first time in a long time. I waited for 1 week and tried again only to encounter the same issue.

I tried with staging let's encrypt server and it again is failing. If I reduce the number of sub-domains to 3 or 4, it usually tends to proceed without problems (have not tried that with prod). Increasing the number of sub-domains to more than 5-6 makes lego fail with 429 error without any additional details.

I'm using DNS resolver with Route53. Have proper AWS keys in environment and proper route53 access to the AWS user. 

When it fails, it fails immediately after contacting to LE. It does not fail after waiting to authorize using DNS. It seems LE rejects the request for authorization.

**Comment by owais** [comment]
#357 unfortunately did not work for me. A limit of 18 still seems to hit the rate limit. I forked lego and set the max requests per second to 1 and that clearly worked. So this clearly is a bug on LetsEncrypt's side. Their implementation does not match their documentation. It is unclear that number of requests per second works right now.

**Comment by xenolf** [comment]
@owais But 1 rps did work? This issue is really infuriating I must say.

**Comment by owais** [comment]
Yes, 1 rps did indeed work. 20 did not. 18 did not. 1 did. I didn't test any other number.

**Comment by svenkubiak** [comment]
Currently have the same issue. Trying to create a SAN certifiacte with 13 domains and running into

`acme: Error 429 -  - `

**Comment by owais** [comment]
Until this is fixed, you can use this fork that ensures 1RPS
https://github.com/owais/lego

**Comment by trecloux** [comment]
I confirm that I have the same issue and that 1RPS works for me.
@owais are you able to reproduce the issue on staging ? I'm not.

**Comment by owais** [comment]
@trecloux Yes, I was able to reproduce it on staging pretty easily. My certificate has 41 domains so perhaps it takes that many to always trigger the bug with staging.

**Comment by ConradKurth** [comment]
I can confirm seeing this issue on staging. Lowering the rate helped, but hopefully letsencrypt fixes the issue quickly

**Comment by xenolf** [comment]
This should no longer be an issue. See #390
