### ISSUE TITLE
GoogleCloud API call failed

### ISSUE THREAD

**Issue by SergeySevruk** [xenolf/lego#368]
I have a problem with gcloud.
gcloud auth login - ok
gcloud dns managed-zones list
NAME    DNS_NAME                 DESCRIPTION
sub        sub.dom.com.            sub.dom.com.
sub1      sub1.dom.com.           sub1.dom.com.

GCE_PROJECT="prj123" GCE_DOMAIN="sub.dom.com" lego \
    --email="user@dom.com" \
    --domains="web.sub.dom.com" \
    --dns="gcloud" \
    --path="${HOME}/.lego" \
    --server=https://acme-v01.api.letsencrypt.org/directory \
    run

2017/03/26 06:52:59 [INFO][web.sub.dom.com] acme: Obtaining bundled SANrtificate
2017/03/26 06:53:00 [INFO][web.sub.dom.com] AuthURL: https://acme-v01.aletsencrypt.org/acme/authz/DDJKucjgUFLGd0gqOnbBT_SjGIVUj-ulG125gjbCetc
2017/03/26 06:53:00 [INFO][web.sub.dom.com] acme: Could not find solverr: tls-sni-01
2017/03/26 06:53:00 [INFO][web.sub.dom.com] acme: Trying to solve DNS-0
2017/03/26 06:53:00 [web.sub.dom.com] Could not obtain certificates
        Error presenting token: GoogleCloud API call failed: googleapi: Er 403: Insufficient Permission, insufficientPermissions

**Comment by SergeySevruk** [comment]
Hi guys ! Any idea ?

**Comment by mholt** [comment]
I don't know about Google Cloud, but it looks like you do not have permission to make an API call, make sure your system/environment is configured properly. This doesn't appear to be an issue with lego.
