### ISSUE TITLE
hook for dvsni challenge

### ISSUE THREAD

**Issue by coolaj86** [xenolf/lego#37]
I have a situation where the server receiving the certificate has a proxy which serves many servers in front of it (https://github.com/letsencrypt/acme-spec/issues/222).

I need a way for the server behind the proxy to inform the proxy that it would like to respond to SNI requests matching `<challenge1>.<challenge2>.acme.invalid`.

My initial suggestion was that the format of the challenge should be changed to `<challenge1>.<challenge2>.<sub.domain.tld>.acme.invalid` (https://github.com/ietf-wg-acme/acme/issues/23), but that was decided to be a non-optimal solution.

The next-best solution I can come up with is that the client should make a hook available to expose the challenge and and perform any necessary work to ensure that the response to the challenge can be received.

**Comment by coolaj86** [comment]
It looks like this may be related? https://github.com/xenolf/lego/pull/32

**Comment by xenolf** [comment]
Right, we want to make solvers and challenges modular. But we're not quite there yet :)

**Comment by mholt** [comment]
I believe this is now possible with your own solver or provider. (#76) If I'm right @xenolf then please feel free to close issue :smile:

**Comment by xenolf** [comment]
Closing this as nobody opposed.
