### ISSUE TITLE
New release date

### ISSUE THREAD

**Issue by richtr** [xenolf/lego#370]
I noticed that the last release of this project was almost one year ago:

https://github.com/xenolf/lego/releases/tag/v0.3.1

Are there plans to create a new development release soon? Also, will the development release include all DNS providers?

**Comment by xenolf** [comment]
Hello! Yes I've been slacking on releases "a bit". I'd like to get the error 429 issue over with and then have a new release. The release will include all DNS providers by default.

**Comment by gbolo** [comment]
+1

new release tag would be great, so I can update my docker image accordingly

**Comment by anarcat** [comment]
any progress here?

**Comment by mholt** [comment]
I spoke with Sebastian today; he's super busy with some important things in life, but expects to get back to this soon!

**Comment by xenolf** [comment]
Release is out.
