### ISSUE TITLE
Do not fail immediately if one domain fails to validate

### ISSUE THREAD

**Issue by jsha** [xenolf/lego#371]
In https://github.com/xenolf/lego/blob/master/acme/client.go#L493
> // TODO: do not immediately fail if one domain fails to validate.

Is this still a TODO? By my reading of the code, it seems like lego *doesn't* immediately fail if one domain fails to validate. But I could be misreading this?

Note: this might be related to https://github.com/xenolf/lego/issues/253, because if the comment is accurate, that could lead to "leaking" pending authzs.

**Comment by xenolf** [comment]
@jsha You are right, the comment does no longer apply. Lego does not fail immediately but reports errors only at the end.
