### ISSUE TITLE
unknown field 'TXTRecords' at installation

### ISSUE THREAD

**Issue by jlxq0** [xenolf/lego#372]
When I try to install via `go get -u github.com/xenolf/lego`, I get the following error:

```
$ go get -u github.com/xenolf/lego
# github.com/xenolf/lego/providers/dns/azure
go/src/github.com/xenolf/lego/providers/dns/azure/azure.go:77: unknown field 'TXTRecords' in struct literal of type dns.RecordSetProperties
```

A few days ago everything went fine on a quite similar machine.
What am I missing?

**Comment by asidorov95** [comment]
after error
<pre>$ sed -i 's/TXTRecords/TxtRecords/g' ~/go/src/github.com/xenolf/lego/providers/dns/azure/azure.go
$ go get -u github.com/xenolf/lego</pre>

**Comment by xenolf** [comment]
Is it possible that you guys have an older version of the azure go SDK installed? The field is there in the current master of the SDK.

**Comment by asidorov95** [comment]
Last azure SDK changes:
arm/dns/models.go 100644 → 100755 
<pre>
267 -	TXTRecords  *[]TxtRecord        `json:"TXTRecords,omitempty"`
267 +	TxtRecords  *[]TxtRecord        `json:"TXTRecords,omitempty"`
</pre>

**Comment by mholt** [comment]
Ah, they made a breaking change upstream recently.

**Comment by jlxq0** [comment]
I can confirm that replacing 'TXTRecords' with 'TxtRecords' works. Thanks @asidorov95!

**Comment by richtr** [comment]
It works with the caveat that during build it points to xenolf/lego for the azure file. So if you're building this yourself, you need to update this line too in your own repo: https://github.com/xenolf/lego/blob/master/providers/dns/dns_providers.go#L9.
