### ISSUE TITLE
Expose private client methods

### ISSUE THREAD

**Issue by jmcarp** [xenolf/lego#378]
I'd like to get a set of challenges, persist them someplace, and then later (i.e., in a separate request) solve the challenges and request a certificate. Because the relevant methods and types are all private, this isn't possible without copying and pasting a bunch of code from client.go. Would you be open to making `Client.getChallenges`, `Client.solveChallenges`, and `Client.requestCertificate` public methods, and `authorizationResource` a public type? I'd be happy to submit a patch if so.

cc @cnelson

**Comment by ldez** [comment]
I closed because it's outdated since v2.
