### ISSUE TITLE
Leaking authorizations

### ISSUE THREAD

**Issue by jsha** [xenolf/lego#383]
Hi! We've gotten a [couple of reports](https://community.letsencrypt.org/t/failed-challenges-rate-limit-prevention-hosting-provider/32480) from hosting providers that integrate with Let's Encrypt that they are hitting the pending authz rate limit, and are using xenolf/acme. I suspect that this is because some code path in xenolf/acme can leak authorizations (i.e., neither fulfill nor deactivate them) when there are some forms of errors. I'm not sure in more detail what those conditions might look like, but would be able to attempt a repro? For instance, you could set up lego to issue a lot of certificates against staging, including some non-existent domains, and log the resulting authz URLs. You could then fetch each of the authz URLs and check if any of them are in "pending" state. If they are, that would indicate an authz leak.

Thanks for implementing this client, it's a very popular way to interact with Let's Encrypt!

**Comment by mholt** [comment]
What version are they using?

**Comment by RBeaudoin** [comment]
We at Heroku are one of those providers that @jsha mentioned who are having issues with the pending authz limits. I'm hoping that #367 will address these issues as we suspect they are related to bad nonce leaving pending authz requests open, but we forked Lego to allow us to cancel pending authz and are pulling in the upstream change today.

**Comment by xenolf** [comment]
I was able to repro leaks when the solver itself encountered an early error state. @RBeaudoin which challenge are you using?

**Comment by RBeaudoin** [comment]
@xenolf we are using `acme.TLSSNI01`

**Comment by xenolf** [comment]
@RBeaudoin could you try the [authz-cleanup](https://github.com/xenolf/lego/tree/authz-cleanup) branch against staging to see if it solves it for you?

**Comment by RBeaudoin** [comment]
@xenolf I can test today and let you know how things work. If it does, it would be a huge help thank you.

**Comment by jsha** [comment]
@xenolf thanks for working on this! out of curiosity, what are the types of early error state that could cause the solver to leak?

**Comment by RBeaudoin** [comment]
Update: we haven't seen any pending authz issues yet after ~10 hours of running the branch in production. We also haven't seen any bad nonce issues which is very nice.

Unfortunately, we are still seeing the `429 Too Many Requests` despite ee0018c855fa43a43f29280a5be2e4b94f9ac991 and 45beff7ed309e190408d7ac1c89a7b7751596a73 but I'm happy to open a different issue related to that

**Comment by xenolf** [comment]
@RBeaudoin thanks for the update! I will merge the changes into master asap. As far as the `429 Too Many Requests` issue goes... I don't really know what to do about it. We already do limit the requests per second to under the value boulder advertises. Maybe @jsha could give us more insight?

**Comment by trecloux** [comment]
I tried to fix the 429 issue, with a dedicated RoundTripper because the current solution is scheduling the goroutines but not the http calls.... but it was a failure :-(

**Comment by trecloux** [comment]
I tried to fix the 429 issue, with a dedicated RoundTripper because the current solution is scheduling the goroutines but not the http calls.... but it was a failure :-(

**Comment by jsha** [comment]
@RBeaudoin could you open a separate issue for the 429s you're seeing and I can provide feedback there?

**Comment by RBeaudoin** [comment]
Opened #390

**Comment by xenolf** [comment]
Closed by eb711d3
