### ISSUE TITLE
Do not work -  go get -u github.com/xenolf/lego

### ISSUE THREAD

**Issue by theshamuel** [xenolf/lego#389]
When I execute command: _go get -u github.com/xenolf/lego_. I get error:
go/src/github.com/xenolf/lego/providers/dns/azure/azure.go:137: undefined: azure.ServicePrincipalToken
go/src/github.com/xenolf/lego/providers/dns/azure/azure.go:138: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
go/src/github.com/xenolf/lego/providers/dns/azure/azure.go:142: undefined: azure.NewServicePrincipalToken

I think, this [merge](https://github.com/Azure/go-autorest/commit/328c4190af154d401987e7e1669919e8cbffba01) made error

**Comment by xenolf** [comment]
Closed via #391
