### ISSUE TITLE
Cannot unarchive releases

### ISSUE THREAD

**Issue by walterdolce** [xenolf/lego#392]
Hi,

Please see below.

```
curl -O https://github.com/xenolf/lego/releases/download/v0.3.1/lego_linux_amd64.tar.xz

...

unxz lego_linux_amd64.tar.xz

...

unxz: lego_linux_amd64.tar.xz: File format not recognized

```

**Comment by lenovouser** [comment]
@walterdolce in case you need a workaround `tar xf lego_linux_amd64.tar.xz` does the job too. Never heard about `unxz` before 😄

**Comment by walterdolce** [comment]
@lenovouser that I tried, but it didn't work on a Debian Jessie64 😢

**Comment by walterdolce** [comment]
FYI - When unarchiving the package via Ansible (the `unarchive` module) it works normally. I didn't have the time to find out what exact command Ansible is running on a box though..

**Comment by s-yata** [comment]
`curl -O https://github.com/xenolf/lego/releases/download/v0.3.1/lego_linux_amd64.tar.xz` seems to download a redirect page. `-L` option worked well on my environment (Ubuntu 16.04).

```
$ curl -L -O https://github.com/xenolf/lego/releases/download/v0.3.1/lego_linux_amd64.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    774      0 --:--:-- --:--:-- --:--:--   774
100 2244k  100 2244k    0     0   619k      0  0:00:03  0:00:03 --:--:--  857k
```

**Comment by LukeHandle** [comment]
The download does redirect as highlighted. Can also confirm with a `file lego_linux_amd64.tar.xz` if you have downloaded an archive vs. HTML. 

@walterdolce are you able to confirm and close out?

**Comment by xenolf** [comment]
I will take this as a "Yes it is resolved!" :) If not, feel free to re-open the issue or start a new one.
