### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by miekg** [xenolf/lego#393]
Hello,

I want certificate metrics expiration date, traffic to/from LE and other bits that might be interesting.
See https://github.com/mholt/caddy/issues/1683 for a short discussion.

Would this project willing to accept a PR that adds prometheus metrics, so that I can pick those up in https://github.com/miekg/caddy-prometheus?

**Comment by xenolf** [comment]
Hi!

While I like statistics, I'm not sure it will do much in case for LE interaction. Client activity is usually only a few HTTP requests and then nothing for months. Not sure you would get any meaningful data out of it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [xenolf/lego] metrics (#393)..." ]
>Hi!
>
>While I like statistics, I'm not sure it will do much in case for LE interaction. Client activity is usually only a few HTTP requests and then nothing for months. Not sure you would get any meaningful data out of it.

Ack. Thanks for letting me know. Think I'm mostly concerned about TLS cert 
lifetime. Would lego be the correct place to extract *that* data or should this 
happen higher up in the stack?

Thanks!

**Comment by xenolf** [comment]
Well lego does not really interact with the certificates themselves. People usually implement that kind of logic one layer above.

**Comment by miekg** [comment]
OK, then this should indeed happen in a higher layer. Thanks for your feedback.

**Comment by SuperQ** [comment]
I would also like to see a normal Prometheus/OpenMetrics style monitoring endpoint. Since this client typically runs as a service rather than a cron job, normal monitoring is useful.
