### ISSUE TITLE
Support Linode v4 API

### ISSUE THREAD

**Issue by callahad** [xenolf/lego#407]
Linode has publicly released a preview of their new, RESTful API: [announcement](https://forum.linode.com/viewtopic.php?f=26&t=14885), [docs](https://developers.linode.com/v4/introduction). The current Linode support in Lego uses the older API.

There hasn't been any deprecation timeline announced for the previous API, so things this isn't urgent, but it's probably something Lego prepare to support...

**Comment by displague** [comment]
https://github.com/linode/linodego can be used and 
 https://github.com/kubernetes-incubator/external-dns/blob/master/provider/linode.go can as an example.

How should this interact with the support add in https://github.com/xenolf/lego/pull/280 ?
`LINODE_API_KEY`s are only valid in the v3 API, the v4 API requires a different value which tends to be referred to as `LINODE_TOKEN`.
