### ISSUE TITLE
project donations

### ISSUE THREAD

**Issue by donpdonp** [xenolf/lego#410]
ive been very happy with lego since the start of letsencrypt. it does exactly what I want and no more. i see there is still considerable effort being put into this project. if a payment method like https://gratipay.com/ were setup, id contribute in that way. (note im not related to gratipay in any way, I just found them on the web and liked their at-cost payment processing pledge)

**Comment by mholt** [comment]
I think this is a great idea. I don't recommend gratipay as it has had some troubles in the past (and I left it because of that and more). But I have always thought https://donorbox.org/ looked like a good option. @xenolf what do you think?

**Comment by xenolf** [comment]
Thanks for wanting to support the project :)
I added a beerpay badge to the README for people wanting to donate.
