### ISSUE TITLE
Renewing fails without message

### ISSUE THREAD

**Issue by rivo** [xenolf/lego#413]
I cannot renew my domains consistently and I'm not sure if it's a bug or if there is just something I don't understand (btw, if it's the latter, where do I post my question?). Anyway, the first main problem which happens a lot is that renewing just fails without any indication why. lego's output looks like this:

```
lego --email="email@example.com" --domains="example.com" --domains="www.example.com" --http=:81 --tls=:444 renew

2017/07/31 15:37:57 [INFO][example.com] acme: Trying renewal with 1671 hours remaining
2017/07/31 15:37:57 [INFO][example.com, www.example.com] acme: Obtaining bundled SAN certificate
2017/07/31 15:37:58 [INFO][example.com] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/py7Zabci5IIYmz5A3NMvX8HYkTkoXYZITaLcb9T0-LeM
2017/07/31 15:37:58 [INFO][www.example.com] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/OcBGDabcGJX8L6z3VY1234NMf13o-oS89xoc2Mv_Xfo
2017/07/31 15:37:58 [INFO][example.com] acme: Authorization already valid; skipping challenge
2017/07/31 15:37:58 [INFO][www.example.com] acme: Trying to solve TLS-SNI-01
```

And that's where it ends. I would expect the output to end with either `Server responded with a certificate` or with an error message. Am I doing something wrong here?

**Comment by mholt** [comment]
Are you sure you're forwarding your ports correctly? It looks like lego isn't seeing the validation handshake at all.

**Comment by rivo** [comment]
Yes, I believe I am (see below). The thing is, lego's behaviour here is nondeterministic. If I run the command again a few times, it will eventually work.

Any ideas? Could this be some kind of timing issue? And if it doesn't receive the request, wouldn't lego wait for it and never stop instead of just exiting?

```
server {
        listen 80;
        server_name example.com www.example.com;

        location /.well-known/acme-challenge {
                proxy_pass http://127.0.0.1:81;
                proxy_set_header Host $host;
        }
}

server {
        listen 443 ssl;
        server_name example.com www.example.com;

        ssl_certificate /letsencrypt/.lego/certificates/example.com.crt;
        ssl_certificate_key /letsencrypt/.lego/certificates/example.com.key;

        location /.well-known/acme-challenge {
                proxy_pass http://127.0.0.1:444;
                proxy_set_header Host $host;
        }
}
```

**Comment by mholt** [comment]
Ah, nginx is doing SSL termination. That's not gonna work for the TLS challenge. :) You'll have to pass the TCP right on through.

**Comment by rivo** [comment]
Thanks for the pointer, didn't realize that. Is there a way to disable the TLS challenge, so that only HTTP-based challenges get used?

As mentioned, the renewal works sometimes. Is this because lego switches to using the HTTP-based challenge in those cases?

Final question: Wouldn't it be good to get an error message by lego instead of it simply exiting?

**Comment by xenolf** [comment]
Hello!
Yes that's possible with the `--exclude` flag.

`--exclude value, -x value   Explicitly disallow solvers by name from being used. Solvers: "http-01", "tls-sni-01".`

**Comment by rivo** [comment]
Thanks! Didn't catch that one.
