### ISSUE TITLE
Validation request comes without host name

### ISSUE THREAD

**Issue by rivo** [xenolf/lego#414]
Fairly often, a renew request fails with the following message:

```
2017/07/31 15:38:16 acme: Error 403 - urn:acme:error:unauthorized - Incorrect validation certificate for tls-sni-01 challenge. Requested d5896436f7627f4c50a372daabcbc772.01757ad37c2213c1c8d4ecfce85cd09a.acme.invalid from MY.IP.ADD.RSS:443. Received 1 certificate(s), first certificate had names ""
Error Detail:
    Validation for example.com:443
    Resolved to:
        MY.IP.ADD.RSS
    Used: MY.IP.ADD.RSS
```

The reason that the names in the certificate are empty is that a self-signed certificate is being served. This happens only when the validation request is sent to the IP address (MY.IP.ADD.RSS) without the "Host" header. I have multiple domains hosted on the same server and direct HTTP(S) requests to its IP address are deactivated (MY.IP.ADD.RSS:443 uses the self-signed certificate).

For some odd reason, this does not happen consistently. I can run the "renew" request again and it will work, sometimes after two or three tries.

Is there anything I can do to make "renew" work each time?

**Comment by xenolf** [comment]
As per the spec, boulder is not using the Host header for TLS-SNI-01 challenges. This is also not really possible because this challenge operates on a lower level then HTTP. If you need HTTP headers in your setup, please consider only using the HTTP based challenge, not TLS-SNI-01.

**Comment by rivo** [comment]
Yes, I'm realizing this now thanks to your responses in #413.
