### ISSUE TITLE
docker build broken 1.6

### ISSUE THREAD

**Issue by drewart** [xenolf/lego#422]
When I try to build using docker it looks like it's installing and using go 1.6 which breaks on 
`
package context: unrecognized import path "context" (import path does not begin with hostname)`

**Comment by frickenate** [comment]
Same issue for me, unable to build from master.

**Comment by frickenate** [comment]
Managed to install Go 1.9, master build works.

**Comment by xenolf** [comment]
Hey! We only test the code with the last two major versions of go in addition to current tip and that's what is officially supported. You can see the tested versions in the file `.travis.yml`.

**Comment by xenolf** [comment]
To add to that. The code inside of the lego repository itself should build fine with older go versions, but I can't guarantee the same for the dependencies we are using. Especially the 1.8 release was problematic with the introduction of the `context` package which is the source of failure in this particular case. We decided to go with the last two go versions as that seemed to be what most other libraries did as well.

**Comment by april** [comment]
Ahh, I had the same problem. It's super unhelpful that Ubuntu 16 (probably the most common distribution) only installs version 1.6.2.
