### ISSUE TITLE
How to force communication over port 443 only?

### ISSUE THREAD

**Issue by bontchev** [xenolf/lego#437]
We have two problems:

1) Port 80 of our site is under continuous level-7 DDoS attack by a virus, so Let's Encrypt server cannot connect to it over HTTP during the certificate renewal procedure.

2) We are using Apache on Windows 10, so we cannot use `certbot` (which can run only on Linux).

I was hoping to use `lego` for certificate renewal but I can't figure out how to tell it to instruct the Let's Encrypt server to use only communications over port 443 (something, which `certbot` apparently can do). I was hoping that the option `--exclude="http-01"` does this but it doesn't seem to be the case; the server still tries to contact our site over port 80.

**Comment by xenolf** [comment]
Hello!

`--exclude="http-01"` is the way to go. It instructs lego to not attempt to solve the HTTP-01 challenge, which leaves it with only TLS-SNI-01. Could you attach a log from an renewal attempt which failed for you?

**Comment by bontchev** [comment]
I can't do it right now; the machine is at the office and I don't have access to it. I'll try to do it tomorrow.

Besides during renewal, is it possible to restrict communications to port 443 during obtaining of new certificates too? I think we tried both and both times the Let's Encrypt server tried to contact ours over port 80 (regardless of whether we used the `--exclude="http-01"` option or not) but maybe we have confused something

**Comment by xenolf** [comment]
It's the same parameter for both, issuing and renewing a certificate.

**Comment by bontchev** [comment]
Is there anything special we should do, in order to produce a log that would help you locate the problem? Any kind of debug/verbose/whatever option? Or just capture the output (which clearly shows that the Let's Encrypt server is trying to contact ours over port 80 and is timing out)?

**Comment by bontchev** [comment]
OK, we have a "window" during which the virus isn't slamming our site, so we did some experimenting with the test Let's Encrypt server (`acme-staging`). Here is what happens when we try to create new certificates from scratch.

Command line:

```
C:/zzz/Certificates/lego_windows_amd64.exe --exclude="http-01" --server=https://acme-staging.api.letsencrypt.org/directory --key-type=rsa4096 --path=C:/zzz/Certificates/acme-staging.api.letsencrypt.org.directory/nlcv.bas.bg --webroot=C:/zzz/xampp/__WWW__/nlcv.bas.bg --accept-tos --csr=nlcv.bas.bg.csr --email=office@nlcv.bas.bg run
```

As you can see, we are using the `--exclude="http-01"` option.

Output from the program:

```
2017/09/26 16:37:43 No key found for account office@nlcv.bas.bg. Generating a curve P384 EC key.
2017/09/26 16:37:43 Saved key to C:/zzz/Certificates/acme-staging.api.letsencrypt.org.directory/nlcv.bas.bg/accounts/acme-staging.api.letsencrypt.org/office@nlcv.bas.bg/keys\office@nlcv.bas.bg.key
2017/09/26 16:37:44 [INFO] acme: Registering account for office@nlcv.bas.bg
2017/09/26 16:37:46 !!!! HEADS UP !!!!
2017/09/26 16:37:46 
		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "C:/zzz/Certificates/acme-staging.api.letsencrypt.org.directory/nlcv.bas.bg/accounts/acme-staging.api.letsencrypt.org/office@nlcv.bas.bg".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.
2017/09/26 16:37:46 [INFO][nlcv.bas.bg, www.nlcv.bas.bg] acme: Obtaining bundled SAN certificate given a CSR
2017/09/26 16:37:47 [INFO][nlcv.bas.bg] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/5iTFhWHaHCtKnDAveQ5WD0NnzCgQbmN406Q3FmZqAzc
2017/09/26 16:37:47 [INFO][www.nlcv.bas.bg] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/RJ-r1cHJxkFlMR9arRNsac_fpjQjdKLSr4mao1eFZNo
2017/09/26 16:37:47 [INFO][nlcv.bas.bg] acme: Could not find solver for: dns-01
2017/09/26 16:37:47 [INFO][nlcv.bas.bg] acme: Trying to solve HTTP-01
2017/09/26 16:37:49 [INFO][nlcv.bas.bg] The server validated our request
2017/09/26 16:37:49 [INFO][www.nlcv.bas.bg] acme: Could not find solver for: tls-sni-01
2017/09/26 16:37:49 [INFO][www.nlcv.bas.bg] acme: Could not find solver for: dns-01
2017/09/26 16:37:49 [INFO][www.nlcv.bas.bg] acme: Trying to solve HTTP-01
2017/09/26 16:37:50 [INFO][www.nlcv.bas.bg] The server validated our request
2017/09/26 16:37:50 [INFO][nlcv.bas.bg, www.nlcv.bas.bg] acme: Validations succeeded; requesting certificates
2017/09/26 16:37:51 [INFO] acme: Requesting issuer cert from https://acme-staging.api.letsencrypt.org/acme/issuer-cert
2017/09/26 16:37:51 [INFO][nlcv.bas.bg] Server responded with a certificate.
```

The way I read the above, the program tried to use solvers `tls-sni-01`, `dns-01` and `HTTP-01` for the site `www.nlcv.bas.bg`. The first two failed (no surprise for the DNS, but why didn't TLS work?), and eventually the server was validated via HTTP - despite we having told the program not to use HTTP.

Once the virus starts slamming our site again (and HTTP starts timing out again), we'll repeat the experiment and I'll show you the output; it clearly says that the Let's Encrypt server tried to contact ours over port 80 and it has timed out.

I didn't bother removing site name and e-mail address; site name is public and the e-mail address is in the certificate anyway.

One more strange thing. During these experiments, we completely forgot to shut down the Apache server. Yet the program still managed to obtain certificates. How so? I thought it wasn't possible for two different programs to listen on the same TCP port?

**Comment by xenolf** [comment]
As you can see from the command you posted, you actually used the `webroot` challenge solver, which works with Apache if given the right path to your webroot. This would also  explain why you kept seeing it trying to solve via port 80. A explicitly specified webroot option overrules the `--exclude` option.

**Comment by bontchev** [comment]
Hold on, now I am totally confused. The way I understand it, the `webroot` option specifies the path on the local disk where the files of the web server are, so that the challenge sent by the Let's Encrypt server is stored in the right place, where it can find then and authenticate the site. How does this option imply communication over port 80 and not, say, port 443? And, if we don't specify it, how would the program know where to store the files?

This added later.

Nevermind, I think I got it. If the option `webroot` is specified, the program stores the challenge it gets from the Let's Encrypt server in the web root and lets the web server serve them in order for Let's Encrypt server to perform the authentication. That's why it worked when Apache was running. (And it probably won't work if it isn't). When the option is _not_ specified, the program acts as a web server (thus Apache must not be running), stores the challenge files in a local directory and serves them to Let's Encrypt's server when the latter requests them. Perhaps it would be a good idea to describe this more clearly in the documentation.

Our Apache server redirects HTTP requests to HTTPS, so it is still not clear to me why yesterday (when using the `webroot` option) we couldn't renew the certificates; the communication should have happened over port 443 (controlled by our server), which is not impacted by the DDoS. But this is not very important.

The important thing is that we got it to work over port 443 now and updated the certificates, so I am going to close this issue now. Thank you very much for your help!

**Comment by xenolf** [comment]
Glad it worked out for you @bontchev!
For further clarification: by using the `webroot` option you automatically opt into using HTTP-01 exclusively, which is why LE always contacted you on port 80. Additionally, LE will not follow redirects sent by your server for security purposes.

I can see that the current CLI documentation can be a bit misleading. I will try to come up with better wording.
