### ISSUE TITLE
Not working with more than 2 subdomains

### ISSUE THREAD

**Issue by Gradlon** [xenolf/lego#441]
Hi,

I try to get certificates for 1 domain with 3 subdomains but I run into an issue.
Generating works fine for two domains but if I add a third domain it breaks and nginx complains.

lego version v0.4.0-0-g192334c448f7

lego --path=/lego --email=mail@mail.com -d example.com -d www.example.com -d stage.example.com --dns=route53 --pem -k ec384 -a run --must-staple

Nginx fails with the following error:
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/../../") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by porjo** [comment]
So the lego command generates the certificate, but when you use it with Nginx it results in that error? Does the error occur for all 3 domains, or only the last one? Have you tried lego v0.4.1 ?

**Comment by ldez** [comment]
We have changed a lot of code since version 0.4.0, so I close this issue.
