### ISSUE TITLE
Error with DNS-01 update (powerdns 4.1)

### ISSUE THREAD

**Issue by ingothierack** [xenolf/lego#465]
I have an problem to update a certificates from an alpine 3.7 via DNS-01 against an powerdns 4.1 server.

It worked one time in the past, where i on alpine 3.6 (upgraded it later to 3.7)

The Problem is, uri for access to pdns is now somehow wrong assembled.
```
2018/01/12 22:29:02 [INFO][mx1.iwt-promotion.net] acme: Could not find solver for: http-01
2018/01/12 22:29:02 [INFO][mx1.iwt-promotion.net] acme: Trying to solve DNS-01
2018/01/12 22:29:02 Error presenting token: Unexpected HTTP status code 404 when fetching 'http://10.1.0.171:8081/api/v1/api/v1/servers/localhost/zones/iwt-promotion.net.'
```
There is now two times the **/api/v1** part in the uri, thats an invalied url then.
The env var is set to
```
PDNS_API_URL="http://10.1.0.171:8081/"
```
use the prebuild binary "lego version v0.4.1-0-g67c86d860a79"

**Comment by porjo** [comment]
Is the lego process running inside a Docker container, or behind a proxy which could be doing HTTP rewriting?

**Comment by ingothierack** [comment]
No docker. Simple KVMs. The communikation between lego and nameserver is direkt, no proxy.
Will try on a different kvm with other os, to see what happens

**Comment by ingothierack** [comment]
Digged a little bit deeper.
I think, i can now put alpine linux out of the problem. Put in pdns 4.1

The problem here is, das the uri past to makeRequest has already the correct full path.

The error is in 
```
	if c.apiVersion > 0 {
		if !strings.HasPrefix(uri, "api/v") {
			uri = "/api/v" + strconv.Itoa(c.apiVersion) + uri
		} else {
			uri = "/" + uri
		}
}
```
the uri cames in with /api/v1 so current the if statement are executed and doubles the /api/v.

dirty hack to

```
        if c.apiVersion > 0 {
                if !strings.HasPrefix(uri, "/api/v") {
                        uri = "/api/v" + strconv.Itoa(c.apiVersion) + uri
                } else {
                        if !strings.HasPrefix(uri, "/") {
                                uri = "/" + uri
                        }
                }
        }
```
fix the problem and works for me now.

For detailed analysis i must setup an debugging environment. So maybe someone has already on to debug this further.

currently i would blame pdns 4.1 for this, and some api-changes.

**Comment by porjo** [comment]
> currently i would blame pdns 4.1 for this, and some api-changes.

You're correct - URLs returned by the PowerDNS API prior to v4.1 were missing a leading `/` - see: PowerDNS/pdns#4524
