### ISSUE TITLE
modify domains in cert

### ISSUE THREAD

**Issue by porjo** [xenolf/lego#466]
lego should support something like Certbot's `--cert-name` flag to add/remove domains from an existing cert

See: https://certbot.eff.org/docs/using.html?highlight=expand#changing-a-certificate-s-domains

> The --cert-name flag can also be used to modify the domains a certificate contains, by specifying new domains using the -d or --domains flag. If certificate example.com previously contained example.com and www.example.com, it can be modified to only contain example.com by specifying only example.com with the -d or --domains flag.

**Comment by xenolf** [comment]
But ACME does not specify any operation to do this, so it would be a re-issue anyways.

**Comment by porjo** [comment]
> But ACME does not specify any operation to do this, so it would be a re-issue anyways.

Hmm, that's a pity

The problem I'm trying to overcome is the scenario where you request a certificate, then realise that you meant to include an extra domain, so you re-request it adding the extra domain. Now you have 2 certs, and get expiry notices for both which is confusing. Am I missing something really obvious here?

**Comment by mholt** [comment]
No -- I would just recommend not obtaining a certificate until you are sure what names you need on it.

Or do what Caddy does: that is, only 1:1 cert-name mapping.
