### ISSUE TITLE
NAT port support?

### ISSUE THREAD

**Issue by victorhaggqvist** [xenolf/lego#48]
This may or may not be something that one want to support, but I thought I could ask.

By NAT port support I mean having the ability to run with another parameter defining the public port which the Let's Encrypt server should query against. I imagine something like this.

    ./lego [other params...] --port=80 --natport=8888

Where `lego` would be listening on 80 in the local machine but tell the Let's Encrypt server to connect to 8888.

**Comment by xenolf** [comment]
That's not possible at the moment I'm afraid.
The ACME protocol defines the port to query for the server without an option to indicate a different one from the client.
If this part of the spec changes to allow for client side port indication then I will definitely support it.

**Comment by victorhaggqvist** [comment]
OK, too bad.

>The ACME protocol defines the port to query for the server without an option to indicate a different one from the client.

But given this I'm kind of curious how it works.. what does the `--port` param do if not specifying the port?

**Comment by mholt** [comment]
The ACME server still connects on the port specified by the protocol, but you can proxy it to a custom port for lego to listen on.

**Comment by xenolf** [comment]
I think [this comment](https://github.com/xenolf/lego/issues/47#issuecomment-162987299) explains it quite well. I need to add that to the README :)
