### ISSUE TITLE
Broken installation due to github.com/Azure/azure-sdk-for-go/arm/dns dependency

### ISSUE THREAD

**Issue by jammm** [xenolf/lego#489]
Context:
Today, this is what happens when you try to install lego:
```
go get github.com/xenolf/lego
package github.com/Azure/azure-sdk-for-go/arm/dns: cannot find package "github.com/Azure/azure-sdk-for-go/arm/dns" in any of:
...
```

https://github.com/Azure/azure-sdk-for-go/pull/975 <- This PR was released to master today (as part of version `14.0.0`. It seems that they removed the `github.com/Azure/azure-sdk-for-go/arm/dns` folder which means you can't use it anymore (from master branch, at least).

It seems that if you want to continue using this sdk, you'd either have to:

- use an older version somehow (prior to 14.0.0) you would probably need to use a package manager for that; or
- refactor azure acme code to pass in context for calls to `CreateOrUpdate, Delete` and `Get` https://github.com/Azure/azure-sdk-for-go/tree/master/services/dns/mgmt

If I try to use `https://github.com/Azure/azure-sdk-for-go/blob/master/services/dns/mgmt/2017-09-01/dns`, I get:

```
# github.com/xenolf/lego/providers/dns/azure
providers/dns/azure/azure.go:85:29: not enough arguments in call to rsc.CreateOrUpdate
	have (string, string, string, dns.RecordType, dns.RecordSet, string, string)
	want (context.Context, string, string, string, dns.RecordType, dns.RecordSet, string, string)
providers/dns/azure/azure.go:112:21: not enough arguments in call to rsc.Delete
	have (string, string, string, dns.RecordType, string)
	want (context.Context, string, string, string, dns.RecordType, string)
providers/dns/azure/azure.go:133:21: not enough arguments in call to dc.Get
	have (string, string)
	want (context.Context, string, string)
P35037:lego aaryaman.vasishta$ go build
# github.com/xenolf/lego/providers/dns/azure
providers/dns/azure/azure.go:85:29: not enough arguments in call to rsc.CreateOrUpdate
	have (string, string, string, dns.RecordType, dns.RecordSet, string, string)
	want (context.Context, string, string, string, dns.RecordType, dns.RecordSet, string, string)
providers/dns/azure/azure.go:112:21: not enough arguments in call to rsc.Delete
	have (string, string, string, dns.RecordType, string)
	want (context.Context, string, string, string, dns.RecordType, string)
providers/dns/azure/azure.go:133:21: not enough arguments in call to dc.Get
	have (string, string)
	want (context.Context, string, string)
```

**Comment by owais** [comment]
I'm seeing this as well. I remember a similar issue happening in the past. Since lego is shipped as a binary, does it make sense to vendor in the dependencies to avoid breakage due to 3rd party lib changes?

**Comment by jammm** [comment]
@owais I'm not sure about that. Maybe the maintainers can answer that.

In the mean time, I've attempted a fix here https://github.com/xenolf/lego/pull/490

**Comment by owais** [comment]
Of course. I just wanted to bring it up for discussion.

**Comment by jammm** [comment]
Hope they look at this soon! This new change in a dependency seems to have broken all new installations.
