### ISSUE TITLE
Ambiguous error messages

### ISSUE THREAD

**Issue by coolaj86** [xenolf/lego#49]
Caddy gives back a single failure message:

```
2015/12/06 03:51:44 [blog.coolaj86.com] failed to get certificate: The server could not validate our request.
```

while the python client gives back very detailed (and varied) error messages:

```
Failed authorization procedure. blog.coolaj86.com (tls-sni-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for blog.coolaj86.com
```

Asking over at https://github.com/letsencrypt/letsencrypt/issues/1855 as to how they pass error messages.

**Comment by xenolf** [comment]
I'm looking into it.

**Comment by xenolf** [comment]
Could you try [this](https://github.com/xenolf/lego/tree/better-challenge-errors) branch?
