### ISSUE TITLE
Poll authz URL instead of challenge URL

### ISSUE THREAD

**Issue by jsha** [xenolf/lego#493]
In further investigating https://github.com/xenolf/lego/issues/486, I've noticed that at least some of the issues are caused by challenges whose status is "pending" while their parent authz's status is "invalid." 

This is obviously a [Boulder bug](https://github.com/letsencrypt/boulder/issues/3482), and we'll work on fixing it, but one way xenolf-acme can become more robust to it is by polling the authz URL instead of the challenge URL.
We added separate statuses for challenges early on in ACME's evolution, when it seemed like authorizations were likely to have multiple challenges that you would have to fulfill separately.

The latest spec (and Boulder's current assumptions) say that you will never need to fulfill more than one challenge on an authz, so the separate statuses are redundant.
Boulder considers the authz status canonical when calculating whether a client is authorized to issue, so polling the authz URL is somewhat more robust.

**Comment by mholt** [comment]
Hi @jsha -- is this still an issue with acmev2?
