### ISSUE TITLE
After dns challenge, dns record stops working

### ISSUE THREAD

**Issue by cwrau** [xenolf/lego#494]
I tried using [Caddy](/mholt/caddy) for automatic, dns based SSL certificate creation, and the following happened: mholt/caddy#2051

In short, after the dns challenge, which worked, the certificate got successfully requested, but the dns entry, which is a wildcard, stopped working for this particular subdomain, every other subdomain still works.
You can can verify this by running `nslookup chat.cwrcoding.com` and `nslookup caskjchbaksdhcbakjnvxbdxjvn.cwrcoding.com`. As you can see the random string works, as it should, but the other one doesn't.

@beevik 

I'm happy to help in any way, for example namecheap API tests.

**Comment by CWRau** [comment]
As of right now, the dns seems to have fixed itself, probably because of a reload on namecheaps side.
But still, I don't think this should happen at all.

**Comment by beevik** [comment]
What was the exact domain string you used to issue the DNS challenge through lego?

My understanding is that wildcard domain certificates were only recently supported by let's encrypt, so I have never tested them with lego.

One thing to keep in mind is that namecheap can sometimes be slow in propagating domain changes.  I typically see waiting times in excess of an hour for some DNS challenge updates.  I don't know if that has anything to do with what you're seeing here, though.

**Comment by CWRau** [comment]
The cert I'm requesting is not a wildcard one, only the dns record pointing to my server is a wildcard one.

I don't know the exact way caddy uses lego to issue certificates, but I guess it would be `chat.cwrcoding.com`, as I used that inside the configuration.

The wildcard dns record has been setup beforehand, but breaks (only for the challenged subdomain) after issuing, so I don't see how propagation times would come into play, as lego doesn't have to change my A(AAA) dns records.

**Comment by captncraig** [comment]
The dns challenge only touches TXT records of the form `_acme-challenge.**,yourdomain.tld`. None of the certificate issuing code should be modifying your dns records in any way. Especially not the wildcard A record you describe. 

If the client modified that, and you can prove it, it is almost certainly a **major** bug in the namecheap driver.

**Comment by CWRau** [comment]
Mh, maybe it's more of a bug on namecheaps side? I'll try to contact them, and ask about this.

**Comment by captncraig** [comment]
Does it happen again if you add a new sub domain to caddy? It's possible it
was a one time thing.

But now that I think about it, namecheap does require you to provide the
entire zone every time you make a change, so a bug in lego is not out of
the realm of possibilities.

**Comment by captncraig** [comment]
To be honest, namecheap is really not a great dns host. I'd highly recommend hosting your dns with cloudflare for free. It has a better, more used api, and generally better all-around performance.

**Comment by CWRau** [comment]
I'll give cloudflare a shot, but it doesn't have wildcard dns for free :/
I'll test caddy again after work

**Comment by captncraig** [comment]
All dns is free. It is **proxied** wildcard records that aren't on the free plan. That is a different thing altogether.
