### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mizutechvoip** [xenolf/lego#495]
I got the following error:

```
2018/03/06 09:04:54 [INFO][voip.mizu-voip.com] acme: Trying renewal with -1856 hours remaining
2018/03/06 09:04:54 [INFO][voip.mizu-voip.com] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x6d5fa9]

goroutine 13 [running]:
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0x11806840, 0x11800f00, 0x11800ec0, 0x11723e20, 0x12)
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:550 +0xc9
created by github.com/xenolf/lego/acme.(*Client).getChallenges
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:547 +0xe4
```

I got the same with the latest version (downloaded today) and with a 3 months old build.

I am running it on a Windows Server and my command line looks like this:

`"lego.exe" --accept-tos="true" --http="88.150.183.67:80" --tls="88.150.183.67:443" --email="removed@removed.com" --domains="voip.mizu-voip.com" --path="C:\Apps\VoIP\msrv_mizucustomers\.lego" renew`

**Comment by davinkevin** [comment]
Same for me on linux/debian with 0.3.1 and 0.4.1 with the following command 

```bash
$ /opt/lego/lego --server=https://acme-staging.api.letsencrypt.org/directory --email=mymail@gmail.com --domains=foo-bar.tk --http=:1234 --tls=:12345 -a --path /opt/lego/.lego renew
```

**Comment by mizutechvoip** [comment]
Additional details: if I generate a new cert (with the --new flag) then it works. Only the --renew option doesn't work. The problem should be obvious from the crash log since it includes also the curplit source code line. Unfortunately I am not familiar with Go to be able to fix (probably the authMsg variable is null, invalid or crashing on it's parsing).

**Comment by davinkevin** [comment]
Ok for me ! 
I miss it, I've just pasted the line define inside the systemd service for renewal, so I forgot to change it to `new`

Thanks for your help

**Comment by ldez** [comment]
We have changed a lot of code since version 0.4.1, so I close this issue.
