### ISSUE TITLE
Google Domains Support?

### ISSUE THREAD

**Issue by bassrock** [xenolf/lego#497]
Was curious if  https://domains.google.com support was on the horizon. It is different then Google Cloud DNS and is free if you register your domain with google.

**Comment by mholt** [comment]
Unfortunately, Google Domains does not have an API (that I know of). Until it gets an API, there will be no way to support it in lego.

**Comment by bassrock** [comment]
Damn. just confirmed with google support and they filed it as a feature request. Hopefully it gets added :/

**Comment by lightmaster** [comment]
Any change on this in the last 3 years?

**Comment by bortek** [comment]
any updates on this ?
