### ISSUE TITLE
DNS challenge provider: External script?

### ISSUE THREAD

**Issue by fd0** [xenolf/lego#505]
Hi,

thank you all very much for your work on lego! I'd like to use lego (the CLI) for a project which requires using the DNS challenge and running custom code. So while I could add a custom DNS challenge provider and implement the code needed to setup the DNS record in Go, I'm wondering: Would you be willing to merge a new DNS challenge provider which calls out to an external program or script?

The background is that for this project, we're using infrastructure already in place, and all Go code that I would be writing to use it with lego would be highly specific for our setup and of no use to anybody else. Encapsulating this code in a small script (or separate Go program) feels like a much better idea. I can imagine that this is something which may be helpful to other users as well.

It could be named `external` or `script`, the name of the program/script to call could be configured via an environment variable. The program/script would then be run by `lego` with arguments, e.g. `present fqdn value` and `cleanup fqdn value` or so.

Would that be something you'd be willing to merge? If so, I'd be happy to do a PR.

Thanks again!

**Comment by mholt** [comment]
Hey @fd0! Nice to see you here.

I can only guess what xenolf would say, but I don't really see a problem with this. In fact, PR #417 might be what you want, although I think it needs more review before it is merged. I suggest getting involved on that PR and if necessary, make a new one.

**Comment by fd0** [comment]
Ah, interesting, I haven't found that PR. I'll have a look!

**Comment by fd0** [comment]
Ok, the PR does much more than I need, it also adds a second challenge provider which calls out to a named pipe. This could also be solved with a script, e.g. by using `socat`. I'll wait what the original author of the PR says, I'm happy to open a new PR and code this myself, but I'd like to avoid stepping on anybodies toes :)

**Comment by fd0** [comment]
Hm, it seems I misread the activity dates for the PR, the last activity by the submitter was in August last year. Do you think it's likely they will pick it up again?

**Comment by fd0** [comment]
I've tried to implement this and submitted PR #508, it was extremely simple.
