### ISSUE TITLE
Add support for secrets in files

### ISSUE THREAD

**Issue by farmdawgnation** [xenolf/lego#509]
For applications deployed in Docker containers using Docker Swarm - secrets _must_ be stored in files instead of the environment. For reasons largely amounting to the Docker Swarm team's threat model, it seems they will never permit secrets to appear in the environment.

Many Docker images have been implementing the ability to suffix the names of environment variables with `_FILE` to cause the Docker container to read a file to get the value of a secret. For example, the WordPress Docker Image permits `WORDPRESS_DB_PASSWORD` if you wish to put the password in the environment directly, or `WORDPRESS_DB_PASSWORD_FILE` if you wish to have the Docker container read a file to determine the secret.

Lego is used by Traefik and currently my Cloudflare API keys are the only component that I can't populate from a Docker Swarm secret. Given that Traefik is often used as an ingress controller, I think that having support for a `CLOUDFLARE_API_KEY_FILE` et al for the various providers would be a significant value add.

Happy to open a pull request if there's interest in this.

**Comment by xenolf** [comment]
Hey!

I'm not opposed to that idea and I would accept a pull request adding this functionality.

**Comment by farmdawgnation** [comment]
Sweet. I'll try to whip something up soon like.

**Comment by amineo** [comment]
@xenolf Is there any update on @farmdawgnation's PR? This is a much needed upgrade into how creds can be managed. Thanks for all the great work on lego!

**Comment by opichon** [comment]
We've created a docker image that supports docker secrets. https://hub.docker.com/repository/docker/dzangolab/lego/general
