### ISSUE TITLE
error 400 from letsencrypt servers

### ISSUE THREAD

**Issue by jeffallen** [xenolf/lego#51]
lego --email "jra@nella.org" -d nella.org -d blog.nella.org run  
2015/12/13 00:17:21 [INFO] acme: Registering account for jra@nella.org
2015/12/13 00:17:21 [DEBUG] {"resource":"new-reg","contact":["mailto:jra@nella.org"]}
2015/12/13 00:17:21 Could not complete registration
	acme: Error 400 - urn:acme:error:malformed - Unable to read/verify body :: Parse error reading JWS

The "DEBUG" line is something I added to dump the jsonBytes to see if they looked right.

My copy of lego is from c4add3c81ed1bac4f8df20d9ca76e47521a82401

**Comment by xenolf** [comment]
Greetings!

Could you try if it helps to drop the quotes around your email address?
We had some trouble with quotes in the past.

**Comment by jeffallen** [comment]
Quotes: No difference. (The " is eaten up by the shell anyway, lego never sees it.)

The problem turns out to be compiling from Go tip. If I use go1.5.1 it works, if I use go built from tip it fails. There's something about the crypto libs that changed to make this fail. Need to look into it more.

For now assume this is a Go bug (or my build environment) and not lego.

**Comment by mholt** [comment]
Hmm, that's slightly disconcerting.

**Comment by jeffallen** [comment]
Was my mutant mix of go1.5 and go tip compiled libraries. I did rm -rf $GOPATH/pkg/darwin_amd64 and rebuilt and the problem went away. I've seen this before, but rarely enough that I always forget to check it until there's no other possibility. :)

**Comment by mholt** [comment]
Ahhhh, that pkg/ cache will get ya every time. Glad you fixed it, truly! :smile:

**Comment by jeffallen** [comment]
Nope, my testing was flawed, it is most definitely a problem introduce by Go tip. Rewinding Go to Aug 20 (commit 34695c474) makes it work.

Still digging.

**Comment by jeffallen** [comment]
The problem starts after a4fb8c13db3f1501f8195306de571b64ed1aeb73 (nov 1) and before f000523018e80471f51e29cae117831157d8dfb8 (dec 1). Bisecting November now...

**Comment by jeffallen** [comment]
The problem is that letsencrypt.org's servers are doing something wrong with HTTP/2:

./lego -m "test11@nella.org" -s "https://acme-staging.api.letsencrypt.org/directory" -d nella.org -d blog.nella.org run

has the problem

GODEBUG=h2client=0 ./lego -m "test11@nella.org" -s "https://acme-staging.api.letsencrypt.org/directory" -d nella.org -d blog.nella.org run

does not.

Working with them to investigate it. https://github.com/letsencrypt/boulder/issues/1279

**Comment by xenolf** [comment]
Thank you so much for going through all this pain. This surely saved us and possibly even boulder quite the headache :)
