### ISSUE TITLE
ACMEv2: ResolveAccountByKey returns EOF error

### ISSUE THREAD

**Issue by mikepulaski** [xenolf/lego#517]
When calling `client.ResolveAccountByKey()`, an `io.EOF` error is returned. This is due to the fact that an ACME server does not necessarily return a response when an account is found, but rather a `Location` header, according to [section 7.3.1](https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.3.1). 

It seems as though the client is attempting to read an empty response body.

See https://github.com/xenolf/lego/issues/457#issuecomment-373072789 for more details.

**Comment by xenolf** [comment]
Fixed via #518
