### ISSUE TITLE
Support reusing private key for certificate renewals

### ISSUE THREAD

**Issue by janeczku** [xenolf/lego#52]
Currently new private keys are generated for every certificate request - even for renewals.
This is a problem for websites using [Public Key Pinning (HPKP)](https://developer.mozilla.org/en/docs/Web/Security/Public_Key_Pinning).

There should be `--reuse-key` flag for `renew` action that will use the private key of the current certificate to generate the CSR.

**Comment by xenolf** [comment]
Just to get an update in here.
I'm working on this :)

**Comment by janeczku** [comment]
@xenolf What a great :christmas_tree::gift: !

**Comment by xenolf** [comment]
This has just landed in commit db1a519684cfaef862c4aa0345b341c9dae49e45 in the refactor-client branch.

**Comment by xenolf** [comment]
The change is now in master.

**Comment by PunKeel** [comment]
Thanks! <3
