### ISSUE TITLE
azure dns provider not in 'acmev2' branch

### ISSUE THREAD

**Issue by lyderic** [xenolf/lego#520]
Hi,

The #490 fix in providers/dns/azure.go that is found in the 'master' branch has not been ported to the 'acmev2' branch.

As a result, attempting to build the 'acmev2' branch fails.

Cheers,
L.

**Comment by xenolf** [comment]
Hello!
Thanks for reporting this.
It has been fixed in c62cb65ba502f145c95ea5f03aa275bf9d39f668.
