### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by scorredoira** [xenolf/lego#521]
Is it possible to set wildcard domains?

I'm using the latest version (0.4.1) and I try:

```
lego -a --email="xxx@gmail.com" \
        --domains="xxxx.com" \
        --domains="*.xxxx.com" \
        --tls=":9091" \
        --http=":9091" \
        --exclude "tls-sni-01" run
```

And get:
`
acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Wildcard names not supported
`

In the dns provider I have configured:

Type | Name |Value |TTL	
A	 |        @	    |     x.x.x.x	 | 600 seconds
CNAME |	*	 |        @	   |      1/2 Hour

**Comment by xenolf** [comment]
The current stable version 0.4.1 does not support ACMEv2.
If you want ACMEv2 support you need to build lego yourself from the `acmev2` feature branch or wait a bit until we promote it to a release.

**Comment by scorredoira** [comment]
Great, thank you very much!
