### ISSUE TITLE
PowerDNS provider: Support configurable timeout

### ISSUE THREAD

**Issue by evaryont** [xenolf/lego#531]
Right now, the timeout for the PowerDNS provider is currently hard-coded to 2 minutes.

https://github.com/xenolf/lego/blob/5922ca92694ae0d455fc9de4776aa4f141c0dcb6/providers/dns/pdns/pdns.go#L60-L64

However, I run PowerDNS as a hidden primary and my secondaries are slow to show new records. (I use BuddyNS, which has a random delay plus the delay of being eventually consistent.) I've measured a 3 to 4 minute lag in responding to new records. This means that lego (and Caddy) will often time out, try again, but then return an error that the nameservers are responding with invalid challenge responses.

Being able to customize the timeout with an environment variable (`PDNS_TIMEOUT`?) would solve this and other situations where nameservers take more than 2 minutes.

**Comment by ldez** [comment]
Closed by #634
