### ISSUE TITLE
Certificate renewal drops Subject Alternative Name extension

### ISSUE THREAD

**Issue by alcaeus** [xenolf/lego#54]
Previously created a certificate:
```lego --domains example.com --domains www.example.com --email=dev@example.com --path /etc/ssl/letsencrypt run```

Then, tried to renew the certificate:
```
lego --domains example.com --domains www.example.com --email=dev@example.com run
2015/12/15 08:29:36 [INFO] acme: [example.com] Trying renewal with 2015 hours remaining
2015/12/15 08:29:36 [INFO] acme: Obtaining bundled certificates for example.com
2015/12/15 08:29:36 [INFO] acme: Trying to solve HTTP-01
2015/12/15 08:29:37 [INFO] Served key authentication
2015/12/15 08:29:38 The server validated our request
2015/12/15 08:29:38 [INFO] acme: Validations succeeded; requesting certificates
2015/12/15 08:29:40 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2015/12/15 08:29:41 [example.com] Server responded with a certificate.
2015/12/15 08:29:41 Error while loading the certificate for domain www.example.com
	open /etc/ssl/letsencrypt/certificates/www.example.com.crt: no such file or directory
```

Result is a certificate without the correct Subject Alternate Names:
```
X509v3 Subject Alternative Name: 
    DNS:example.com
X509v3 Certificate Policies: 
    Policy: 2.23.140.1.2.1
    Policy: 1.3.6.1.4.1.44947.1.1.1
      CPS: http://cps.letsencrypt.org
      User Notice:
        Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/
```

**Comment by xenolf** [comment]
Could you try with [this branch](https://github.com/xenolf/lego/tree/fix-san-renewal)?
You only need to pass the CommonName domain to lego for renwals as it will now read the remaining domains from the DNSNames property of the certificate.

**Comment by alcaeus** [comment]
I'll take a look later today. Without testing, I do think there is going to be a minor issue with this line: https://github.com/xenolf/lego/blob/fix-san-renewal/acme/client.go#L382
The call to ```ObtainSANCertificates``` should be outside the loop filling the domains array.

**Comment by xenolf** [comment]
Right... moved it out of there

**Comment by alcaeus** [comment]
Tested it today, works like a charm! :+1:
