### ISSUE TITLE
directory missing new registration URL

### ISSUE THREAD

**Issue by kiltum** [xenolf/lego#541]
Lego cannot get acme v2 certs

Command to run

`GCE_PROJECT=traefik-202805 GCE_SERVICE_ACCOUNT_FILE=traefik.json  ./lego -a -m kiltum@kiltum.tech --domains "vsemoe.org" -s https://acme-staging-v02.api.letsencrypt.org/directory --dns gcloud --path .lego run`

I get response from server

```
{
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "qMv3JxOeOgI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
```

lego exit with error **Could not create client: directory missing new registration URL**

But if i switch old scheme

`GCE_PROJECT=traefik-202805 GCE_SERVICE_ACCOUNT_FILE=traefik.json  ./lego -a -m kiltum@kiltum.tech --domains "vsemoe.org" -s https://acme-staging.api.letsencrypt.org/directory --dns gcloud --path .lego run`

I got response 
```
{
  "DcH32RlYkas": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-staging.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "new-authz": "https://acme-staging.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-staging.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-staging.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"
}
```

And all works fine

I am newbie in go, but all looks like error in acme/http.go - func getJSON - 

json.NewDecoder(resp.Body).Decode(respBody) does not fill 

```
type directory struct {
	NewAuthzURL   string `json:"new-authz"`
	NewCertURL    string `json:"new-cert"`
	NewRegURL     string `json:"new-reg"`
	RevokeCertURL string `json:"revoke-cert"`
}
```
because need to change new-authz to newAccount, etc

**Comment by cpu** [comment]
> Lego cannot get acme v2 certs

@kiltum I believe this is expected behaviour. Lego's support for ACME v2 is still in development and unmerged: https://github.com/xenolf/lego/issues/457
