### ISSUE TITLE
RenewCertificate() returns no error but Certificate and Private Key is missing from CertificateResource

### ISSUE THREAD

**Issue by tamalsaha** [xenolf/lego#542]
i am using acme v1 api (master branch)

- https://github.com/appscode/voyager/issues/1023
- https://github.com/jetstack/kube-lego/issues/83

**Comment by ldez** [comment]
could you retry with the latest version?

**Comment by ldez** [comment]
Now we have acme v2 api and without any activity on this issue, I close.
