### ISSUE TITLE
DoS in GetOCSPForCert

### ISSUE THREAD

**Issue by takeyourhatoff** [xenolf/lego#56]
[The following line](https://github.com/xenolf/lego/blob/102a9f756bdc05112e8a890b0c75fcc42e99d531/acme/crypto.go#L70)

```golang
issuerBytes, err := ioutil.ReadAll(resp.Body)
```

allows an an attacker in a network MiTM position to exhaust the memory of any application using lego and cause a runtime panic by holding the previously opened TCP connection open and forging garbage data. The call the ioutil.ReadAll ensures that the application will consume the garbage data until it runs out of memory.

**Comment by takeyourhatoff** [comment]
There are a few more places throughout the codebase that have the same issue. Remember that ioutil.ReadAll is not safe to call when you do not know the length of the io.Reader.

https://github.com/xenolf/lego/search?utf8=%E2%9C%93&q=ioutil.ReadAll

**Comment by xenolf** [comment]
Yeah, thanks for the heads up :)
I want to replace all of them with a limited reader of 1MB. I think 1MB will suffice for most things.

**Comment by takeyourhatoff** [comment]
I took a quick look at the spec to see if I could fine a amount that was "correct", but didn't spot anything at first glance. I'll take another look when I get the time and will send you a PR if I find anything concrete, but 1MB seems sensible.
