### ISSUE TITLE
Could not create client: directory missing new registration URL

### ISSUE THREAD

**Issue by MaxProfit** [xenolf/lego#564]
Hey,

I am having the same issue with the "Could not create client: directory missing new registration URL" however I have all the services shut down, and I keep getting this error. I'm running Wordpress on AWS Ubuntu 16.04 with an apache webserver.

I have checked that the /etc/lego exists, and there is even a key in there, but I cannot create client. Any help would be appreciated.

Thanks,

Matt Williams

There are a bunch of us over at https://community.bitnami.com/t/could-not-create-client-directory-missing-new-registration-url/57992/3

**Comment by ldez** [comment]
Duplicate of #562
