### ISSUE TITLE
CLI support for renew with CSR?

### ISSUE THREAD

**Issue by jrun** [xenolf/lego#577]
I'm hoping someone can confirm that the `renew` CLI command doesn't support the use of a CSR without a private key. I'm not a golang dev so I could be misunderstanding something. 

Assuming that's accurate, is it intentional? Simply not implemented yet?

Is it worthwhile to add to the CLI help indicating `--csr` is limited to `run`? I can take a try at writing something if so.

Relevant pull requests:

- #122
- #224

**Comment by epgdatacapbon** [comment]
Same here.
"--csr" option does not work with "renew".
"lego renew" always create a new private key.

I hope someone fix it.
