### ISSUE TITLE
Flag provided but not defined: 

### ISSUE THREAD

**Issue by DrPreobrazhensky** [xenolf/lego#583]
Any flag I give to lego return this error.

> 2018/06/20 11:37:11 flag provided but not defined: -m

lego version 1.0.1 Downloaded compiled from the release page.

**Comment by ldez** [comment]
You have to add a value after `-m`.

ex: `./lego -m foo@bar.com`

**Comment by DrPreobrazhensky** [comment]
Of course I added.
>Any flag I give to lego.

**Comment by ldez** [comment]
I used the tar (amd64) from https://github.com/xenolf/lego/releases/tag/v1.0.1, and I don't reproduce your issue.

Works for me:
```
./lego -m foo@bar.com
```
