### ISSUE TITLE
renew --days logic backwards

### ISSUE THREAD

**Issue by colinn** [xenolf/lego#59]
The [logic](https://github.com/xenolf/lego/blob/master/cli_handlers.go#L200) of the --days parameter seems reversed to me:

     if int(expTime.Sub(time.Now()).Hours() / 24.0) <= c.Int("days") {
			return
     }

This appears to renew the certificate only if it is NOT about to expire.

Is this the behaviour intended, or a typo?

**Comment by xenolf** [comment]
You are right, the comparison was wrong.
Fixed in 0c8bd2962e9f5f8958b7a9155af3cea1b6907bf4
