### ISSUE TITLE
Move to https://acme-staging.api.letsencrypt.org/acme/new-reg for test access

### ISSUE THREAD

**Issue by jcjones** [xenolf/lego#6]
Howdy, friendly lego devs!
Just wanted to let you know that the long-term location for a convenient Boulder testing site is https://acme-staging.api.letsencrypt.org/acme/new-reg , and that ACME has been updated: https://datatracker.ietf.org/doc/draft-barnes-acme/

(note - corrected URI to go live this week)

If you want to ping me in #letsencrypt on freenode, I'm jcj_moz.

Cheers, and keep up the good work. :+1:

**Comment by xenolf** [comment]
Hey there!

Thanks for bringing this to attention. Is this new URL supposed to replace the https://www.letsencrypt-demo.org/acme/new-reg URL?

**Comment by jcjones** [comment]
That's correct, xenolf. And note I removed the version # from the URI - it'll be going live later this week.

**Comment by jcjones** [comment]
Resolved in 41c2d8cc83a4d04a5d51c701c6724c60200b5286
