### ISSUE TITLE
DuckDNS txt record bug

### ISSUE THREAD

**Issue by fl1pfl0p** [xenolf/lego#600]
It looks like a small bug is clearing IP addresses from DuckDNS when a txt record should be cleared.

The txt parameter is mandatory when clearing the txt record otherwise the IP address will be cleared according to https://www.duckdns.org/spec.jsp

https://github.com/xenolf/lego/blob/c4bbb4b819c087d02066fe745d7ca5b60a480d36/providers/dns/duckdns/duckdns.go#L41-L49

This would work...

```go
// makeDuckdnsURL creates a url to set or clear the TXT record.
// txt == "" will clear the TXT record.
func makeDuckdnsURL(domain, token, txt string) string {
	requestBase := fmt.Sprintf("https://www.duckdns.org/update?domains=%s&token=%s&txt=%s", domain, token, txt)
	if txt == "" {
		return requestBase + "&clear=true"
	}
	return requestBase
}
```

**Comment by loopway** [comment]
Noticing this with traefik v1.6.6. Do you happen to know to which traefik versions this fix has been ported?
