### ISSUE TITLE
Panic Error on Renew

### ISSUE THREAD

**Issue by nsime298** [xenolf/lego#602]
Currently getting a panic error on a renew request. 

```console
root@omitted:/etc/lego/certificates# sudo lego --email=“nate@omitted” --domains=www.omitted.com --path=/etc/lego renew
2018/07/19 01:33:56 [INFO][www.omitted.com] acme: Trying renewal with -458 hours remaining
2018/07/19 01:33:56 [INFO][www.omitted.com] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x789c82]

goroutine 20 [running]:
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc4201521c0, 0xc4203ab4a0, 0xc4203ab020, 0xc420423fc0, 0x11)
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:550 +0x132
created by github.com/xenolf/lego/acme.(*Client).getChallenges
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:547 +0x133
```

Any help would be greatly appreciated.

**Comment by nsime298** [comment]
Getting this on two different servers.

root@omitted:~/etc/lego/accounts# sudo lego --email="omitted" --domains="omitted" --path="/etc/lego" renew
2018/07/19 01:51:27 No key found for account omitted. Generating a curve P384 EC key.
2018/07/19 01:51:27 Saved key to /etc/lego/accounts/acme-v01.api.letsencrypt.org/omitted/keys/omitted.key
2018/07/19 01:51:27 [INFO][omitted.com] acme: Trying renewal with 110 hours remaining
2018/07/19 01:51:27 [INFO][omitted.com] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x789c82]

goroutine 13 [running]:
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc42046e0e0, 0xc42005e8a0, 0xc42005e7e0, 0xc4204008d0, 0xe)
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:550 +0x132
created by github.com/xenolf/lego/acme.(*Client).getChallenges
	/mnt/d/Programming/GoPath/src/github.com/xenolf/lego/acme/client.go:547 +0x133

**Comment by ldez** [comment]
Could you give more information about the lego version?
