### ISSUE TITLE
GCloud provider issue

### ISSUE THREAD

**Issue by mazzy89** [xenolf/lego#604]
I'm trying to use `gcloud` as provider to run DNS Challenge in Terraform.

```
dns_challenge {
    provider = "gcloud"

    config {
      GCE_PROJECT              = "${var.project}"
      GCE_SERVICE_ACCOUNT_FILE = "${pathexpand(var.acme_challenge_config)}"
    }
  }
```

This is the configuration. My `GCE_PROJECT` is different from the `GCE_SERVICE_ACCOUNT_FILE` this because I access the `GCE_PROJECT` from another project that it is defined in the `GCE_SERVICE_ACCOUNT_FILE`.

When I run Terraform I get this:

```
Error presenting token: No matching GoogleCloud domain found for domain ...
```

It seems that the lookup of the domain is done in the project defined in `GCE_SERVICE_ACCOUNT_FILE` rather of the `GCE_PROJECT`.

**Comment by bzub** [comment]
Hi @mazzy89. Just make sure it's clear, you would like to be able to set the `GCE_PROJECT` environment variable such that `lego` overrides the project defined in `GCE_SERVICE_ACCOUNT_FILE`, if there is one in that file?

**Comment by athak** [comment]
Hi, we are experiencing this issue too. `GCE_PROJECT` should override the project in `GCE_SERVICE_ACCOUNT_FILE`. A common use case is using a project to centralize service accounts and then authorizing them in other projects via IAM. We currently have to workaround this by using a restricted service account in the project where the zone resides.
