### ISSUE TITLE
Support ECC Certificate

### ISSUE THREAD

**Issue by spance** [xenolf/lego#61]
Hello,

Do you have plan to implement ECC account key and ECC certificate ?

**Comment by mholt** [comment]
Yes, but Let's Encrypt doesn't support ECC yet: https://community.letsencrypt.org/t/elliptic-curve-cryptography-ecc-support/34?u=mholt

**Comment by spance** [comment]
Thank you.
Wish the Lets Encrypt could support it sooner.

**Comment by xenolf** [comment]
We're trying to track let's encrypt as closely as possible. So as soon as LE has ECC certs we'll support them :)

**Comment by PunKeel** [comment]
Looks like LE supports them


https://community.letsencrypt.org/t/ecdsa-testing-on-staging/8809/54 :-)

**Comment by mholt** [comment]
@PunKeel See the [add-ecc-support](https://github.com/xenolf/lego/tree/add-ecc-support) branch :wink:

**Comment by PunKeel** [comment]
@mholt Thanks! Wasn't shown in Github's search results 

Anyway, nginx doesn't support ECC+RSA yet :'(
