### ISSUE TITLE
Wrong host record in CloudXNS

### ISSUE THREAD

**Issue by PeterPanZH** [xenolf/lego#619]
When I use [Caddy](https://caddyserver.com/) as an HTTP server in DNS challenge mode, it cannot get certificate of my domain hosted by [CloudXNS](https://www.cloudxns.net/).

It seems that there is something wrong with record name generated by Lego.
The host record is set to `_acme-challenge.example.com`.
<img width="984" alt="qq20180816-175531 2x" src="https://user-images.githubusercontent.com/3366499/44202098-9eae3100-a17d-11e8-9ea3-fd258f126ea8.png">

But CloudXNS will resolve it to `_acme-challenge.example.com.example.com`.
<img width="825" alt="qq20180816-174143 2x" src="https://user-images.githubusercontent.com/3366499/44201391-b08ed480-a17b-11e8-9e1b-36ba70ec869e.png">

According to [the document of CloudXNS](https://www.cloudxns.net/Public/Doc/CloudXNS_api2.0_doc_zh-cn.zip) (Chinese version only, sad...), the key `host` **SHOULD NOT** contain the domain again.
For example `_acme-challenge` means `_acme-challenge.example.com` and `_acme-challenge.foo` means `_acme-challenge.foo.example.com`.

Since I don't know GO, I cannot bring a PR. But I think the problem is here:
[https://github.com/xenolf/lego/blob/master/providers/dns/cloudxns/cloudxns.go#L139](https://github.com/xenolf/lego/blob/master/providers/dns/cloudxns/cloudxns.go#L139)

Hoping you can fix it. Thanks a lot.

**Comment by ldez** [comment]
Hello, thanks for reporting :+1:

I fixed the bug, you see the tests related to your bug [here](https://github.com/xenolf/lego/pull/629/files#diff-4dbbc6d030f2241fe58928ab768cecfaR227)

| domain        | host                  |
|---------------|-----------------------|
| `foo.bar.com` | `_acme-challenge.foo` |
| `bar.com`     | `_acme-challenge`     |
