### ISSUE TITLE
CLI displays the wrong version

### ISSUE THREAD

**Issue by venyii** [xenolf/lego#63]
Calling `./lego` shows you some information, including the installed version. Currently it displays the [wrong version](https://github.com/xenolf/lego/blob/master/cli.go#L27) (`master` still shows 0.1.0 while 0.1.1 is released)

Not a huge deal, I was just a little confused at first :)

**Comment by mholt** [comment]
I've been considering doing this for Caddy, I bet lego could benefit from this technique too: http://stackoverflow.com/a/11355611/1048862

This way the version is set in the code automatically at build time.

**Comment by xenolf** [comment]
My bad! Totally forgot to increase the version for the latest release :)
Will get fixed with the next release.

**Comment by shurcooL** [comment]
> This way the version is set in the code automatically at build time.

But that makes the binary no longer `go get`able, doesn't it?

**Comment by mholt** [comment]
Nah. A `go get` is unlikely to be at that exact version since it pulls the latest from master, and if you really want the version you can just run the build script or type it in manually. (I think.)

**Comment by shurcooL** [comment]
Makes sense.

**Comment by xenolf** [comment]
The version was updated to 0.2.0. Release versions will display the version along with the commit from now on.
