### ISSUE TITLE
Environment variables for Alibaba Cloud DNS provider

### ISSUE THREAD

**Issue by ericyan** [xenolf/lego#632]
The newly-merged alidns provider (c22f8d841fc2d1dd95b3a83cdab06b01ca5a0f2a) reads credentials from environment variable `ALIDNS_API_KEY` and `ALIDNS_SECRET_KEY`. However, `ALICLOUD_ACCESS_KEY` and `ALICLOUD_SECRET_KEY` are more idiomatic and are already used in [the official Ansible provider](https://github.com/alibaba/ansible-provider/blob/master/lib/ansible/utils/module_docs_fragments/alicloud.py), [Packer](https://www.alibabacloud.com/blog/how-to-deploy-apps-effortlessly-with-packer-and-terraform_593894) and [Terraform](https://www.terraform.io/docs/providers/alicloud/index.html).

I would suggest that we switch to the more idiomatic environment variable pair, as many users may already have those defined. I can send a pull request if you agree to make this change.

**Comment by ldez** [comment]
@ericyan I'm ok with that change, let's go :smiley:
