### ISSUE TITLE
Tags on docker automated builds

### ISSUE THREAD

**Issue by kuuji** [xenolf/lego#638]
Hi there!

First awesome job on this. This is a great project!

I noticed that you only build the docker container from master in your automated builds on the docker hub. I'm using your docker container and I've had some of my things break in the last few days due to unexpected update.

If you set it up like on the screenshot below you can have

   - images from git tag tagged as the git tag => e.g. xenolf/lego:v1.0.1
   - images from latest git tag tagged as "latest"
   - images from master branch tagged as dev

<img width="1262" alt="screen shot 2018-09-17 at 11 27 41 am" src="https://user-images.githubusercontent.com/2299504/45633281-5bd9c480-ba6d-11e8-89e7-02d14e4da1e7.png">

Let me know if you have any question. You can also add me as a contributor on your hub repo if you want me to set it up => https://hub.docker.com/u/kuuji/

**Comment by xenolf** [comment]
I configured it as seen in the picture but I don't know how long it will take for it to refresh.

**Comment by kuuji** [comment]
@xenolf It will only work going forward. If you want to trigger builds from existing tag you need to enable build triggers at the bottom of the build settings page, then you can trigger them like this

```
curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "v0.5.0"}' -X POST <your_trigger_url>
```

You'll need to replace `<your_trigger_url>` by what's in the docker interface and set the `source_name` appropriately.

I'd recommend doing `v0.5.0` `v1.0.0` and `v1.0.1` in that order, since the last one is always going to trigger a "latest" tag.

**Comment by xenolf** [comment]
Done. Should be fine in a few minutes.
