### ISSUE TITLE
Add a SAN on renew?

### ISSUE THREAD

**Issue by matthewaaronthacker** [xenolf/lego#652]
The first time I used lego, I added only the domain.com and forgot the www.domain.com. I've tried renewing with the extra --domains command, but the new cert doesn't have the SAN. Is this a limitation of lego, or letsencrypt, or am I just doing something wrong?

Barring that, what's the proper procedure for deleting my old cert and starting from scratch? Is it as simple as deleting the certs and running again with the 'run' command?

Thanks!

**Comment by eluczycki** [comment]
Had a similar issue, however 'renew' does not seem to add the new domain, so I changed it to 'run' and though the original [domain.com] gets verified and shows a current authorization, the additional domain [www.domain.com] receives an error that it can not start the HTTP server for the challenge?

2018/10/15 05:00:34 Could not obtain certificates
	acme: Error -> One or more domains had a problem:
[www.collbox.co] [www.domain.com] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied

Any thoughts would be helpful, thanks!

**Comment by lenovouser** [comment]
@eluczycki either something else is already running on port 80 or - more likely - your OS only allows users with elevated permissions to bind to port 80. In that case `setcap 'cap_net_bind_service=+ep' /path/to/lego` should to the trick. You can get the path with `which lego` on most UNIX systems.

**Comment by ldez** [comment]
For now, the `renew` command use only the first domain.
As a work around, you can `revoke` and `run`.

**Comment by matteocontrini** [comment]
This works now, thanks 🎉
