### ISSUE TITLE
--tls flag not recognized

### ISSUE THREAD

**Issue by atomicus** [xenolf/lego#654]
```./lego -d=test.example.com --email=test@example.com  --http=":80" --tls=":443" run```

Returns error:
`flag provided but not defined: -tls`

`lego version 1.0.1`

**Comment by xenolf** [comment]
Hey!

The TLS-SNI-01 challenge was disabled permanently by Let's Encrypt because of a security issue with it. As such we removed the flag from the client.
More information can be found [here](https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811)
