### ISSUE TITLE
Wildcard certs are not generated, dns-01 resolver error.

### ISSUE THREAD

**Issue by atomicus** [xenolf/lego#655]
Hi, 
so lego works for my domains:
`test.app.example.com`
`app.example.com`
but not for:
`*.app.example.com`

Everything is set up identically on DNS provider side (*.app.example.com, app.example.com point to the same).

I'm running command as:
```
~# ./lego -d=*.app.example.com --email=test@example.com -a run
```
Results in:
```
2018/10/01 16:00:25 [INFO][*.app.example.com] acme: Obtaining bundled SAN certificate
2018/10/01 16:00:26 [INFO][*.app.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/...
2018/10/01 16:00:26 [INFO][app.example.com] acme: Could not find solver for: dns-01
2018/10/01 16:00:26 Could not obtain certificates
	acme: Error -> One or more domains had a problem:
[app.example.com] [app.example.com] acme: Could not determine solvers
```

**Comment by atomicus** [comment]
A question too it also, as it's not stated clerly (or I did not find it).
Dowildcard domain require work only with dns challange (which in fact requires a plugin, or manual txt entries) or it should also work with well-known (http) type of auth?

**Comment by ldez** [comment]
@atomicus Hello, which DNS providers are you using?

The wildcard certificates are only available with the DNS challenge, it's a constraint due to Let's Encrypt.
