### ISSUE TITLE
Name.com DNS-provider acme: Error -> One or more domains had a problem:

### ISSUE THREAD

**Issue by asodastreamer** [xenolf/lego#656]
The error-message continues as follows:
```
time limit exceeded: last error: NS ns2lns.name.com. did not return the expected TXT record
```
This happens to me all the time.
On my local box as well as on my server.
What is interesting is that lego creates a dedicated domain for the acmen-challenge.
_acme-challenge.mydomain.me 
I would expect the TXT-record to be under mydomain.me as I call it for the entire domain.

I call lego in the following way:

```
lego -d mydomain.me -m em@a.il --path $HOME/.lego  --filename $HOME/tmp/certificates/mydomain.crt --pem --dns namedotcom   run
```

As far as propagations are concerned:
locally I use a caching dns-proxy, but I emptied the cache before the lego-run and I run 

```
dig -t TXT _acme-challenge.mydomain.me
```
while I wait for lego to fail.

I see the TXT-record being present.

P.s.: On an unrelated note:
I also noticed that lego does not clean up after itself in the event of a failure. While this is good for debugging, it might not be wanted for the majority of cases a failure happens

**Comment by moimart1** [comment]
Same problem here with lego `v1.1.0`

```
> sudo NAMECOM_USERNAME=abc NAMECOM_API_TOKEN=abc lego --accept-tos --dns namedotcom --dns-timeout 60 --domains *.mydomain.com --email ssl@mydomain.com --path /tmp run
2018/10/28 18:38:50 No key found for account ssl@mydomain.com. Generating a curve P384 EC key.
2018/10/28 18:38:50 Saved key to /tmp/accounts/acme-v02.api.letsencrypt.org/ssl@mydomain.com/keys/ssl@mydomain.com.key
2018/10/28 18:38:51 [INFO] acme: Registering account for ssl@mydomain.com
2018/10/28 18:38:51 !!!! HEADS UP !!!!
2018/10/28 18:38:51 
		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/tmp/accounts/acme-v02.api.letsencrypt.org/ssl@mydomain.com".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.
2018/10/28 18:38:51 [INFO] [*.mydomain.com] acme: Obtaining bundled SAN certificate
2018/10/28 18:38:51 [INFO] [*.mydomain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/c-abc
2018/10/28 18:38:51 [INFO] [mydomain.com] acme: Preparing to solve DNS-01
2018/10/28 18:38:52 [INFO] [mydomain.com] acme: Trying to solve DNS-01
2018/10/28 18:38:52 [INFO] [mydomain.com] Checking DNS record propagation using [127.0.0.53:53]
2018/10/28 18:38:52 [INFO] Wait [timeout: 1m0s, interval: 2s]
2018/10/28 18:39:53 Could not obtain certificates
	acme: Error -> One or more domains had a problem:
[mydomain.com] time limit exceeded: last error: NS ns1ksz.name.com. did not return the expected TXT record [fqdn: _acme-challenge.mydomain.com.]
```

**Comment by moimart1** [comment]
I think it's a `name.com` problem. The time to propagate DNS records seems very long 
I used `NAMECOM_PROPAGATION_TIMEOUT=900` and `NAMECOM_POLLING_INTERVAL=20` after a second retry, it's worked

In `dns_challenge::checkAuthoritativeNss`, the `dnsQuery` don't return anything for following nameservers `ns1ksz.name.com. / ns4qxz.name.com. / ns3gnv.name.com. / ns2fln.name.com`
But if I use an online service like https://mxtoolbox.com/TXTLookup.aspx I get the acme-challenge

Voilà

**Comment by asodastreamer** [comment]
I can cofirm that moimart1's approach is working.
But I don't think it has to do with name.com.
subsequent certificate-requests go way faster.
Also the certificate returned, is not made out to a wildcard-comain but to the root-domain so not *.domain.tld but rather domain.tld.

**Comment by ldez** [comment]
I think there are 2 problems:
- default values (timeout and interval) for name.com are too small
- `checkAuthoritativeNss` have "weird" behavior.

So:
- I will change default timeout and interval to `900` and `20` as suggested by @moimart1 
- the behavior of `checkAuthoritativeNss` will be changed in #700
