### ISSUE TITLE
netcup: provider not working, since response is incorrectly unmarshalled

### ISSUE THREAD

**Issue by nnexai** [xenolf/lego#686]
Using ACME DNS-01 in traefik using netcup as provider fails on login.

Please see #685 for more details.

The pull-requests does not complete CI, since I just changed the file directly in github (seems like indention, whitespace rules or line length didn't end up correctly).

Hopefully someone with a bit of GO-Programming experience can build a fix based on the PR (fixing the incorrect unmarshalling).

Thanks!

**Comment by ldez** [comment]
@nnexai could you try this Docker image `ldez/traefik:netcup`?

**Comment by nnexai** [comment]
@ldez 
`time="2018-10-22T19:41:39Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[XXX] error presenting token: netcup: error logging into DNS-API, status: error, short: Validation Error., message: Customer account not found. JSON decode failed while validating request.\n"`

I need to do some more validation for the setup I am running - getting back to you later

**Comment by nnexai** [comment]
> could you check your customer id.
> `Customer account not found` come from Netcup

Figured that much ;) it is quite cumbersome to test these things since I am currently using the whole thing via kubernetes and secrets as environment variables.. the secrets and env-variables look good, but since traefik does not log any of these values and the container is empty except for the traefik binary i am kind of stuck atm

**Comment by ldez** [comment]
I will produce a custom version with more logs (but you will need to activate `acmeLogging` in Traefik)

**Comment by nnexai** [comment]
thx i did some local testing with docker and there it seems to work.. 

``` text
time="2018-10-22T20:35:32Z" level=info msg="Testing certificate renew..."
time="2018-10-22T20:35:32Z" level=info msg="ingress label selector is: \"\""
time="2018-10-22T20:35:32Z" level=info msg="Creating cluster-external Provider client"
time="2018-10-22T20:35:32Z" level=error msg="Error starting provider *acme.Provider: endpoint missing for external cluster client"
time="2018-10-22T20:35:32Z" level=info msg="The key type is empty. Use default key type 4096."
time="2018-10-22T20:35:32Z" level=info msg="Server configuration reloaded on :444"
time="2018-10-22T20:35:32Z" level=info msg="Server configuration reloaded on :8080"
time="2018-10-22T20:35:32Z" level=info msg="Server configuration reloaded on :81"
time="2018-10-22T20:35:36Z" level=info msg=Register...
time="2018-10-22T20:35:36Z" level=info msg="legolog: [INFO] acme: Registering account for nnex.ai@gmail.com"
time="2018-10-22T20:35:37Z" level=info msg="legolog: [INFO] [*.XXX.de, XXX.de] acme: Obtaining bundled SAN certificate"
time="2018-10-22T20:35:38Z" level=info msg="legolog: [INFO] [*.XXX.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXX"
time="2018-10-22T20:35:38Z" level=info msg="legolog: [INFO] [XXX.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXX"
time="2018-10-22T20:35:38Z" level=info msg="legolog: [INFO] [XXX.de] acme: Could not find solver for: http-01"
time="2018-10-22T20:35:38Z" level=info msg="legolog: [INFO] [XXX.de] acme: Preparing to solve DNS-01"
time="2018-10-22T20:35:39Z" level=info msg="legolog: [INFO] [XXX.de] acme: Preparing to solve DNS-01"
time="2018-10-22T20:35:41Z" level=info msg="legolog: [INFO] [XXX.de] acme: Trying to solve DNS-01"
time="2018-10-22T20:35:41Z" level=info msg="legolog: [INFO] [XXX.de] Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]"
time="2018-10-22T20:35:41Z" level=info msg="legolog: [INFO] Wait [timeout: 1m0s, interval: 2s]"
time="2018-10-22T20:36:41Z" level=error msg="Error obtaining certificate retrying in 413.281216ms"
time="2018-10-22T20:36:42Z" level=info msg="legolog: [INFO] [*.XXX.de, XXX.de] acme: Obtaining bundled SAN certificate"
time="2018-10-22T20:36:42Z" level=info msg="legolog: [INFO] [*.XXX.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXX"
time="2018-10-22T20:36:42Z" level=info msg="legolog: [INFO] [XXX.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXX"
time="2018-10-22T20:36:42Z" level=info msg="legolog: [INFO] [XXX.de] acme: Could not find solver for: http-01"
time="2018-10-22T20:36:42Z" level=info msg="legolog: [INFO] [XXX.de] acme: Preparing to solve DNS-01"
time="2018-10-22T20:36:44Z" level=info msg="legolog: [INFO] [XXX.de] acme: Preparing to solve DNS-01"
time="2018-10-22T20:36:45Z" level=info msg="legolog: [INFO] [XXX.de] acme: Trying to solve DNS-01"
time="2018-10-22T20:36:45Z" level=info msg="legolog: [INFO] [XXX.de] Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]"
time="2018-10-22T20:36:45Z" level=info msg="legolog: [INFO] Wait [timeout: 1m0s, interval: 2s]"
time="2018-10-22T20:37:46Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[XXX.de] time limit exceeded: last error: NS second-dns.netcup.net. did not return the expected TXT record [fqdn: _acme-challenge.XXX.de.]\n"
time="2018-10-22T20:37:46Z" level=error msg="Unable to obtain ACME certificate for domains \"*.XXX.de,XXX.de\" : unable to generate a certificate for the domains [*.XXX.de XXX.de]: acme: Error -> One or more domains had a problem:\n[XXX.de] time limit exceeded: last error: NS second-dns.netcup.net. did not return the expected TXT record [fqdn: _acme-challenge.XXX.de.]\n"
```
i saw the interactions with the api in the api-log of netcup (with better set ttl and time limits i think it would have worked locally)  - now I just need to find out why the kubernetes deployment doesn't work

**Comment by ldez** [comment]
Could you pull my image and retry?

**Comment by nnexai** [comment]
Thanks - found the problem.. kubernetes introduced a newline at the end of all secrets (api-key, api-password and customer-number).
Thus the number was set to "123\n"
Now I just need to get this fixed =)

**Comment by nnexai** [comment]
got the following output
``` text
time="2018-10-22T21:18:09Z" level=error msg="Unable to obtain ACME certificate for domains \"*.XXX.de,XXX.de\" : unable to generate a certificate for the domains [*.XXX.de XXX.de]: acme: Error -> One or more domains had a problem:\n[XXX.de] error presenting token: netcup: error when sending the request: an error occurred during the action infoDnsRecords: [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ]\n"
```
looks to me this is just a problem of my kubernetes setup.. at the moment 2 traefik instances are competing to setup dns entries.. according to the previous local run and the kubernetes runs which except for useage errors also work, i would say the fix is working as intended

**Comment by ldez** [comment]
Could you pull my image and retry?

**Comment by nnexai** [comment]
Still getting:
"Value in field domainname does not match requirements of type: domainname."
even though the error is not shown in the traefik log (but rather in the netcup log)

this is happens on infoDnsRecords

the logs only tell me that the txt is not updated correctly.
```
time="2018-10-22T22:00:02Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[XXX.de] time limit exceeded: last error: NS third-dns.netcup.net. did not return the expected TXT record [fqdn: _acme-challenge.XXX.de.]\n"
time="2018-10-22T22:00:02Z" level=error msg="Unable to obtain ACME certificate for domains \"*.XXX.de,XXX.de\" : unable to generate a certificate for the domains [*.XXX.de XXX.de]: acme: Error -> One or more domains had a problem:\n[XXX.de] time limit exceeded: last error: NS third-dns.netcup.net. did not return the expected TXT record [fqdn: _acme-challenge.XXX.de.]\n
```

at the moment i have 10 different TXT records (might be related to the "failing" infoDnsRecords

**Comment by ldez** [comment]
The error in netcup log is excepted. (once only normally)

For the error `did not return the expected TXT record`, I think of 2 solutions.
I will produce 2 images.

Perhaps we could continue to discuss the [Traefik Slack channel](https://slack.traefik.io/)
