### ISSUE TITLE
TLS-ALPN-01 challenge: unsupported TLS protocol version

### ISSUE THREAD

**Issue by mueckinger** [xenolf/lego#691]
`lego --email="myemail" --domains="mydomain" -x "http-01" -x "dns-01" run
`
leads to
`http: TLS handshake error from 10.47.18.198:54162: tls: client offered an unsupported, maximum protocol version of 300`
10.47.18.198 is my Proxy
Google says protocol version 300 refers to SSL 3.0 which is deprecated.

**Comment by mholt** [comment]
Looks like a machine on your internal network (10.47.18.198) is making TLS handshakes to yours using an old cipher suite. Noise, but has nothing to do with lego.
