### ISSUE TITLE
how to solve the " illegal instructions" problem?

### ISSUE THREAD

**Issue by flowercow** [xenolf/lego#696]
i download an released program (https://github.com/xenolf/lego/releases/download/v1.1.0/lego_v1.1.0_linux_armv7.tar.gz) and run it in a Merlin Asuswrt .
i got an error" illegal instructions"
so what's wrong with the go program?

**Comment by flowercow** [comment]
i cat /proc/cpuinfo and got info below

Processor	: ARMv7 Processor rev 0 (v7l)
processor	: 0
BogoMIPS	: 1998.84

processor	: 1
BogoMIPS	: 1998.84

Features	: swp half thumb fastmult edsp 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: Northstar Prototype
Revision	: 0000
Serial		: 0000000000000000

**Comment by xenolf** [comment]
@flowercow what's the kernel version on that? 
[This](https://github.com/golang/go/wiki/MinimumRequirements) mentions needing 3.1 depending on platform.

**Comment by flowercow** [comment]
merlin asuswrt use kernel 2.6.36.4 brcmarm.

so is there any way to run lego in such platform? may cross-compile in other Linux box, such a Debian?

**Comment by xenolf** [comment]
That kernel is plenty old and may be the source of your issue. Cross compiling would not solve the missing support in the go core.
Can you run other go programs on that platform?

**Comment by flowercow** [comment]
I found i can't run go in my platform from Entware Repo(go_1.11-1_armv7-2.6.ipk). And i find that the developer mentioned here (https://github.com/Entware/entware/issues/71) ,just because broadcom armv7 does not have floating point.

**Comment by ldez** [comment]
With Go you can compile for an architecture by setting env var.
- https://golang.org/doc/install/source#environment
- https://github.com/golang/go/wiki/GoArm

Coudl you try something like that:
```
# replace [OS] by the targeted OS
GOARCH=arm GOOS=[OS] GOARM=5 go build 
```

**Comment by flowercow** [comment]
> With Go you can compile for an architecture by setting env var.
> 
>     * https://golang.org/doc/install/source#environment
> 
>     * https://github.com/golang/go/wiki/GoArm
> 
> 
> Could you try something like that:
> 
> ```shell
> # replace [OS] by the targeted OS
> GOARCH=arm GOOS=[OS] GOARM=5 go build 
> ```

i use docker and cross compile with GOARM=5,  then lego can work in my routers. 

but i can't get an certification by tls-alpn-01 challenge. 
Does lego provides a standalone web server? or i must setup one to fit for the verfication of TLS-ALP-01 challenge?

**Comment by ldez** [comment]
I think this question is resolved.
For the question about TLS-APLN-01, follow #713
