### ISSUE TITLE
DNS Provider: Godaddy - Failed to get *.domain.tld with domain.tld as SAN

### ISSUE THREAD

**Issue by SomeBdyElse** [xenolf/lego#709]
I use traefik as a load balancer for Docker Swarm. Traefik uses lego to option SSL certificates. 

By setting the following options on the command line, I request traefik to obtain one SSL certificate: 
* *.sub.domain.tld as the main domain
* sub.domain.tld as first SAN entry

```
      --acme=true 
      --acme.email=email@domain.tld
      --acme.storage="acme.json" 
      --acme.entrypoint=https 
      --acme.acmelogging=true 
      --acme.dnschallenge.provider=godaddy
      --acme.dnschallenge.delayBeforeCheck=90
      --acme.domains='*.sub.domain.tld, sub.domain.tld'
```

Lego fails to obtain the certificate:
```
acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect TXT record "qNAASJ__redacted__c8J0" found at _acme-challenge.sub.domain.tld
```

Looking at the godaddy domain management console, my *impression* is that there are two verification processes for the sub.domain.tld, battling for the _acme-challenge TXT record, overriding the TXT record in the process. 

Once I remove the sub.domain.tld as SAN, the process works flawlessly. 

A similar issue seems to be treated here: https://github.com/josteink/le-godaddy-dns/commit/06c8d3f9b10787a35c26f5ab4e8fe9c788c9dcaa

**Comment by SomeBdyElse** [comment]
I forgot to mention that once I switch the provider to digitalocean, the process works flawlessly as well.

**Comment by ldez** [comment]
Related to #680
