### ISSUE TITLE
How to use 'TLS-ALPN-01' challenge?

### ISSUE THREAD

**Issue by flowercow** [xenolf/lego#713]
Give me some example, thanks a lot!

I use this to get a certification.

lego -d foo.mydomain --exclude='http-01' --exclude='dns-01' run

i got error below:
"acme: Error 400 - urn:ietf:params:acme:error:connection - Timeout during connect (likely firewall problem)"

But i am sure that port 443 is opened, when i setup a web server, i can visit the web from other IP address. So what should i do?

**Comment by ldez** [comment]
Hi,

The TLS-ALPN-01 require the port 443.
If your are using a reverse proxy or a web server or firewall be sure it support [ALPN](https://www.keycdn.com/support/alpn).

To test the command with the Let's Encrypt staging:
```bash
./lego -m your@email.com -x dns-01 -x http-01 -s https://acme-staging-v02.api.letsencrypt.org/directory -d mydomain.com run
```

For production:
```bash
./lego -m your@email.com -x dns-01 -x http-01 -d mydomain.com run
```

For information about the challenge it-self, you can go to https://community.letsencrypt.org/

**Comment by flowercow** [comment]
> 
> 
> i see.
> when i use lighttpd and bind port 443, i can visit the server using https connection from a remote vps which is located in USA.
> when i stop the server and use lego with tls-alpn, it report time out problem.
> i don't know why, because firewall problem? i need to do something to iptables?
> btw, i am using lego in a ASUS router hosted by merlin asuswrt.
> i run lego in bash, and use netstat to watch on it. i found that:
> tcp 0 0 1._._.1:43347 23.37.154.53:443 ESTABLISHED
> tcp 0 0 :::443 :::* LISTEN
> i think that 23.37.154.53 may be the letsencrypt acme server and lego has already listing port 443. but can't issue a certification.

i have found the problem. it is related with firewall (iptables).
i enable firewall in the router, if i use webserver provied by the fireware, the asuswrt autoconfig the firewall rules for the server. 
when i using lego, asuswrt does not autoconfig the firewall rules for lego.
After i disable the firewall, i got the cert correctly. 

Thanks a lot for all the help!
