### ISSUE TITLE
route53: Access denied on ListResourceRecordSets

### ISSUE THREAD

**Issue by anilech** [xenolf/lego#716]
Hi! Afrer upgrade to 1.2.1 got following issue with AWS DNS route53:

`[mydomainname] error presenting token: route53: AccessDenied: User: arn:aws:iam::xxxxxxxxxx:user/xxxxxxxxxx is not authorized to perform: route53:ListResourceRecordSets on resource: arn:aws:route53:::hostedzone/ZONEID`

Shoud I update the AWS security policy with the new permission or it is a bug?

**Comment by ldez** [comment]
HI, you should update the policy:

```json
{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "",
           "Effect": "Allow",
           "Action": [
               "route53:GetChange",
               "route53:ChangeResourceRecordSets",
               "route53:ListResourceRecordSets"
           ],
           "Resource": [
               "arn:aws:route53:::hostedzone/*",
               "arn:aws:route53:::change/*"
           ]
       },
       {
           "Sid": "",
           "Effect": "Allow",
           "Action": "route53:ListHostedZonesByName",
           "Resource": "*"
       }
   ]
}
```

**Comment by anilech** [comment]
Hi @ldez , thanks for the fast reply!

It is a good idea to fix AWS policy in the README.md as well.

**Comment by ldez** [comment]
Hi see https://github.com/xenolf/lego/pull/700/commits/a1bf836e30d862157e3a0c9a13c033c5b27c36c9
