### ISSUE TITLE
Add support for ClouDNS

### ISSUE THREAD

**Issue by sashkab** [xenolf/lego#717]
Add support for ClouDNS provider.

* API documentation: https://www.cloudns.net/wiki/article/42/

**Comment by rradillen** [comment]
I was also looking for this one

**Comment by tzakrajs** [comment]
Issue ought to be renamed "Add support for ClouDNS" (there is currently an extra "d")

I am creating a local branch to add ClouDNS support and will submit a pull request this weekend or so with what I have.

**Comment by sashkab** [comment]
@tzakrajs thank you!

**Comment by steve-todorov** [comment]
This is awesome! Any idea when this will be released? :)
