### ISSUE TITLE
Provide autorenew command

### ISSUE THREAD

**Issue by fenderle** [xenolf/lego#72]
I don't know if this is feasible or not as I have not too much experience with letsencrypt. 

Would it be possible to have some kind of 'autorenew' command which renews all certificates it finds in the lego directory which require renewal within a given period of days (preferable configurable)?

So one has just to schedule a daily cronjob which calls autorenew. Failures should then be outputted to stderr and exit with != 0, so that it's easy to send a failure notice email just in case.

**Comment by mholt** [comment]
You can do this already. :)

```
$ lego renew --days 30 --domains example.com
```

This will renew the certificate if it expires in 30 days or less. For more info: `lego renew --help`

**Comment by fenderle** [comment]
Great - this should solve that :+1:
