### ISSUE TITLE
Incompatibility with github.com/miekg/dns package's new updates

### ISSUE THREAD

**Issue by miadabrin** [xenolf/lego#725]
the package doesn't compile with the fresh github.com/miekg/dns package's versions since it is incompatible ( usage of dns.ErrTruncated fails)

**Comment by ldez** [comment]
For now we use:
https://github.com/xenolf/lego/blob/a5f0a3ff8026e05cbdd11c391c0e25122497c736/Gopkg.lock#L306

**Comment by miadabrin** [comment]
Is it possible to also add a .mod file?

**Comment by ldez** [comment]
I have updated the package https://github.com/xenolf/lego/pull/700/commits/2add6910e6f2fbcf8542cb6ebde771f3260424fc

And for the support for Go module see #706

**Comment by miadabrin** [comment]
Okay Cool
