### ISSUE TITLE
renew without --days fail

### ISSUE THREAD

**Issue by athanp** [xenolf/lego#755]
Latest lego (2.0.1) fails to renew certs when not using previously optional --days xx option

For example, the following does nothing, no renewal but no errors 
```
lego -a --path="/usr/local/etc/ssl/acme" --email="user@example.com" --domains="example.com" --domains="www.example.com" --http renew
```

but the next one with the addition of --days works fine
```
lego -a --path="/usr/local/etc/ssl/acme" --email="user@example.com" --domains="example.com" --domains="www.example.com" --http renew --days 99
```

Pre 2.0 lego used to force renewal when not using --days

PS: FreeBSD r12 x64, lego 2.0.1 HTTP challenge only

**Comment by ldez** [comment]
When you don't explicitly defined `--days`, now lego use a default value: `15`

```console
$ lego renew -h
NAME:
   lego renew - Renew a certificate

USAGE:
   lego renew [command options] [arguments...]

OPTIONS:
   --days value   The number of days left on a certificate to renew it. (default: 15)
   --reuse-key    Used to indicate you want to reuse your current private key for the new certificate.
   --no-bundle    Do not create a certificate bundle by adding the issuers certificate to the new certificate.
   --must-staple  Include the OCSP must staple TLS extension in the CSR and generated certificate. Only works if the CSR is generated by lego.
```

**Comment by athanp** [comment]
I didn't notice that --days is now default even when omitted.
It wasn't in lego 1.x.x AFAIK

Thanks for the clarification!

**Comment by matteocontrini** [comment]
Could you add this to the 2.0 changelog? It took me a while to understand why lego wasn't printing anything...
