### ISSUE TITLE
inconsistent use of domain in log messages

### ISSUE THREAD

**Issue by dhduvall** [xenolf/lego#772]
The log messages emitted by `validate()` in `solver_manager.go` when processing a DNS challenge don't indicate whether the validation is being done on a wildcard domain or not, making it harder to pair these messages with the ones done in other parts of the code.

Since `domain` is only being passed in for this purpose, perhaps `dns01.Challenge.Solve()` could pass its value of `domain`, rather than `authz.Identifier.Value`. It looks like the same should happen for `http01`, but `tlsapln01` seems to get it right.

**Comment by ldez** [comment]
Yes that true.
Would you create a PR?
https://github.com/xenolf/lego/blob/0574362e13a8bd7433f5d4e1987fa88869607c48/challenge/dns01/dns_challenge.go#L138
