### ISSUE TITLE
Feature request: parse gcloud credentials optional from string

### ISSUE THREAD

**Issue by vchrisb** [xenolf/lego#775]
https://github.com/xenolf/lego/blob/master/providers/dns/gcloud/googlecloud.go#L89 requires the gcloud credentials to be passed by a string pointing to a keyfile.

It would be helpful to have the option to pass the gcloud service account key directly via a string.

This could be achieved by adding an additional parameter like `GCE_SERVICE_ACCOUNT_KEY` or by allowing `GCE_SERVICE_ACCOUNT_FILE` to also be a service account string, like done in the gcloud terraform provider: https://github.com/terraform-providers/terraform-provider-google/blob/05d558d33ff2bcf8a57d3df11df0e7cbfaac0e29/google/config.go#L366

**Comment by ldez** [comment]
Closed by #776
