### ISSUE TITLE
Reading DNS provider environment variables from a file

### ISSUE THREAD

**Issue by andyforceno** [xenolf/lego#784]
Is it possible to read the dns verification environment variables from a file? I'm hesitant to pass my Cloudflare API key on the commandline.

**Comment by ldez** [comment]
Yes it's possible, you have to use: 
`CF_API_EMAIL_FILE` and `CF_API_KEY_FILE` or (`CLOUDFLARE_EMAIL_FILE` and `CLOUDFLARE_API_KEY_FILE`)

You must set a path to file that only contains the value of the key.
