### ISSUE TITLE
--email and -m false positive

### ISSUE THREAD

**Issue by Tamacun** [xenolf/lego#795]
Hello,

When I went to manually request a certificate this morning for a new domain running a Bitnami image of Ubuntu 16, I received the following error:

You have to pass an account (email address) to the program using --email or -m

However, this is the command I entered:

sudo lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --domains="www.DOMAIN" --path="/etc/lego" run

("EMAIL-ADDRESS" and "DOMAIN" placeholders added, I used real values when encountering the error)

Please advise on the issue and if you need more information to recreate the error.

![image](https://i.imgur.com/Wgp8Wxe.png)

Thank you

**Comment by ldez** [comment]
Hello, could you give the version of lego that you use?

**Comment by Tamacun** [comment]
Idez,

Thank you for the prompt reply. I am in fact using lego version 1.2.1 and dropping the TLS argument has worked. It seems the guide I have used for months was edited recently to reflect the v2 update and I didn't catch that change.

Thanks again, sorry for the operator error.

**Comment by freddyroberts** [comment]
@ldez I have updated recently from v1 to v2 and tried the v2 commands and have received the same error message. 

when I run `lego -v`: `lego version v0.4.1-0-g67c86d860a79`
I have both `lego_linux_amd64.tar.xz  and  lego_v2.2.0_linux_amd64.tar.gz`

What am I doing wrong here?

**Comment by ldez** [comment]
- untar `lego_v2.2.0_linux_amd64.tar.gz`
- `./lego -v`
