### ISSUE TITLE
why is --days not in anywhere in help?

### ISSUE THREAD

**Issue by edwardbair** [xenolf/lego#801]
I could not figure out why v2.2.0 was exiting silently and not renewing my certs. Turns out I had to specify --days XX, with XX as some value apparently greater than the default, i.e.  lego ... renew --days 90. Days feature is nice, but not properly documented. Needs to be part of lego ... help. Also would be nice to get some kind of message when renew doesn't work because certificate's expiration date is >  days argument. Having lego exit silently isn't very helpful and left me scratching my head after upgrading.

**Comment by ldez** [comment]
```console
$ lego renew --help
NAME:
   lego renew - Renew a certificate

USAGE:
   lego renew [command options] [arguments...]

OPTIONS:
   --days value   The number of days left on a certificate to renew it. (default: 30)
   --reuse-key    Used to indicate you want to reuse your current private key for the new certificate.
   --no-bundle    Do not create a certificate bundle by adding the issuers certificate to the new certificate.
   --must-staple  Include the OCSP must staple TLS extension in the CSR and generated certificate. Only works if the CSR is generated by lego.   
```

**Comment by edwardbair** [comment]
Ah! I see. The help menu is based on the command entered. And looking carefully the base help does say "Shows a list of commands or help for one command." 

Thanks for the response.  You might want to add an example to the help menu, e.g "help, h Shows a list of commands or help for one command e.g. lego renew --help" to make that jump out more for the user.
