### ISSUE TITLE
Content of CSR

### ISSUE THREAD

**Issue by Klaus-Tockloth** [xenolf/lego#802]
The Resource object has an exported field CSR (Certificate Signing Request). But this field is always empty.

```
type Resource struct {
    Domain            string `json:"domain"`
    CertURL           string `json:"certUrl"`
    CertStableURL     string `json:"certStableUrl"`
    PrivateKey        []byte `json:"-"`
    Certificate       []byte `json:"-"`
    IssuerCertificate []byte `json:"-"`
    CSR               []byte `json:"-"`
}
```

Questions:
- Is the empty CSR field a bug?
- How is it possible to obtain the CSR?

Tested with version 2.2.0 (Obtain and Renew).

**Comment by ldez** [comment]
Hello, The CSR field in `Resource` is mainly used has an input parameter for the `ReNew` method.

ReNew

https://github.com/xenolf/lego/blob/7cdfe9b36b7f6274ea8316059fbceddecabd0087/certificate/certificates.go#L359-L366

ObtainForCSR

https://github.com/xenolf/lego/blob/7cdfe9b36b7f6274ea8316059fbceddecabd0087/certificate/certificates.go#L147

**Comment by Klaus-Tockloth** [comment]
Thanks for the clarification. The CSR field currently isn't used to hold the internally created CSR. Maybe a feature request ...
