### ISSUE TITLE
Renew with bundled san certificates drops subject alternate names

### ISSUE THREAD

**Issue by sharpner** [xenolf/lego#87]
hi there, just tried to renew my bundled certificate, but it always drops my SAN. 

Tested with one --domains parameter that contained only the main certificate domain and also one test with all --domains parameter.

Tested versions: master and 0.2

Command to check:
```openssl x509 -noout -text -in /etc/ssl/letsencrypt/certificate```

**Comment by sharpner** [comment]
Lego command: 
```./lego --exclude "tls-sni-01" --domains=blub.example.com -path=/etc/ssl/letsencrypt/ --email=my@blub.example.com --http 0.0.0.0:9999 renew```

Output:
```
2016/01/29 05:28:52 [INFO][blub.example.com] acme: Trying renewal with 1806 hours remaining
2016/01/29 05:28:53 [INFO][blub.example.com] acme: Obtaining bundled SAN certificate
2016/01/29 05:28:53 [INFO][blub.example.com] acme: Could not find solver for: dns-01
2016/01/29 05:28:53 [INFO][blub.example.com] acme: Trying to solve HTTP-01
2016/01/29 05:28:54 [INFO][blub.example.com] Served key authentication
2016/01/29 05:28:56 [INFO][blub.example.com] The server validated our request
2016/01/29 05:28:56 [INFO][blub.example.com] acme: Validations succeeded; requesting certificates
2016/01/29 05:29:05 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2016/01/29 05:29:05 [INFO][blub.example.com] Server responded with a certificate.
```

**Comment by xenolf** [comment]
Please let me know if this commit does not solve your problem :)

**Comment by sharpner** [comment]
will do. thx
