### ISSUE TITLE
IPv6-only support

### ISSUE THREAD

**Issue by ghost** [xenolf/lego#88]
Pending [Let's Encrypts's IPv6 support](https://github.com/letsencrypt/boulder/milestones/IPv6%20Support) (IPv6-only hosts), I guess bootstrapping off a [magic IPv4 DNS forwarder](https://github.com/xenolf/lego/blob/d70e2869d257e5301ec9940ad8e95ea8afaad2c5/acme/dns_challenge.go#L76) is going to be a problem...

    /*  .../lego/acme/dns_challenge.go */
    func checkDNS(domain, fqdn string) bool {
    	// check if the expected DNS entry was created. If not wait for some time and try again.
    	m := new(dns.Msg)
    	m.SetQuestion(domain+".", dns.TypeSOA)
    	c := new(dns.Client)
    	in, _, err := c.Exchange(m, "8.8.8.8:53")  // <= ouch
    	if err != nil {
    		return false
    	}
    	// ...

There are systems out there that let only certain DNS forwarders through their firewalls (to mitigate cache poison attacks etc), so maybe it would be an idea to provide a configurable forwarder?

**Comment by xenolf** [comment]
Yes, I agree that this may be a problem. My initial thought was to get the standard DNS resolver for the system and use that, but it didn't work out.

Making it configurable may be the best option.

**Comment by denquixote** [comment]
Well, it can be that easy! I did not test it with an actual staging / live challenge, though.

**Comment by xenolf** [comment]
I will leave this open to track the "fascist firewall" issue :P

**Comment by xenolf** [comment]
There is not really something we can do in a broad sense. We will handle the issues if any in relation to this on a case-by-case basis.
